### ISSUE TITLE
chemin /var/www/lcs/includes/headerauth.inc.php dans le fichier index

### ISSUE THREAD

**Issue by nicolas-san** [JeromeDevome/GRR#1]
Bonjour,
j'essaye votre script, et en voyant le code de l'index, il y a ça au début:

if (!@file_exists("/var/www/lcs/includes/headerauth.inc.php"))
	error_reporting (E_ALL);

Le répertoire includes n'existe pas sur le repo, ni dans l'archive, c'est un test que vous avez pour votre environnement de dev ou un truc comme ça ?

**Comment by JeromeDevome** [comment]
Bonjour,
Depuis la version 1.9.3 GRR gère le LCS.

Doc : http://grr.devome.com/?wpdmdl=52

Pour des soucis de compatibilité de GRR entre le passage d’une version 1 à 3 il vaut mieux garder cet ligne.

**Comment by nicolas-san** [comment]
Ok, merci, je ne connaissais pas, 
le lien http://lcs.ac-caen.fr/ est mort

**Comment by nicolas-san** [comment]
Ce lien est ok http://lcs.crdp.ac-caen.fr/
