### ISSUE TITLE
phpinfo dans outils

### ISSUE THREAD

**Issue by remyd1** [JeromeDevome/GRR#100]
Bonjour,

Il y a un fichier `phpinfo.php` dans le sous-dossier `outils/` accessible sans authentification permettant à n'importe quelle personne de récupérer les informations du serveur (versions utilisées, modules utilisées, options php du `php.ini`).

J'imagine que l'intérêt était de pouvoir faire du debug, mais cela me semble particulièrement dangereux de laisser ça comme ça en production...

Cordialement,

**Comment by JeromeDevome** [comment]
Bonjour je viens de le supprimer en V4 il est intégré à l'administration
