### ISSUE TITLE
Possibilité d'empêcher les réservations de débuter un week-end ou pendant des périodes déterminées

### ISSUE THREAD

**Issue by remyd1** [JeromeDevome/GRR#103]
GRR permet d'empêcher toute réservation et utilisation d'une ressource sur des périodes définies (ex: vacances, week-ends). En revanche, il n'est pas possible d'empécher simplement une réservation de débuter un week-end ou sur une période donée (ex. : congés), sans placer la ressource comme étant complètement indisponible.
Or, une réservation peut s'étaler sur plusieurs jours / semaines...

Exemple avec un cas concret : 
On peut imaginer un prêt de matériel qui commence le vendredi avec un retour le mardi. En revanche, il est impossible d'empêcher les utilisateurs de demander une réservation le samedi, sans placer cette ressource comme indisponible. Cependant, si je met cette ressource comme indisponible le week-end, on ne pourra pas avoir cette continuité du vendredi au mardi. De plus, il se peut que le modérateur soit disponible le vendredi pour valider cette réservation, mais pas le week-end.

La ressource devrait donc pouvoir continuer à rester disponible, mais nous devrions pouvoir empêcher ces dernières de débuter un week-end.

Est-il possible de rajouter cette fonctionnalité dans la roadmap ?

Cordialement,

**Comment by ynaessens** [comment]
Bonjour,
je teste avec la release 3.4.1c : 
les réservations sont interdites le dimanche, je peux réserver une ressource du vendredi 15h. au mardi 15h., par exemple.
Le dimanche étant caché, un utilisateur ne peut pas poser de réservation commençant le dimanche, même en modifiant les données de la page edit_entry (on obtient une erreur si le créneau démarre hors réservations).
Je ne comprends donc pas ce que vous voulez que la 3.4.1c ne fait pas.
Cordialement,
YN
