### ISSUE TITLE
Problème d'ajout d'image

### ISSUE THREAD

**Issue by pierreployet** [JeromeDevome/GRR#105]
Il semblerait que la fonction import d'image portée par import.class.php ne soit plus fonctionnelle. Cela pourrait y avoir un lien avec le commit de ces derniers jours ?

Voici mes logs : 

`2020/05/06 21:40:43 [error] 902#902: *10 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Aucun fichier ou dossier de ce type in /var/www/GRR/include/import.class.php on line 75PHP message: PHP Notice:  Undefined variable: picture_room in /var/www/GRR/include/import.class.php on line 110" while reading response header from upstream, client: 172.29.125.41, server: , request: "POST /admin/admin.php?p=admin_edit_room HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "", referrer: "/admin/admin.php?p=admin_edit_room&room=1"`

j'ai également une référence à un fichier qui n'existe pas j'en cherche encore la source : 

`2020/05/06 21:40:23 [error] 902#902: *10 open() "/var/www/GRR/bootstrap/css/images/ui-icons_222222_256x240.png" failed (2: No such file or directory), client: 172.29.125.41, server: , request: "GET /bootstrap/css/images/ui-icons_222222_256x240.png HTTP/1.1", host: "", referrer: "https:///bootstrap/css/jquery-ui.css"`

Si vous avez une piste je suis preneur !

Merci d'avance pour votre aide et bon courage en cette période,
Pierre

**Comment by JeromeDevome** [comment]
Bonjour,
Avez-vous le dossier suivant personnalisation/images/ressources/ avec les
droits d'écriture. En effet le chemin est modifié.

Le mer. 6 mai 2020 à 21:54, pierreployet <notifications@github.com> a
écrit :

**Comment by pierreployet** [comment]
Bonsoir, 

Merci pour votre réponse rapide, non le dossier n'existait pas.

Après création plus de log d'erreur en revanche pas d'image sur la page de planning.

Cdlt
Pierre

**Comment by JeromeDevome** [comment]
Oui, j'ai pas terminé les modifications. J'ai fais un push pour avoir de
conflit avec d'autres modifications. J'essaie de faire cela demain soir.

Le mer. 6 mai 2020 à 22:08, pierreployet <notifications@github.com> a
écrit :

**Comment by pierreployet** [comment]
Merci beaucoup pour votre dispo

FYI une autre ref qui semble KO : 

`2020/05/06 22:08:11 [error] 5831#5831: *39 FastCGI sent in stderr: "Unable to open primary script: /var/www/GRR/my_account_modif_listes.php (No such file or directory)" while reading response header from upstream, client: 172.29.125.41, server: , request: "GET /my_account_modif_listes.php?id_area=&default_room=-1&type=ressource&action=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "", referrer: "https://grr.i-tracing.lan/admin/admin.php?p=admin_config6"`

Le fichier : my_account_modif_listes.php n'existe effectivement pas

Bonne soirée à vous,
Pierre

**Comment by JeromeDevome** [comment]
Je viens de mettre à jours les fichiers
