### ISSUE TITLE
Week view using Slots

### ISSUE THREAD

**Issue by adri-M** [JeromeDevome/GRR#11]
Hi,
I discovered a Bug in frontend on week view (Only week view with single Ressource selected)

Server Environment:
Linux 2.6.32-37-pve
MySQL 5.5.46
PHP 5.6.14
Apache 2.4.10
GRR 3.0.0-RC1 from official website (But tested with current GIT, same issue)

When using Time slot in my GRR (Monday To Friday, Slots Morning/Afternoon per day in my environment ), all the afternoons (only! aka second slot of a day) are not diplayed at all. I have the plus in the case of afternoon instead of the event.

Process to reproduce:
- Configure slots "Matin" / "Après-midi"
- Add a reservation for afteroon (1 slot):
   Appear in (global or ressource) month view.
   Appear in (global or ressource) day view.
   --> Bug: Appear in global week view only. Go to Ressource week view: EMPTY!
- Add a reservation for morning (1 slot):
   Appear in (global or ressource) month view.
   Appear in (global or ressource) day view.
   Appear in (global or ressource) week view
- Add a reservation for an all day (Aka choose 2 slots starting morning):
   Appear as expected in (global or ressource) month view. (2 slots booked: morning and afternoon)
   Appear as expected in (global or ressource) day view. (2 slots booked: morning and afternoon)
   --> Bug: Appear as expected in global week view only. Go to Ressource week view: ONLY MORNING APPEAR! Only 1 slot appear booked in this view.

Please help, this is a major Bug to use this GRR Version.
Result of $debug_flaged enabled in week.php attached, with 2 print screens:
Week global view (Work) and Week ressource view (Not work)
In debug i can see my 3 booked slots but the two located afternoon don't appear, only morning appear.

PS: I've found other bugs in Admin frontend but using the GRR-RC i'm not surprised and it's not critical for using GRR.

Thank's for all your work, GRR v1 works perfectly since many years in my company!
Adrien

![globl_week_view](https://cloud.githubusercontent.com/assets/1553910/11597130/d7cdeca0-9ab9-11e5-8715-21c2ebf759dc.jpg)
![week_view](https://cloud.githubusercontent.com/assets/1553910/11597128/d7abd6b0-9ab9-11e5-9293-b06fb52d4ad0.jpg)
[Debug_grr_week.txt](https://github.com/JeromeDevome/GRR/files/52353/Debug_grr_week.txt)

**Comment by nicolas-san** [comment]
thanks for reporting here !
We look into asap

**Comment by laedo** [comment]
Hi, 
i have the same problem in 2019, are you still workin in this project?.

I have used GRR for many years, previous versions do not have that problem.

**Comment by nicolas-san** [comment]
Hi, sorry, I did not work anymore on this project, I can't help you

**Comment by ynaessens** [comment]
Hi
I worked on week.php to fix the bug. 
Have you installed the latest version, which is on the devel3 branch ?
Kind regards
YN

**Comment by laedo** [comment]
Thanks for your quick reply, I'll try the latest version,

regards
