### ISSUE TITLE
probleme de reservation pour un utilisateur LDAP

### ISSUE THREAD

**Issue by Benance** [JeromeDevome/GRR#120]
Bonjour,
Suite à une migration de GRR 1.9.6 vers GRR 3.4.1b, un utilisateur (et un seul, pour le moment...) avec les droits "usager" ne peut pas effectuer de reservation sur une ressource pourtant reservable par tout le monde.
Lorsqu'il valide sa réservation, il tombe sur le message d'erreur: "Attention, réservation impossible : Vous tentez de réserver une ressource au nom d'une autre personne alors que vous n'avez pas les droits suffisants."
Y aurait-il une solution pour débloquer la situation?
Merci d'avance pour vos retours

**Comment by ynaessens** [comment]
Bonjour 
Avez-vous essayé de supprimer cet utilisateur puis de tenter une reconnexion suivie d’une réservation ?
À ce que vous esposez, le nom d’utilisateur doit être différent du nom issu du LDAP. Si c’est le seul cas problématique, c’est étonnant. 
Cordialement 
YN

**Comment by Benance** [comment]
Bonjour,
Je pensais essayer cette solution en effet, mais je n'étais pas sûr de mon coup.
Vous pensez donc que je peux tout à fait supprimer l'utilisateur sans risque? Il pourra de nouveau être automatiquement recrée lors d'une nouvelle connexion?
Merci d'avance pour votre confirmation.

**Comment by ynaessens** [comment]
Bonjour,
en principe c’est ainsi que fonctionne l’authentification LDAP.
Par prudence et pour vérifier l’origine du problème, je vous suggère de créer un nouvel utilisateur LDAP ayant les mêmes caractéristiques que l’utilisateur problématique et de tester sur ce nouvel utilisateur la procédure complète : intégration à Grr, réservation, suppression de Grr et réintégration. 
En notant ce qui est OK ou KO. 
Cordialement 
YN

**Comment by anteldan** [comment]
Bonjour,

Cet usager en compte LDAP était-il déjà présent dans votre GRR en V 1.9.6 ?
Et avez-vous déroulé le scenario de @ynaessens  ?

J'utilise (encore) la V 3.4.1b et nous n'avons pas de problème avec les comptes externes dans GRR (en LDAP), aussi bien ceux qui sont inscrit automatiquement dans la base suite à leur première connexion ou ceux que nous avons créés avant leur première connexion afin de leur paramétrer en avance de phase des privilèges. 

Notre configuration est :
- Il faut obligatoirement être connecté et avoir le statut "usager" pour consulter, réserver
- les comptes ont par défaut le statut "usager" lors de leur création.

Cordialement,
Daniel

**Comment by Benance** [comment]
Bonjour,
Oui cet usager était déjà présent dans le GRR en V 1.9.6
Je n'ai pas encore essayé la proposition faite par ynaessens.
Je vais m'en occuper aujourd'hui et reviendrai poster un retour ici.

**Comment by Benance** [comment]
Bonjour,
la solution proposée par @ynaessens était la bonne: suppression de l'utilisateur, puis reconnexion de cet utilisateur et réservation: tout fonctionne de nouveau correctement.
Encore merci
