### ISSUE TITLE
Échec d'installation - "La connexion au serveur MySQL a échoué"

### ISSUE THREAD

**Issue by belgianGeek** [JeromeDevome/GRR#126]
Bonjour tout le monde,

J'ai récemment tenté d'installer GRR v3.4.1e sur une machine virtuelle Ubuntu Server. J'ai donc installé les paquets requis (apache2, mysql-server et les différents modules PHP) et téléchargé la release la plus récente du projet via GitHub.

Néanmoins, l'installation échoue toujours à l'étape 2 avec le message _La connexion au serveur MySQL a échoué_. Je précise que le serveur est bien démarré, que les permissions sur les différents fichiers sont correctes (accès en lecture et écriture) et que j'ai essayé d'installer GRR via le compte root MySQL, dont j'ai configuré le mot de passe au préalable via la commande _mysql_secure_installation_.

Si vous avez des idées pour résoudre ce problème, je suis preneur.

**Comment by ynaessens** [comment]
Bonjour 
Avez-vous d’autres applications php/MySql qui tournent sur ce serveur ?
Selon les éléments que vous donnez, je pense à un paramétrage incorrect, notamment le port sur lequel écoute MySql, puisque vous semblez sûr de votre utilisateur. 
Cordialement 
YN

**Comment by belgianGeek** [comment]
Bonjour,

Il s'agit de la seule application PHP/MySQL exécutée sur le serveur car c'est une machine virtuelle dédiée. Le port utilisé par MySQL est le 3306 (celui par défaut si je ne me trompe pas).

Par contre, j'ai édité le fichier connect.inc.php avant de débiter l'installation afin d'y indiquer les identifiants root pour créer le base de données. Est-ce la bonne manière de faire ?

Merci pour votre aide 😉

**Comment by ynaessens** [comment]
Il n’est pas nécessaire d’éditer le fichier connect.inc.php quand on utilise la procédure d’installation automatique. 
Essayez de relancer l’installation après avoir supprimé ou renommé votre fichier. Le logiciel doit vous demander les éléments nécessaires à la connexion et ensuite il crée le fichier connect.inc.php à partir des valeurs reçues.

**Comment by belgianGeek** [comment]
Je n'étais pas au courant... je vais essayer et je vous tiens au courant. Merci pour ce retour rapide, ça fait plaisir à lire.

**Comment by belgianGeek** [comment]
Cela ne fonctionne toujours pas... Je suis pourtant parti d'une nouvelle installation Ubuntu Server dans VirtualBox, sans avoir modifié le fichier `connect.inc.php`. J'ai par contre remplacé les accents présents dans le fichier `Installation/tables.my.sql` afin d'éviter toute erreur d'encodage, mais sans succès.

Cela serait-il dû à une version de PHP incompatible ? J'utilise la version 7.4.

Je me base sur ce [tutoriel](https://ulvoasvincent.files.wordpress.com/2018/06/grr.pdf) pour effectuer l'installation. Il est un peu vieux mais bien documenté.

**Comment by ynaessens** [comment]
Le tutoriel est à peu près juste, sauf qu’il n’est pas nécessaire d’éditer le fichier connect.inc.php.
Nous n’avons pas eu de retour de difficultés dues à la version 7.4 de php. 
Peut-être un problème de communication entre php et mysql ? C’est pourquoi je vous demandais si vous avez une autre application sur ce serveur. 
Que donnent les fichiers de log (apache access.log, error.log et php error.log)?

**Comment by belgianGeek** [comment]
Je vous confirme que ce serveur est dédié à GRR.

Le fichier `/var/log/apache2/eror.log` contient toujours cette erreur :
`[Thu Nov 26 11:32:33.023598 2020] [php7:warn] [pid 662] [client 10.0.30.206:53733] PHP Warning:  mysqli_connect(): (HY000/1698): Access denied for user 'root'@'localhost' in /var/www/html/grr/installation/install_mysql.php on line 313, referer: http://10.0.31.70/grr/installation/install_mysql.php?etape=1
[Thu Nov 26 11:32:33.023618 2020] [php7:warn] [pid 662] [client 10.0.30.206:53733] PHP Warning:  mysqli_errno() expects parameter 1 to be mysqli, bool given in /var/www/html/grr/installation/install_mysql.php on line 314, referer: http://10.0.31.70/grr/installation/install_mysql.php?etape=1`

Je ne comprends pas pourquoi l'accès est interdit à l'utilisateur _root_ puisque le mot de passe entré dans l'interface est celui configuré localement sur le serveur MySQL avec la commande _mysql_secure_installation_.

**Comment by ynaessens** [comment]
Le message est clair : access denied
Pouvez-vous vous connecter à mysql avec le compte root en ligne de commande ?
Sinon il semble que le port 53733 est utilisé par le serveur, cela est-il lié ?
Désolé de ne pouvoir aider davantage.

**Comment by belgianGeek** [comment]
Bonsoir,

Après m'être plongé dans le code, j'ai remarqué qu'il y avait une erreur dans le fichier `/installation/install_mysql.php` à la ligne 313, car la fonction mysqli_connect utilisait de mauvais paramètres, chargés depuis le fichier `/include/connect.inc.php`. Je n'ai eu besoin que de remplacer les paramètres existants par ceux récupérés par les différentes fonctions ISSET présentes en début de fichier et tout à fonctionné impeccablement bien. je suis loin d'être un expert en PHP/MySQL, mais ces quelques modifs ont fonctionné dans mon cas.

En résumé, la ligne 313 du fichier contenait ceci : `$db = @mysqli_connect("$dbHost", "$dbUser", "$dbPass", "$dbDb", "$dbPort");`, que j'ai remplacé par cela : `$db = @mysqli_connect($adresse_db, $login_db, $pass_db, "", $port_db);`.

J'espère que cette erreur sera patchée car c'est vraiment très embêtant de ne pas pouvoir installer le programme du premier coup... Dans tous les cas, merci pour votre aide 👍

**Comment by ynaessens** [comment]
Bonsoir,
c'est étrange : la modification que vous suggérez correspond au code déposé il y a 7 mois !
Je clos donc cette discussion.
Profitez bien de GRR et n'hésitez pas à revenir si vous débusquez d'autres problèmes.
Cordialement,
YN
