### ISSUE TITLE
Impossible de modifier des réservations suite à la migration vers Ubuntu 20.04

### ISSUE THREAD

**Issue by belgianGeek** [JeromeDevome/GRR#130]
Bonjour,

Nous utilisons plusieurs machines virtuelles Ubuntu pour héberger différentes instances de GRR version 3.2.0. Ces machines étant de vieilles installations, toujours en Ubuntu version 16.04, nous les avons récemment mises à jour vers la version 20.04 d'Ubuntu.

Désormais, aucune modification n'est possible, même avec le compte administrateur... Est-ce dû à la version (7.4) de PHP ? Aussi, je ne sais pas comment mettre à jour la base de données de GRR si cela s'avère nécessaire.

Voici le message d'erreur lors d'une tentative de suppression de réservation :

`Accès refusé : Vous n'avez pas les droits suffisants pour effectuer cette opération.` => bizarre, je suis connecté avec le compte administrateur...

Et si j'essaie de copier une réservation, j'obtiens le même résultat :

````
Warning: Illegal string offset 'start_time' in /var/www/html/include/mrbs_sql.inc.php on line 698

Warning: Illegal string offset 'end_time' in /var/www/html/include/mrbs_sql.inc.php on line 699

Warning: Illegal string offset 'entry_type' in /var/www/html/include/mrbs_sql.inc.php on line 700

Warning: Illegal string offset 'repeat_id' in /var/www/html/include/mrbs_sql.inc.php on line 701

Warning: Illegal string offset 'room_id' in /var/www/html/include/mrbs_sql.inc.php on line 702

Warning: Illegal string offset 'timestamp' in /var/www/html/include/mrbs_sql.inc.php on line 703

Warning: Illegal string offset 'beneficiaire' in /var/www/html/include/mrbs_sql.inc.php on line 704

Warning: Illegal string offset 'name' in /var/www/html/include/mrbs_sql.inc.php on line 705

Warning: Illegal string offset 'type' in /var/www/html/include/mrbs_sql.inc.php on line 706

Warning: Illegal string offset 'description' in /var/www/html/include/mrbs_sql.inc.php on line 707

Warning: Cannot assign an empty string to a string offset in /var/www/html/include/mrbs_sql.inc.php on line 707

Warning: Illegal string offset 'room_id' in /var/www/html/edit_entry.php on line 79

Warning: Illegal string offset 'room_id' in /var/www/html/edit_entry.php on line 80

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3658

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3667

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3687

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3689

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3690

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3691

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3692

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3694

Notice: Trying to access array offset on value of type int in /var/www/html/include/functions.inc.php on line 3695
Accès refusé

Vous n'avez pas les droits suffisants pour effectuer cette opération.

Retour à la page précédente
````

Je suis preneur de toute piste de solution.

Merci d'avance pour vos réponses.

**Comment by ynaessens** [comment]
Bonjour,
pour php 7.4, il faut essayer de mettre en place la dernière version stable [https://github.com/JeromeDevome/GRR/releases/tag/v3.4.1f](url) et revenir nous dire si des problèmes persistent.
Merci !
Cordialement,
YN

**Comment by belgianGeek** [comment]
Je vais essayer d'installer la nouvelle version et de réimporter une sauvegarde. Je vous tiens au courant.

Merci pour votre aide.

**Comment by belgianGeek** [comment]
Ça a l'air de fonctionner avec la nouvelle version, merci. Néanmoins, il semble que j'ai perdu des données lors de l'export SQL de la base de données de l'ancien GRR (en version 3.2) vers le nouveau, qui est en version 3.4.1f. Malgré une mise à jour de la base de données après import dans la nouvelle instance, des données sont toujours absentes...

Pourriez-vous m'indiquer dans quelle(s) table(s) les réservations sont-elles enregistrées ? Connaissez-vous un moyen de résoudre ce problème ?

**Comment by belgianGeek** [comment]
Bonjour,

Finalement, nous avons trouvé le souci : le fuseau horaire était réglé sur GMT-7 dans le fichier `/include/config.inc.php`, ce qui a provoqué un décalage de 6h de toutes nos réservations. Il n'y a donc pas eu de pertes de données mais uniquement des cinfilts qui ont fait disparaître certaines réservations.

Pour plus d'infos, voir ce sujet : [https://site.devome.com/fr/kunena/aide-installation-et-mise-ajour/91-probleme-de-decalage-horaire-suite-a-la-mise-a-jour-en-3-3-1](https://site.devome.com/fr/kunena/aide-installation-et-mise-ajour/91-probleme-de-decalage-horaire-suite-a-la-mise-a-jour-en-3-3-1).

Je clos donc le sujet puisque mon problème est résolu.

Merci pour votre aide !
