### ISSUE TITLE
Un probleme de l'affichage pour imprimer en fonction du navigateur 

### ISSUE THREAD

**Issue by steven04458** [JeromeDevome/GRR#132]
Bonjour

Sur FireFox l'écrant d'impression présent des bug. 
J'ai donc essayer sur un autre navigateur (chrome), est les fameux bug n'apparaissent pas sur celui ci.

------Voici l'affichage sur FireFox------

Exemple 1:
![Affichage_FireFox_1](https://user-images.githubusercontent.com/62381938/107760781-9c1afb00-6d2a-11eb-9596-7e7da792d472.png)
Exemple 2:
![Affichage_FireFox_2](https://user-images.githubusercontent.com/62381938/107760784-9d4c2800-6d2a-11eb-8c7c-e6b2102cc626.png)
--------------

**Comment by ynaessens** [comment]
Bonjour 
Ça le fait avec les scripts de quelle branche / release ?
À bientôt 
YN

**Comment by steven04458** [comment]
Bonjour 
je suis sur la version release 3.4.1f

**Comment by ynaessens** [comment]
Bonjour,
je reproduis bien le problème, c'est la page week_all, n'est-ce pas ?
Edge, Opera et Chrome donnent un rendu correct, Firefox sort les blocs formant les réservations du jour du tableau principal...
apparemment, il suffit de modifier l'attribut height:100% de la classe a.poplight dans styles.css
c'est reporté dans le commit https://github.com/JeromeDevome/GRR/commit/e26b1f3fda3e8ab7a24abb7a72262e139e4021a1
Merci de confirmer l'efficacité du correctif

**Comment by steven04458** [comment]
Bonjour,
En modifiant l'attribut height:100% , cela a bien corriger le bug .
Merci a vous pour la correction du bug
