### ISSUE TITLE
Numéro de téléphone avec des espaces

### ISSUE THREAD

**Issue by anteldan** [JeromeDevome/GRR#138]
Version 3.4.1b
Un utilisateur saisit une demande de réservation modérée, dans le formulaire il y a un champ pour le numéro de téléphone. Le numéro de téléphone est saisi avec des espaces tous les 2 chiffres.
L'utilisateur enregistre le formulaire.
La page suivante edit_entry_handler.php?oldRessource=29 indique :
**2. Numéro de téléphone : vous devez spécifier un nombre.
Retour à la page précédente**

Le http_referer est désactivé sur le serveur : le lien est sans effet.
Le champ numérique pour le numéro de téléphone ne devrait-il pas pouvoir accepter les espaces ?

**Comment by ynaessens** [comment]
Bonjour,
oui, je n'avais pas pensé à cela : c'est le type numeric qui pose problème dans ce cas. Reste à trouver une regex qui accepte les nombres ou les espaces ;-)
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
je ne vois pas comment vous avez obtenu ce message d'erreur : avez-vous fait une personnalisation ?
De mon côté, votre demande m'a fait lever une erreur de nommage, corrigée sur la branche 3.4.1.
Le traitement du formulaire de contact a été revu dans la 3.4.2, je n'en ferai pas plus sur la 3.4.1.
Pour ce qui est du comportement lorsque http_referer est inactivé, là aussi j'ai apporté des modifications précédemment. 
Pouvez-vous mettre à jour ?
Cordialement,
YN
