### ISSUE TITLE
Erreur lors de l'import de réservations au format CSV

### ISSUE THREAD

**Issue by belgianGeek** [JeromeDevome/GRR#145]
Bonjour,

Nous aimerions migrer notre gestion de locaux depuis un logiciel ERP vers MyGRR. J'ai donc exporté les réservations présentes dans l'ERP au format CSV, adapté le fichier selon les directives présentes dans l'interface d'import de GRR et essayé un import dans une instance de test (version GRR 3.4.1e, PHP 7.4, MySQL 8.0.23).

Vous trouverez le descriptif de l'erreur dans la capture d'écran ci-dessous :
![image](https://user-images.githubusercontent.com/39968047/119840539-611d8b80-bf05-11eb-9bdb-d471503efa68.png)

Pourriez-vous tenter de résoudre ce problème sachant que nous aimerions acheter un abonnement MyGRR ? Nous avons plus de 1000 réservations, ce qui serait très embêtant à encoder manuellement...

Je vous remercie pour votre aide et vous souhaite une excellente après-midi.

Bien à vous,
MV

**Comment by ynaessens** [comment]
Bonjour,
je crois que ce problème a été réglé. 
Il faudrait que vous récupériez les fichiers en tête de la branche 3.4.1 pour avoir les derniers correctifs. 
Cordialement
YN

**Comment by belgianGeek** [comment]
Bonjour,

J'ai remarqué que l'ensemble de nos instances GRR (hébergées avec MyGRR Unlimited) ont été mises à jour vers la version 3.4.1g et vous en remercie.

Le problème reste néanmoins malheureusement entier, avec un message d'erreur identique à celui joint à mon premier commentaire.

Pourriez-vous tenter de le résoudre s'il-vous-plaît ?

Merci, belle journée,
MV

**Comment by JeromeDevome** [comment]
Bonjour,
Je vous invite à transmettre votre fichier d'import à l'adresse de contact
de MyGRR, pour avoir une solution rapidement.

Cordialement,
Jérôme BERNARD

**Comment by belgianGeek** [comment]
Bonjour,

Notre problème ayant été résolu et les scripts GRR ayant été corrigés, je ferme cette issue.
