### ISSUE TITLE
gestion et documentation plugin

### ISSUE THREAD

**Issue by remyd1** [JeromeDevome/GRR#153]
Bonjour,

J'ai vu passer quelques messages sur la mise en place d'un système de plugins.

Comme discuté [ici](#60], j'ai un code, qui permet, une fois la ressource modérée et validée, de pousser vers un calendrier caldav (nextcloud en l'occurence). Il y a encore un peu de bash dedans, mais je devrai pouvoir le convertir assez facilement.

Merci de me tenir au courant lorsque la documentation des plugins sera disponible.

Cordialement,

**Comment by ynaessens** [comment]
bonjour @remyd1 , 
peut-être ajouter cette référence pour vous aider à contribuer : https://github.com/JeromeDevome/GRR-Modules
Cordialement,
YN

**Comment by remyd1** [comment]
Bonjour,

Merci pour l'info. Je regarderai ça.

Le README central n'est, par contre, pas très causant.

**Comment by Aurely9n** [comment]
Bonjour @ynaessens  ,

Cette discussion m’intéresse beaucoup car je souhaite produire un plugin pour personnaliser mon installation de GRR. La version 4.10 qui fonctionne très bien et rapidement chez moi (quel bonheur).
J'ai regardé le code du module de test ci-dessus et d'après ce que je vois, c'est qu'il n'est pas possible d'ajouter des fichiers CSS, JS ou de surcharger des requêtes du code de base de GRR.
Par exemple, si je souhaite qu'un évenement javascript se lance lorsque je fait un action sur un champ de la page "edit_entry", comment faire avec mon plugin custom ? Il aurait fallu que je puisse surcharger cette page spécialement avec un fichier .js de mon module custom...

Cordialement !

**Comment by ynaessens** [comment]
Bonjour @Aurely9n,
je n’ai aucune piste à vous proposer. D’après le code, les modules ajoutent des portions de code html aux pages. Les limitations du traitement des données sont effectivement mystérieuses… 
Pour ce qui est du style, il doit être possible de faire quelque chose, et dans le respect des prescriptions html5 ?…
Cordialement,
YN
