### ISSUE TITLE
calendrier des vacances à actualiser

### ISSUE THREAD

**Issue by Juliencpi** [JeromeDevome/GRR#16]
Bonjour,
la partie "Afficher les Vacances scolaire et les jours fériés (France)" est incorrecte du fait du changement de zone prévue pour l'année 2015/2016. Pourriez vous procéder à la modification pour la prochaine version ?
http://www.education.gouv.fr/pid25058/le-calendrier-scolaire.html?annee=159&zone=0&search_input=%C2%A0D%C3%A9partement%2C+Code+postal+ou+ville
Merci et bon courage

**Comment by jmmassion** [comment]
Bonjour,
Y a t'il une procédure que l'on puisse appliquer nous-même dans l'attente d'un correctif ?
Merci par avance

**Comment by jmmassion** [comment]
Finalement je fais les questions et les réponses ...
La mise à jour peut s'effectuer dans le fichier vacances.xml
Cordialement

**Comment by ynaessens** [comment]
bonjour,
le fichier vacances.xml a été mis à jour à partir de celui diffusé par Index-Education
