### ISSUE TITLE
[GRR 3.4.0] add SSO functionnality

### ISSUE THREAD

**Issue by ASLLR** [JeromeDevome/GRR#165]
Hello everyone, 

i would like to know if the implementation of SSO funtionnality is on the roadmap ? 

I use lemonldapng and i'd like to use CAS, or in a perfect case, Openid to connect on the app.

Thank in advance,

**Comment by ASLLR** [comment]
Hello, thank you for reply.

i can't help you because i'm bad in dev but if you estimate the time and cost to develop openid, i will try to search a sponsor for that.

Thank in advance

**Comment by ynaessens** [comment]
Hello,
I have no idea of how long it would be to add OpenID connectivity to GRR.
But if you know someone how has time or resource to help, it would be great.
Kind regards,
YN
