### ISSUE TITLE
PB affichage calendrier en mode dockerisé

### ISSUE THREAD

**Issue by sisitototest** [JeromeDevome/GRR#167]
Bonjour,
J'utilise une image php:7.3-fpm-alpine3.13 avec musl-locales-master.

Fichier /etc/profile.d/locale.sh pour la configuration des locales par défaut
export CHARSET=UTF-8
export LANG=fr_FR.UTF-8
export LC_COLLATE=fr_FR.UTF-8

Réponse de la commande sur alpine 3.13
#locale
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE=fr_FR.UTF-8
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES=fr_FR.UTF-8
LC_ALL=fr_FR.UTF-8

Merci beaucoup pour votre aide et pour tout autre piste

**Comment by ynaessens** [comment]
Bonjour,
quel est votre problème ?
Le calendrier ne s'affiche pas correctement ? est-il en anglais ?
Cordialement,
YN

**Comment by sisitototest** [comment]
Bonjour,

Nous utilisons GGR en mode docker https://github.com/ptigiloo/grr-docker.
Avez vous valider cette solution Docker?
Allez vous maintenir cette solution au cours des montées de version?

Pour info ptigiloo avait utilisé une image alpine qui ne gère pas bien les
locales la modification en debian bulleseye a été faite hier et je confirme
son bon fonctionnement.

Merci beaucoup pour votre retour

Bonne journée

**Comment by ynaessens** [comment]
Merci pour votre retour.
Pour la dockerisation, il faudrait voir avec ptigiloo s'il compte maintenir son travail à jour.
Cordialement,
YN
