### ISSUE TITLE
.gitignore dans les releases

### ISSUE THREAD

**Issue by skid9000** [JeromeDevome/GRR#170]
Bonjour,

Est-il possible d'intégrer le fichier .gitignore dans les releases de GRR ?
Je gère les mises à jour intégralement via git (avec les tags) et l'intégration de ce fichier dans les releases aiderait beaucoup.

Merci !

**Comment by ynaessens** [comment]
Bonjour,
pour faire cela, ne vous suffit-il pas de cloner la branche que vous suivez ?
Cordialement 
YN

**Comment by skid9000** [comment]
Bonjour,

Non, car l'intégration du fichier dans les releases simplifierait le processus de mise à jour à seulement 2 commandes :
- git fetch
- git checkout v4.x.y

Il suffira ensuite de diff les fichiers de config avec les .ori pour vérifier si il y a des changements à réaliser.

**Comment by ynaessens** [comment]
Bonjour 
Dites-moi si je me trompe : il me semble que seul config.inc.php pose problème, les autres fichiers de configuration sont soit à modifier à la main, soit modifiés par un script de configuration.
Si je n’ai pas compris, merci de préciser votre demande.
Cordialement 
YN

**Comment by skid9000** [comment]
Bonjour,

Vous avez tout juste.
L'avantage d'avoir d'avoir le .gitignore serait qu'au git checkout, ça écrase tout le projet sauf ces fichiers de configuration, ce qui est un gain de temps considérable. Mais permet également en cas de coquille de rétrograder rapidement à la version précédente.

**Comment by ynaessens** [comment]
Bonjour,
j'ai rétabli le .gitignore dans la branche devel3 https://github.com/JeromeDevome/GRR/commit/e3be7cc653989701e666d6b084b3ac5af9a82033
Pouvez-vous jouer le scénario que vous décrivez et dire si c'est fonctionnel ?
Merci pour votre retour.
Cordialement,
YN

**Comment by skid9000** [comment]
Bonjour,

Yes nickel !
Merci beaucoup !
