### ISSUE TITLE
Modification réservation - date de début erronée (3.4.3 RC3)

### ISSUE THREAD

**Issue by ovigy** [JeromeDevome/GRR#174]
Bonjour,
nous rencontrons un bug qui persiste sur la dernière version 3.4.3 RC3.

Vue "week" : dans le cas d'une réservation sur plusieurs jours, si on souhaite la modifier sans cliquer sur le début de la réservation, la date de début par défaut est erronée lors de la modification.

**Exemple : réservation du 4 au 6/01**

![GRRnew_editResa_5-01](https://user-images.githubusercontent.com/7659434/152561138-90664c19-779c-4a21-af60-45d4df8a05c2.png)

- **PB** : si clic sur le planning le 5/01, la date de début qui est affichée par défaut est le 06/01
![GRRnew_editResa_dateDebut](https://user-images.githubusercontent.com/7659434/152561195-709efcf4-fcee-4a77-9d91-ca19559983bd.png)

- **OK** : si clic sur le planning le 4/01, la date de début qui est affichée par défaut est la bonne (04/01)
![GRRnew_editResa_dateDebut_OK](https://user-images.githubusercontent.com/7659434/152561211-d3373cb2-8ee6-48fd-9da5-a09e2333d1c0.png)

J'espère et je pense que ce bug sera plus facile à résoudre :-)
A voir sur les autres vues ?
Merci pour votre aide.

Cordialement,
Oana

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre retour d'expérience. Je pense que ce commit corrige le problème : https://github.com/JeromeDevome/GRR/commit/1d0ee6e082c6361bd40c1e766a487b750170c22e
Cordialement,
YN

**Comment by ovigy** [comment]
Bonjour,
merci pour la correction, cela fonctionne bien sur la v3.4.3 (de test ici). Si jamais vous aviez une correction compatible avec la 3.4.2b (en production pour l'instant), ce serait super.
Merci pour votre aide.
Cordialement,
Oana

**Comment by ynaessens** [comment]
Bonjour,
pour la 3.4.2, je propose ce commit https://github.com/JeromeDevome/GRR/commit/33640bba434113dc7d13e340065e78e87c68a0af
pour le mieux, je vous conseille de récupérer l'ensemble des modifications depuis la 3.4.2d, en procédant comme pour une mise à jour.
Cordialement,
YN

**Comment by ovigy** [comment]
Le commit "33640bb" ne permet pas de modifier une ressource car en cliquant sur une ressource, seul le bouton "fermer" apparaît. Tous les autres boutons "modifier, copier, échanger et effacer" n'apparaissent pas. 
Désolée pour ces retours en arrière pour la 3.4.2. Je vais voir pour passer en 3.4.3 prochainement.
Merci
Oana

**Comment by ynaessens** [comment]
Je pense que c'est un problème de droits d'accès à la réservation que vous visualisez : je ne fais pas ce constat sur mon installation de test.
Avez-vous bien récupéré l'ensemble des fichiers au commit https://github.com/JeromeDevome/GRR/commit/33640bba434113dc7d13e340065e78e87c68a0af ? Car il est possible que des modifications intermédiaires aboutissent à cette absence des liens attendus.
Cordialement,
YN

**Comment by ovigy** [comment]
J'ai bien récupéré les 2 scripts "edit_entry.php" et "view_entry.php". Je l'ai refait au cas où mais le problème persiste.
Avec les anciennes versions, j'ai bien accès à la modification. Mon compte est "admin".

**Comment by ynaessens** [comment]
Merci de confirmer mon hypothèse, et mes excuses pour m'être mal exprimé.
Vous devriez récupérer tous les scripts à partir de la page https://github.com/JeromeDevome/GRR/tree/33640bba434113dc7d13e340065e78e87c68a0af (bouton Code, puis Download zip) et ensuite procéder comme pour une mise à jour. La seule différence devrait être que la base de données n'a pas été modifiée et donc GRR ne devrait pas demander de procéder à une mise à jour de la base.

**Comment by ovigy** [comment]
C'est super, ça fonctionne!
Merci
Oana
