### ISSUE TITLE
[GRR3.4.3] bug sélection crénaux heures par défaut

### ISSUE THREAD

**Issue by Matthieu-Stras** [JeromeDevome/GRR#179]
Bonjour,

J'ai constaté un bug de prise en compte des heures lors de la sélection d'un créneau spécifique.
Si je sélectionne un créneau disponible à une heure spécifique via la croix sur un calendrier (ex : 10h à 11h), la sélection par défaut du créneau avant validation correspond aux heures de début et de fin de la plage journalière (ex: 8h00 à 18h00).

Cordialement,

**Comment by ynaessens** [comment]
Bonjour,
je ne reproduis pas ce bug avec les fichiers de ce commit https://github.com/JeromeDevome/GRR/commit/21d97eb14b6bbf750f7bb45fa78cd4ce2f5687d9
Cordialement,
YN
