### ISSUE TITLE
grrV3 - maj RC2

### ISSUE THREAD

**Issue by Juliencpi** [JeromeDevome/GRR#18]
Bonjour,
après mis a jour du grr3 en RC2 (ou installation direct en RC2) dans l'administration, s'affiche le numéro de version Numéro de version : GRR3.0.0a RC1.. Bizarre non ?

**Comment by JeromeDevome** [comment]
Bonjour, 
En effet un oubli de changement dans un fichier. On y pensera dans la prochaine version.
