### ISSUE TITLE
Mauvaise selection du champ Authentification dans Modification User

### ISSUE THREAD

**Issue by l-2-m** [JeromeDevome/GRR#180]
Sur la branche Master, il y a une erreur dans admin\templates\admin_user_modify.twig dans les lignes 30 et 31 qui empêche la bonne sélection du mode d'Authentification.

`<option value="locale" {% if utilisateur.disponible == 'local' %} selected {% endif %}>{{ trad.authentification_base_locale }}</option><option value="externe" {% if utilisateur.disponible == 'ext' %} selected {% endif %}>{{ trad.authentification_base_externe }}</option>`
ça devrait être 
`<option value="locale" {% if utilisateur.source == 'local' %} selected {% endif %}>{{ trad.authentification_base_locale }}</option><option value="externe" {% if utilisateur.source== 'ext' %} selected {% endif %}>{{ trad.authentification_base_externe }}</option>`

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre retour.
C'est en principe corrigé dans ce commit : https://github.com/JeromeDevome/GRR/commit/ea348d1987cee702167c3947783a397e8638f80b
Cordialement,
YN

**Comment by JeromeDevome** [comment]
Merci à vous
