### ISSUE TITLE
Pouvoir définir plusieurs serveurs SSO/CAS

### ISSUE THREAD

**Issue by skid9000** [JeromeDevome/GRR#184]
Bonjour,

Nous utilisons actuellement GRR dans un contexte qui fait que nous avons de multiples entités avec des serveurs CAS différents.

Est-il envisageable qu'on puisse définir plusieurs serveurs CAS dans le panel d'admin ?

Merci.

**Comment by ynaessens** [comment]
Bonjour,
la configuration actuelle permet l'authentification par UNE source externe ou sur la base de données interne de GRR.
Dans le cadre de la refonte de l'authentification, il serait envisageable de permettre plus d'une source externe. Cela nécessite vraisemblablement du temps...
Dans votre cas, il vous est peut-être possible de définir une interface intermédiaire qui joue le rôle de serveur CAS, lequel interroge vos autres serveurs CAS pour récupérer le ticket ?
Cordialement,
YN
