### ISSUE TITLE
[3.4.3a] Bug SSO / page de login

### ISSUE THREAD

**Issue by skid9000** [JeromeDevome/GRR#185]
Bonjour,

Quand on active l'option "Rediriger un utilisateur non authentifié CAS vers la page d'accueil de GRR." dans les paramètres SSO, celà fait bien l'effet escompté, sauf que si on clique depuis la page de login sur "S'authentifier auprès du Service Central d'Authentification (CAS SSO)" , celà redirige à chaque fois sur la page de login de GRR au lieu du SSO.

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre message.
Effectivement, cela se produit lorsque l'authentification est obligatoire pour accéder aux plannings. Dans le cas où l'authentification n'est pas obligatoire, on passe de la page de login au planning par défaut d'où il est possible de s'authentifier en cliquant sur "Authentification".
Je cherche un correctif.
Cordialement,
YN

**Comment by ynaessens** [comment]
Pouvez-vous confirmer que ce correctif https://github.com/JeromeDevome/GRR/commit/3b607e8662096664fdea4daa23000a54cbf4303c résout votre problème de redirection ?

**Comment by skid9000** [comment]
Bonjour,

Le correctif fonctionne, merci :)
