### ISSUE TITLE
Mise à jour de l'heure d'une réservation non prise en compte

### ISSUE THREAD

**Issue by seb-vial** [JeromeDevome/GRR#19]
Bonjour,

Lorsque l'on modifie une réservation, si on change l'heure (testé de change l'heure de fin, pas de début), elle n'est pas prise en compte lors de la sauvegarde, l'ancienne heure est toujours affichée.
J'ai voulu testé de changer le jour pour voir si ça fonctionnait, le changement de jour fonctionne.

J'ai tenté de chercher dans le fichier `edit_entry_handler.php` à quel endroit se faisait la mise à jour, j'ai pu remarquer qu'il n'y avait pas d'**update**, juste un **insert** et donc derrière un **delete** pour supprimer l'ancienne réservation... (je ne suis pas sûr que cela soit la bonne méthode à utiliser mais bon).

Donc voilà, à voir comment corriger ce petit problème de changement d'heure pour une réservation.

**Comment by Birssan** [comment]
Petit up...

**Comment by nicolas-san** [comment]
Salut ! c'est pas passé à la trappe :) on est juste en retard sur tout ^^

**Comment by Birssan** [comment]
:+1:
