### ISSUE TITLE
Choix heures réservation calées sur les 1/2h : comment changer ?

### ISSUE THREAD

**Issue by nderambure** [JeromeDevome/GRR#195]
Hello,

J'ai beau avoir fouillé la doc et l'admin du site, je ne trouve pas comment faire en sorte de pouvoir réserver des ressources, salles...etc à 5mn de granularité. Sur la v3.4.3b, seules les heures et les 1/2h sont dispos pour l'interval de temps.
Du coup notre système de résa est à l'arrêt -_-'

Merci !

**Comment by ynaessens** [comment]
Bonjour,
le réglage se fait dans la page d'administration des domaines (plus petit bloc réservable et durée par défaut d'une réservation).
Dans la page d'édition des ressources, on choisit de réserver par date/heure de début et date/heure de fin ou durée.
J'ai testé ma 3.4.3 et j'ai bien la possibilité de commencer un créneau toutes les cinq minutes, et les réservations de font par multiple de cinq minutes...
Cordialement,
YN

**Comment by nderambure** [comment]
Hello @ynaessens et merci pour votre réponse, j'ai bien vu ce champs, mais mes yeux cherchaient "30" et pas 1800.... désolé...
