### ISSUE TITLE
Ajouter Captcha au contactFormulaire.php

### ISSUE THREAD

**Issue by SiRiLiS** [JeromeDevome/GRR#200]
Bonjour,
une idee pour ameliorer la securité du contactFormulaire.php: ajouter un captcha (ou similaire).
Vos avis?

A+

Fabio

**Comment by ynaessens** [comment]
Bonjour,
c'est une bonne idée.
Travail en cours.
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
j'ai ajouté un captcha au formulaire de réservation en ligne. C'est une fonctionnalité incluse dans la release 3.5.0a.
Cordialement,
YN
