### ISSUE TITLE
Integration auth SAML 2.0 pour integration edugain

### ISSUE THREAD

**Issue by SiRiLiS** [JeromeDevome/GRR#201]
Bonjour,
j'ai vu que la biblioteque LASSO est tres ancienne. Est-ce que il y aura la possibilité d'integration du systeme SAML2.0 pour permettre une authentification Edugain sur GRR?

Merci beaucoup

Fabio

**Comment by ynaessens** [comment]
Bonjour,
cela fait partie des travaux à réaliser dans le cadre de la modularisation de l'authentification.
Si vous êtes compétent sur la question, vous êtes bienvenu pour apporter votre contribution.
Cordialement,
YN

**Comment by JeromeDevome** [comment]
Bonjour, 
Dans la version 4 la bibliothèque est mise à jour, je vous laisse tester.
