### ISSUE TITLE
Probléme liée a l'impression des planning

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#203]
Bonjour,
J'ai passé la mise à jours GRR 3.5.0.
Quand j'imprime un planning de la semaine avec toutes les ressources, le planning s'affiche bien mais quand je veux imprimer le planning de la semaine que d'une salle, cela m'affiche qu'une colonne avec les heures mais pas les reservation.
![Capture](https://user-images.githubusercontent.com/50909713/188465811-36ef6603-9fb9-45ba-a6fa-cd834be29009.PNG)

Any Help ?

**Comment by ynaessens** [comment]
Bonjour, 
merci pour le signalement.
Effectivement il manquait un paramètre pour calculer la page en mode prévisualisation.
Désolé pour le dérangement.
Un correctif dans ce commit : https://github.com/JeromeDevome/GRR/commit/c8338f8632bc66665310d708dda8581c35b4834e
Cordialement,
YN

**Comment by SteBoun** [comment]
Cela a réglé ma panne 
Merci Beaucoup
