### ISSUE TITLE
3.4.3 IMAP authentification

### ISSUE THREAD

**Issue by gdesor** [JeromeDevome/GRR#204]
GRR 3.4.3, l'authentification IMAP est non fonctionnel.

Dans include/session.inc.php
remplacer la ligne 
`(Settings::get("imap_statut") != '' and (@function_exists("imap_open")) and Settings::get("imap_adresse") != '' and Settings::get("imap_port") != ''){`
par 
`(Settings::get("imap_statut") != '' and (@function_exists("imap_open")) ){`

Dans admin/admin_config_imap.php
Les variables imap sont définies dans le tableau $imap, puis utilisé avec les variables $imap_key.
Remplacer  :
```
foreach ($imap as $key => $value){
    $imap[$key] = clean_input($value);
}
```
Par : 
```
foreach ($imap as $key => $value){
    $imap[$key] = clean_input($value);
    eval('$imap_'.$key.'=$imap[$key];');
}
```

**Comment by ynaessens** [comment]
Bonjour,
je vous fais confiance pour la solution, reprise dans le commit https://github.com/JeromeDevome/GRR/commit/83822a23cab3b762d20c06b947b29c8072efff15
Merci pour l'analyse et la solution proposée.
Cordialement,
YN
