### ISSUE TITLE
Augmenter le nombre de caratères du champ "login" dans la table "grr_utilisateurs"

### ISSUE THREAD

**Issue by Aurely9n** [JeromeDevome/GRR#205]
Bonjour,

Le nombre de caractères du champ "login" dans la table "grr_utilisateur" est actuellement de 40 maximum. Est-il possible de l'augmenter (sans changer la nature de ce champ) sans causer des effets de bords indésirables. Le passer à 255 par exemple (max du champ VARCHAR).

- exemple dans  {GRR}//installation/tables.my.sql :
```
DROP TABLE IF EXISTS grr_utilisateurs;
CREATE TABLE grr_utilisateurs (login varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL default '', 
```
Nos utilisateurs s'authentifient via un système SSO  et certains ont leur login plus long que 40 caractères. La restriction actuelle ne leur permet pas de s’identifier sur la plateforme via la méthode utilisée.

Cordialement,
Aurelien

**Comment by ynaessens** [comment]
Bonjour, 
maintenant que la base est codée en utf8mb4, il ne faut pas dépasser varchar(192).
Pour ce qui est d'effets de bord indésirables, le mieux est d'essayer ;-)
Et rendre compte de votre expérience. 
D'avance merci pour la communauté. 
Cordialement, 
YN

**Comment by Aurely9n** [comment]
Bonjour,

Merci de votre patience, je n'ai pas eu le temps de tester les changement qu'il faudrait faire pour que ça fonctionne mais je pense y être arrivé !
En fait, il faudrait augmenter le nombre de caractères à 190 (comme ça on ne dépasse pas la limite UTF8mb4) dans toutes les tables qui contiennent le champ "login" ainsi que les champs "created_by" et "beneficiaire". EN faisant cette manipulation dans bdd, je peux me connecter avec des comptes dont les login sont supérieur à 40 et... c'est bien!
Vous trouverez en pièce jointe, le fichier tables.my.txt (obligé de changer l'extension pour github) qui permet d'installer les tables avec le nouvelles valeurs

Peut-être pourriez vous incorporer ces changements après les avoir validés dans une prochaine version de GRR ?

Bien à vous,
Aurélien

[tables.my.txt](https://github.com/JeromeDevome/GRR/files/9774879/tables.my.txt)

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre travail. 
J'ai intégré les modifications sur la branche de développement https://github.com/JeromeDevome/GRR/commit/76546e41f4981996e0fb7c0407a3720c5870a4a2
S'agissant d'une modification de la BDD, ce sera intégré dans la branche officielle 3.5.1, mais les fichiers correspondant à ce commit ne devraient pas poser de problèmes en installation native.
Je modifie la mise à jour en conséquence.
Cordialement,
YN

**Comment by ynaessens** [comment]
Après la mise à jour et la correction de l'initialisation, il est préférable d'utiliser les fichiers de ce commit https://github.com/JeromeDevome/GRR/commit/ce257af6b166ee9c630d11582267b66bdf895f50
Cordialement,
YN

**Comment by Aurely9n** [comment]
Bonjour,
Merci beaucoup pour la correction et l'intégration !
Très cordialement
Aurelien
