### ISSUE TITLE
Passage 1.9.7 à 3.4x

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#206]
Bonjour,
j'ai installé des GRR sur un serveur MAC avec MAMP , il y a plus de 20 ans 
GRR 1.9.7x

et depuis septembre , 3 fois, tous les GRR se sont mis à afficher la page d'installation 
mise à jour de la base de donnée
ou
installation

j'ai pu me débrouiller avec des sauvegardes du dossier " db " dans MAMP
J'ai remplacé le " db " par celui de la sauvegarde et ça fonctionne
mais ça c'est reproduit 3 fois, en tout
j'ai donc créer un serveur chez gandi

j'ai débuté les installations et les migrations des bases

deux GRR sont bien passés de 1.9.7 à 3.4x

mais d'autres ont un problème d'affichage de la page après connexion en administrateur
alors que la migration c'est bien passée

je n'ai pas les boutons 
pour les domaines et les ressources
ça s'affiche sous forme de liens et la age est déformée .
ça doit venir des bases car le même GRR , si j'installe la base avec lui, tout va bien mais je perd tout
la question , pourquoi ça ne le fait pas pour tous ???

 

![grr](https://user-images.githubusercontent.com/39954233/191847141-5ba0768f-e24d-4bf8-a551-cf875ac09f7d.jpg)

**Comment by ynaessens** [comment]
Bonjour,
je ne vois rien de déformé dans la page affichée. Si vous voulez des listes déroulantes ou des boutons, cela se règle dans la page d’administration des affichages.
Pour ce que vous rapportez, si je comprends bien, la mise à jour de la base a un comportement instable ?
Cordialement 
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
justement, c'est coché dans l'admin " en boutons " et ce n'est pas pris en compte
c'est ça le problème , j'utilisé la même image GRR 3.4 pour  4 GRR
Le site : www.monsite.fr/oufer/ est bon
et le site : www.monsite.fr/grrmed/ ne donne pas l'affichage en boutons même coché
je me demande s'il n'y a pas un lien avec la base de données car si je cré la base de donnée avec le site grrmed , j'ai les boutons.
j'ai testé , j'ai créer une base vide , j'avais bien l'affichage en boutons
j'ai vidé la base grrmed 
j'ai importé la sauvegarde du serveur utilisé actuellement 
( grr 1.9.7 )
le site GRR 3.4 a bien fait la mise à jour car tout était OK après.
je me suis connecté en administrateur et là plus de boutons
je suis allé dans le réglage général pour cocher en boutons ! , c'était déjà validé
et donc je ne comprends pas .
de toute façon, ça vient de la base mais ou se trouve la partie présentation, couleur.   
avec une base vierge , tout va bien .

**Comment by JeromeDevome** [comment]
Bonjour,
Regarder dans les paramètres de votre compte ? Le paramètre dans le compte
et prioritaire à celui de l'administration. L'administration permet juste
de définir le comportement par défaut pour les nouveaux utilisateurs.

**Comment by lachainestoplinky** [comment]
SUPER , 
c'était ça ..
mais comme le site " grrmed " 
le site " oufer " c'était GRR 1.9.7 et même version (e)
je vous remercie beaucoup  pour votre aide
pour info , oufer c'est le grr d'ouverture et de fermeture des salles
et grrmed , c'est celui de la médiathèque du centre universitaire à Montauban

j'utilise un MAC depuis près de 23 ans avec tous ces GRR
Le MAC n'est plus une tour mais un Imac depuis 7 ans
on l'utilise aussi pour afficher les salles de cours sur un écran.
ce qui est bien car la légende est dessous avec GRR 1.9.7
Mais plus en 3.4 , je crois.
j'ai trouvé la raison du problème entre les sites
sur le site oufer, j'ai les drots administrateur et que moi , je n'ai rien changé 
donc au moment de la mise à jour , c'est par défaut .
et les autre sites dont grrmed, il n'y a que le compte administrateur et la collègue à dût modifier ses réglages
 et se retrouvent par défauts après la mise à à jour 
Félicitation à toutes et tous 

Cordialement
Jérôme
![Capture d’écran 2022-09-24 à 10 59 36](https://user-images.githubusercontent.com/39954233/192089636-de15c263-443e-4eec-9320-7866187e76ea.png)

**Comment by lachainestoplinky** [comment]
Bonjour,
j'ai activé l'affichage de la légende ( type de réservations ) mais je n'en trouve que 2 ?
 
![Capture d’écran 2022-09-24 à 15 03 24](https://user-images.githubusercontent.com/39954233/192099609-730c91d6-1d31-4f31-a58a-c32795407afd.png)
![Capture d’écran 2022-09-24 à 15 00 52](https://user-images.githubusercontent.com/39954233/192099621-86e07904-0a7f-4136-95cb-c92779367f09.png)
