### ISSUE TITLE
Grr salles de cours - problèmes

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#207]
Bonjour,
tous les sites GRR sont passés de 1.9.7 vers 3.4 sans problèmes
sauf celui des réservations des salles de cours qui était déjà en 3.4.0c 
peut-être pas de vous !

quand je vais en simple visiteur , j'ai ce message alors qu'il est à jour.
![Capture d’écran 2022-09-25 à 15 30 41](https://user-images.githubusercontent.com/39954233/192147144-abb97640-4bdc-4732-8fc3-bfeb29f75f5c.png)
je clique sur mettre à jour la base
![Capture d’écran 2022-09-25 à 15 32 42](https://user-images.githubusercontent.com/39954233/192147224-64165736-ed54-4c6d-aa20-d64c2942a392.png)
et il n'y a pas de mise à jour
je clique sur accueil
et je tombe sur la page de connexion alors que le site est visible pour tous
 
![Capture d’écran 2022-09-25 à 15 34 37](https://user-images.githubusercontent.com/39954233/192147342-c980c118-72e7-445f-8432-f5c540c81bc9.png)
et une fois connecté, je tombe sur la page d'administrateur 
![Capture d’écran 2022-09-25 à 15 36 26](https://user-images.githubusercontent.com/39954233/192147386-971d4f7c-f880-4b1a-bbfb-4883895188a7.png)
et si je me déconnecte, j'ai bien la première page comme un visiteur
![Capture d’écran 2022-09-25 à 16 03 55](https://user-images.githubusercontent.com/39954233/192147764-9dbc8fe1-7d0c-4463-8772-3eeabe178e9e.png)
C'est super car tous les autres sont passés 7
Cordialement

**Comment by ynaessens** [comment]
Bonjour 
Je ne vois pas bien quel est votre problème.
Vous devriez passer en 3.4.3 ou 3.5.0. Ne pas tenir compte de la proposition de mise à jour vers la 3.4.0, c’est le serveur devome qui n’est pas à jour.
Cordialement 
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
merci , c'est ce que je vais faire , j'avais testé la version 3.5 mais il n'a pas pu faire la mise à jour vers 3.5
il c'est arrêté à 3.4.3 ou je sais plus
les conversions en utf8 étaient OK
ce qui était bien au final .
j'avais peur d'avoir des bug du coup.
merci
les autres GRR en 3.4 seront actif demain.
ça va râler ... ! 
Cordialement

**Comment by lachainestoplinky** [comment]
Bonjour,
j'ai le même problème après mise à jour vers 3.4.3b
j'ai fait un test tut con:
j'ai ajouté week_all.php après le nom du site
site.fr/grr/wek_all.php
et là, j'ai u la page du grr pour les simple visiteurs
ça doit venir de quelque chose dans la base

cordialement

**Comment by ynaessens** [comment]
Bonjour,
j'ai quelques difficultés à comprendre où est le problème.
Pour le réglage de la page de démarrage, cela se fait en deux temps dans les pages d'administration : 
- Accès et droits, pour autoriser l'accès aux plannings sans se connecter, ou l'interdire ;
- Général > Affichages, pour choisir l'affichage par défaut, sachant que chacun peut modifier le choix de sa page de démarrage.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
bonjour,
oui, je sais, le hic , c'est que le planning indique qu'il n'est pas installé alors que c'est faux.
si j'importe une autre base , d'un autre GRR tout va bien et avec celle des salles de cours, il semble que la mise à jour de 1.9.t à 3.4.0 ou 3.4.3b , GRRaffiche que ce n'est pas installé mais si j'entre l'adresse du site www.lesite.fr/grr/login.php ou week_all.php , j'ai bien la page login ou la page public
un problème avec cette base , je pense .
le GRR n'arrive pas à lire la configuration .

**Comment by ynaessens** [comment]
Ah, là je vois mieux le souci.
Je vous suggère de faire une mise à jour forcée de la base fautive.

**Comment by lachainestoplinky** [comment]
Bonjour,je vous remercie je suis au boulot, je vais voir ça.Cordialementenvoyé : 29 septembre 2022 à 12:18de : ynaessens ***@***.***>à : JeromeDevome/GRR ***@***.***>cc : jEROME ***@***.***>, Author ***@***.***>objet : Re: [JeromeDevome/GRR] Grr salles de cours - problèmes (Issue #207) Ah, là je vois mieux le souci. Je vous suggère de faire une mise à jour forcée de la base fautive.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
