### ISSUE TITLE
/!\ Sécurité: stockage des mots de passe non sécurisé

### ISSUE THREAD

**Issue by Altair31** [JeromeDevome/GRR#208]
Bonjour @JeromeDevome,
Le stockage des mots de passe est simplement chiffré avec md5.
Cette méthode de chiffrement est connue depuis quelques années pour ne plus être robuste.
De très nombreuses tables permettent de retrouver un mot de passe à partir de son MD5.
Il faudrait changer le stockage des mots de passe afin d'utiliser un algorithme de chiffrage plus robuste ainsi qu'un salage afin de correspondre à l'état de l'art en terme de sécurité des mots de passe.
Version auditée: GRR-3.5.0

**Comment by JeromeDevome** [comment]
Bonjour,
La version 4.0 corrigé ce problème

**Comment by Altair31** [comment]
Ok, vous laissez donc la version de production avec une grosse faille béante tout en déconseillant d'utiliser la 4.0 car en béta.
Pourquoi ne pas appliquer également le patch sur la version 3.5?
On est pas sur du cosmétique ou de la nouvelle fonctionnalité là, c'est un vrai problème de sécurité.

**Comment by JeromeDevome** [comment]
Nous allons déployer la version en release au mois d'octobre.

Ce n'ai pas une faille, il faut déjà que l'on accède à la bdd.

**Comment by ynaessens** [comment]
Bonjour @Altair31 
C'est dans la to-do list pour la branche 3 aussi. Comme le dit Jérôme, la protection du serveur de BDD est cruciale.
Merci quand même pour cette piqure de rappel ;-)
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
je viens de faire passer des sites GRR 1.9.7 à 3.4 , pour 2 sites je ne naissais pas le mode passe administrateur.
je suis aller sur la base GRR ou je suis admin, j'ai copié la chaine mot de passe
et je l'ai collée dans l'autre et je suis devenu administrateur.
j'ai pu finir la mise à jour 
et j'ai recollé le mot de passe à nouveau, de ce fait, les collègues pouvaient aller sur le nouveau GRR sans me donner le mot de passe .

bien sur, il faut pouvoir aller sur le serveur bdd

**Comment by ynaessens** [comment]
Bonjour,
pour la modification du cryptage des mots de passe sur la famille GRR3, j'ai utilisé password_hash...
https://github.com/JeromeDevome/GRR/commit/636b65fb1f1363ca1202d73e5732549a0d199edb
le résultat devrait être utilisable bien que ce soit en apparence une branche de développement. Si vous pouviez tester et confirmer mes premières analyses, ce sera intégré dans la prochaine version 3.5.1.
Cordialement,
YN

**Comment by Altair31** [comment]
Le problème est toujours présent en 4.0.0

**Comment by ynaessens** [comment]
Bonjour,
pouvez-vous préciser vos attentes ?
Le cryptage mis en place dans la v3.5.1 vous satisfait-il ?
Merci pour votre participation, 
cordialement,
YN

**Comment by Altair31** [comment]
Le plus simple serait d'utiliser les fonctions [password_hash](https://www.php.net/manual/en/function.password-hash.php), et [password_verify](https://www.php.net/manual/en/function.password-verify.php).
Pour ajouter un peu plus de sécurité, je vous renvoie vers [ce commentaire de la doc de password_hash](https://www.php.net/manual/en/function.password-hash.php#124138).
J'ai personnellement pas testé la 3.5.1 mais directement la 4.0.0 (fresh install).
Qu'avez-vous mis en place sur la 3.5.1 ?

**Comment by ynaessens** [comment]
Je partage votre point de vue, c'est effectivement password_hash et password_verifiy que j'utilise dans la v3.5.1.
Si vous pouviez contribuer à confirmer que les modifications mises en place sont bien fonctionnelles, notamment si vous utilisez SSO ou une autre identification externe, cela me permettrait de publier la 3.5.1 comme stable.
Merci pour vos remarques.
Cordialement,
YN

**Comment by JeromeDevome** [comment]
J'ai fais un [commit](https://github.com/JeromeDevome/GRR/commit/b455f7ae0188aac9cb8e5d8debeaaafa2db758f)
En effet la fonction password_hash est plus simple et semble plus sécurisé que ma méthode bien tordue.

**Comment by JeromeDevome** [comment]
Disponible avec la version 4.0.1

**Comment by ynaessens** [comment]
Bonne nouvelle !
Ainsi la compatibilité ascendante depuis la v3.5.1 sera assurée :-)

**Comment by Altair31** [comment]
Bonjour,
Je viens de tester la 4.0.1 et il semblerait qu'il y ait un oubli.
Lors de l'installation, le mot de passe est toujours stocké en MD5 rendant la connexion impossible depuis une fresh install.

**Comment by JeromeDevome** [comment]
Bonjour, cela est changé en 4.0.2. De plus à la première connexion celui est convertit.
