### ISSUE TITLE
Connection HS suite maj vers Ubuntu 22.04

### ISSUE THREAD

**Issue by micter59** [JeromeDevome/GRR#209]
Bonjour,

J'ai fait la mise à jour du serveur hébergeant l'application GRR (3.4.3)
Je suis passé de Ubuntu 20.04 à Ubuntu 22.04.
PHP est passé de la 7.4 à la 8.1.

Les pages de l'application s'affichent bien, mais je ne peux plus me connecter.
J'ai une page blanche simplement. Et ensuite, je dois supprimer le cookie d'authentification pour avoir accès à nouveau aux pages (mais pas connecté donc).
Dans le log d'Apache, j'ai la ligne suivante 
"PHP Fatal Error: Uncaught mysqli_sql_exception: Table 'grr.grr_j_groupe_se3' doesn't exist in /var/www/grr/include/mysql.inc.php:81"
La stack trace remonte ensuite à :
include/session.inc.php(762) grr_sql_query()
login.php(44) : grr_opensession()

J'ai vérifié que le module LDAP est bien installé.

Merci d'avance pour votre aide.
N'hésitez pas s'il y a d'autres infos que je peux apporter.

Michaël

**Comment by micter59** [comment]
Je viens de vérifier, la table grr_j_groupe_se3 n'existe pas dans la DB.
Mais en même temps, elle n'existait pas avant non plus...

**Comment by micter59** [comment]
Autre précision, j'ai un GLPI 10.0.3 qui tourne sur le même serveur, et aucun problème. On s'y connecte aussi avec un compte LDAP.

**Comment by anteldan** [comment]
Bonjour,
Dans votre configuration LDAP dans GRR, pour l'adresse du serveur LDAP est-ce que vous mettez renseignez bien le scheme ? c-à-d "ldap://" ou "ldaps://" en préfixe du nom du serveur ?

**Comment by micter59** [comment]
Oui, dans le fichier  j'ai bien $ldap_adresse='ldap://adresseDuLDAP' et ce dernier est bien joignable.

**Comment by micter59** [comment]
J'ai l'impression que PHP 8.1 a changé sa manière de gérer la partie LDAP :
https://kinsta.com/blog/php-8-1/#ldap-resources-migrated-to-objects
Peut-être que ça vient de là ?

**Comment by ynaessens** [comment]
Bonjour,
avec php8.1, il est nécessaire d’installer Grr 3.5.0 et même récupérer les derniers correctifs sur la branche 3.5.0.
L’erreur que vous signalez a été corrigée.
Cordialement 
YN

**Comment by micter59** [comment]
Je viens de faire la mise à jour, problème réglé. Un grand merci !
