### ISSUE TITLE
problème authentification en locale

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#212]
Bonjour,
j'ai installé GRR 3.4 sur un serveur de l'hébergeur GANDI
il y a une personne qui n'arrive pas à s'identifier de chez elle ( free ) ADSL
ou de son smartphone ( SOCH ), elle n'a pas de message d'erreur, la page de connexion revient .
du smartphone de son mari , ça fonctionne ( orange )
et ses identifiants testés sur le réseau de l'université et du département, de chez moi ( orange ) ça fonctionne.
même la connexion en administrateur ne fonctionne pas chez elle .
chez une amie , j'ai testé la connexion administrateur et mes identifiants pour le même GRR , ça fonctionne . ( ADSL orange )

c'est étrange , les identifiants de la collègue de boulot qui ne fonctionnent pas sur free ADSL et Soch sur son smartphone.

ça peut venir d'une version de GRR ou c'est de sa configuration ?

**Comment by ynaessens** [comment]
Bonjour,
avez-vous pensé à vérifier que cette personne n'a pas inactivé les cookies ou le javascript ?
Sinon, je sèche.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
je vais voir avec elle lundi .
en effet, car une autre collègue arrive à se connecter sur son smartphone et ses identifiants 
la collègue qui n'y arrive pas est la seule . 
et comme j'ai dit , partout ou j'ai testé ses identifiants .. tout est bon
c'est elle , le problème !

au conseil départemental, c'est SFR ou ORANGE ( fibre )
l'université , c'est ORANGE ( réseau Rénather ) 
sans rire, je vais tester celui de l’hôpital de Montauban car le premier GRR n'était pas vu 
il était hébergé sur un IMAC avec une IP externe bloquée

**Comment by lachainestoplinky** [comment]
bonjour, la collègue est revenue de congés.
j'avais installé une autre version de GRR : " GRR 3.4.3b " pour tester une base de données.
avec cette version , elle peut se connecter en administrateur avec son smartphone .
mais elle ne peut pas s'identifier sur un GRR 3.4.0 avec son smartphone .

il y a une différence entre les fichiers " login.php " ou pas ?

avec la version 34.3b , je dois indiquer le chemin complet 
www.monsite.fr/grr/login.php
sije m'arrête à monsite.fr/ 
le site indique que la base n'est pas installée.
- > il faut obligatoirement s'identifier pour voir le site 
dans la version 3.4.0 , je n'ai pas ce problème mais les problèmes pour se connecter.

quelle version est fonctionnelle après 3.4.0 ?

PHP 7.4.21
SQL 5.7

**Comment by ynaessens** [comment]
Bonjour,
avec php 7.4, les versions 3.4.3 et 3.5.0 sont fonctionnelles. Ce n’est pas assuré pour les versions <= 3.4.2.
Si vous avez une page d’installation au lieu de la page par défaut, c’est soit votre base qui comporte une erreur, soit un problème de compatibilité avec MySQL 5.7. Si vous pouvez activer les outils de développement web de votre navigateur, vous aurez peut-être des renseignements sur ce qui pose problème.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
une dernière chose, 
est-il possible de rétrograder de 3.4 vers 3.3 ?

**Comment by lachainestoplinky** [comment]
bonjour,
j'ai créer deux GRR de test , à voir avec la collègue demain .
à la fin de la mise à jour, j'ai  ce message:

Mise à jour jusqu'à la version 3.4.1 :
Ok !
Mise à jour jusqu'à la version 3.4.2 :
Ok !
Mise à jour jusqu'à la version 3.4.3 :
Erreur sur la requête : ALTER TABLE `grr_log` CHANGE `REMOTE_ADDR` `REMOTE_ADDR` VARCHAR(40) NOT NULL DEFAULT '' (1067 : Invalid default value for 'START')

je dois vider la table avant de faire la mise à jour ?

**Comment by ynaessens** [comment]
Bonjour,
si vous faites une installation depuis zéro, vous ne devriez pas avoir de problèmes de connexion demandant une mise à jour.
Si vous restaurez d'anciennes données, vous serez amené à mettre à jour. Le problème vient de la valeur par défaut sur les champs date ; une valeur nulle n'est plus acceptée par MySQL. 
J'ai fait les modifications nécessaires sur GRR3.5.0. Si vous pouvez l'installer, vous devriez être tranquille. Sinon je ferai un correctif sur GRR3.4.3.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Bonjour,la collègue est revenue , tout est activé ( cookies et javascrypt )j'ai une seconde collègue dans le même cas.impossible de s'identifier de chez elle .la première c'est l'opérateur FREE pour l'ordinateur portable et SOCH pour le smartphonela seconde , c'est RED SFR pour son ordinateur.Sur le premier serveur :SQL = 5.5.42PHP = 5.3.29si je vais plus haut , GRR 1.9.7 ne fonctionne pas donc plus de GRR pour les salles de cours.avec ce serveur , tout vieux , et pas à jour , ça fonctionne partout.de 3.4 est-il possible de revenir à une version à 3.3  avec GRR ?au boulot, un GRR en 3.3 est utilisé par le service qui fait le prêt de véhiculesmais c'est en local , pas sur internet.envoyé : 12 octobre 2022 à 18:23de : ynaessens ***@***.***>à : JeromeDevome/GRR ***@***.***>cc : jEROME ***@***.***>, Author ***@***.***>objet : Re: [JeromeDevome/GRR] problème authentification en locale (Issue #212) Bonjour, si vous faites une installation depuis zéro, vous ne devriez pas avoir de problèmes de connexion demandant une mise à jour. Si vous restaurez d'anciennes données, vous serez amené à mettre à jour. Le problème vient de la valeur par défaut sur les champs date ; une valeur nulle n'est plus acceptée par MySQL. J'ai fait les modifications nécessaires sur GRR3.5.0. Si vous pouvez l'installer, vous devriez être tranquille. Sinon je ferai un correctif sur GRR3.4.3. Cordialement, YN—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
OK, je vais tester, avec la version , 3.5 ; c'est con pour 2 GRR !! sur 7un collègue devait tester sa connexion, de chez lui  avec FREEet oui , je vais créer un GRR propre avec une base créer par lui et voir si les connexions fonctionnent partout à bientôt envoyé : 12 octobre 2022 à 18:23de : ynaessens ***@***.***>à : JeromeDevome/GRR ***@***.***>cc : jEROME ***@***.***>, Author ***@***.***>objet : Re: [JeromeDevome/GRR] problème authentification en locale (Issue #212) Bonjour, si vous faites une installation depuis zéro, vous ne devriez pas avoir de problèmes de connexion demandant une mise à jour. Si vous restaurez d'anciennes données, vous serez amené à mettre à jour. Le problème vient de la valeur par défaut sur les champs date ; une valeur nulle n'est plus acceptée par MySQL. J'ai fait les modifications nécessaires sur GRR3.5.0. Si vous pouvez l'installer, vous devriez être tranquille. Sinon je ferai un correctif sur GRR3.4.3. Cordialement, YN—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
Si ça peut aider :les deux GRR qui posent problèmes pour la connexion chez free et soch étaient sous GRRR 1.9.7.e ( au départ ) -> GRR 3.4.0 ( début du blocage ) une copie des GRR en version  3.4.3b ( même problème )Le GRR 1.9.c ou d ( au départ ) -> GRR 3.4.0 -> GRR 3.4.3b ( pas de problèmes )l'export de la base toujours à partir GRRet l'import  dans la base avec PHPMYADMINUTF8 car latin1 n'existe pas dans le choix et le iso est refusé par le serveurenvoyé : 12 octobre 2022 à 18:23de : ynaessens ***@***.***>à : JeromeDevome/GRR ***@***.***>cc : jEROME ***@***.***>, Author ***@***.***>objet : Re: [JeromeDevome/GRR] problème authentification en locale (Issue #212) Bonjour, si vous faites une installation depuis zéro, vous ne devriez pas avoir de problèmes de connexion demandant une mise à jour. Si vous restaurez d'anciennes données, vous serez amené à mettre à jour. Le problème vient de la valeur par défaut sur les champs date ; une valeur nulle n'est plus acceptée par MySQL. J'ai fait les modifications nécessaires sur GRR3.5.0. Si vous pouvez l'installer, vous devriez être tranquille. Sinon je ferai un correctif sur GRR3.4.3. Cordialement, YN—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
bonjour,
oui, c'est ce que nous avons décidés ! , j'ai utilisé les deux copies en 3.4.3b ; j'ai vidé les deux bases et tout recréer 
comme cette version crée un domaine et une ressource, on a testé son problème de connexion sur son smartphone et c'est bon, ça fonctionne , je ne sais pas à partir de son pc sur free.
merci beaucoup de votre aide .
