### ISSUE TITLE
erreur CSV réservations

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#213]
Bonjour,
j'utilise la version 3.4.3b
j'ai testé l'import d'une réservation un respectant à la lettre le format csv 
je passe la première étape , les informations sont bien lues
j'ai bien le retour en vert et c'est prêt pour un envoi dans la base 
mais c'est là que ça bloque .
d'ailleurs, je me demande s'il ne maque pas le nom du domaine , avant ou après le nom de la ressource .
il y a 4 domaines et 10 ressources

**Comment by ynaessens** [comment]
Bonjour,
je viens de refaire un test et les données sont bien enregistrées.
Il y a juste un point à corriger : les réservations sans type sont validées lors de la lecture mais ne seront pas enregistrées.
Vos réservations ont-elles bien un type ?
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Oui , le Type A 
mais il faut bien donner le dondaine ? dans l'exemple donné sur le GRR , on n'en parle pas .
s'il y a 2 ressources avec le même nom mais dans domaines différent , ça se passe comment ?
je vais re faire un test

**Comment by lachainestoplinky** [comment]
Bonjour,
dans le fichier csv, il doit y avoir autre chose ?

dans le fichier , j'ai cette ligne
2022-12-12;12h00;14h00;Pavillon des Savoirs;Test;A

A= le type de réservation

après avoir cliqué sur " importer le fichier de réservation "
j'ai ce message:
1 lignes de données ont été lues en 0 secondes.
Array ( [0] => 0 (INSERT INTO grr_csv2 (`id`, `date`, `heure_deb`, `minute_deb`, `heure_fin`, `minute_fin`, `ressource`, `description`, `type`) VALUES ('DEFAULT' , '2022-12-12' , '12' , '0' , '14' , '0' , 'PAVILLON DES SAVOIRS' , 'Test' , 'A');) )

2022-12-12 12h0 - 14h0 => PAVILLON DES SAVOIRS : Test ; A
la ligne ci-dessus est en vert

il manque peut-être des infos dans le fichier csv
vous pourriez me faire parvenir un exemple complet qui fonctionne chez vous
et comparer

merci

**Comment by ynaessens** [comment]
Oui, le fait que le domaine ne soit pas précisé peut poser problème si deux ressources ont le même nom dans deux domaines différents. Ce format est "historique", ce qui ne signifie pas qu'il soit figé.
Les données que j'utilise sont de même format que les vôtres.
Pouvez-vous vérifier si la table grr_csv2 est bien créée ? Et son contenu conforme aux données lues ?
Pourriez-vous mettre vos scripts à jour avec ceux-ci : https://github.com/JeromeDevome/GRR/tree/GRR-3.4.3
Si cela résout votre problème, je taguerai une nouvelle sous-version.

**Comment by ynaessens** [comment]
Si vous avez accès par phpmyadmin, il serait intéressant de tenter la création manuelle par la commande SQL:
`"CREATE TABLE IF NOT EXISTS `grr_csv2` (`id` int(11) NOT NULL AUTO_INCREMENT,`date` DATE NOT NULL,`heure_deb` tinyint(4) NOT NULL,`minute_deb` tinyint(4) NOT NULL,`heure_fin` tinyint(4) NOT NULL,`minute_fin` tinyint(4) NOT NULL,`ressource` tinytext NOT NULL,`description` tinytext NOT NULL,`type` tinytext ,PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=latin1"`.
Si vous avez accès aux journaux, l'échec de création par le script admin_import_entries_csv_direct.php devrait laisser une trace.

**Comment by lachainestoplinky** [comment]
Bonjour,
je vous remercie car je fais de la formation SQL avec vous !
la table a été créée sans problème dans la base grr343b , nom de la version de grr
je vais voir pour le reste 
merci
pour les utilisateurs, c'est une autre table alors ( grrcsv1 un truc comme ça !

j'ai créer la table dans le grr qui est en erreur car il n'a pas pu faire la mise à jour comme il faut après l'import d'une base
je n'ai pas voulu créer la table dans la version qui va être utilisée et qui avait crée toutes les tables sauf les grr_csv
je prends le temps car je suis chez moi et la collègue au boulot

**Comment by ynaessens** [comment]
Les tables d'importation csv sont en principe créées à la volée lors de la première importation et non à l'initialisation.
Ce serait intéressant de comprendre pourquoi la création échoue dans votre cas.
La solution de secours consiste à créer les bases manuellement par phpmyadmin, elles peuvent rester en place sans inconvénient.

**Comment by lachainestoplinky** [comment]
bonjour,
ma collègue m'a dit que ce n'est pas grave pour les réservations et pour le GRR en question, ce n'est qu'une consultation pour les agents donc un compte visiteur va suffire .

elle souhaite savoir s'il y a une façon de faire apparaître le NOM d'un type de réservation dans le planning 
il est bien coché dans la rubrique d'affichage , sur toutes les cases mais il n'apparait pas.
coché ou pas , ça ne change rien .
version GRR 3.4.3b .
ce qui serais bien , c'est pouvoir définir la chose suivante pour faire ça 
faire apparaitre le NOM du TYPE de réservation dans la brève description.

pour nous, le type de réservation, par couleur
c'est aussi le PRENOM des personnes qui sont à la plonge , chargés des ouvertures, des fermetures et de la caisse du restaurant de l'Université .

donc les agents regardent leur prénom qui est aussi leur couleur.
pour le planning de la semaine.

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre retour. Il y avait une scorie d'ancien code.
C'est corrigé sur ce commit : https://github.com/JeromeDevome/GRR/commit/42eec18d89b44f2269034773882fccff82021a2d
Désolé pour le dérangement.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
pour effectuer le correctif,
je remplace les lignes ( en rouge )par celle qui sont en vert dans le fichier indiqué , c'est bien ça ?
et je renvoi le fichier sur le serveur 

cordialement

**Comment by ynaessens** [comment]
Bonjour,
oui, ou vous remplacez directement le fichier ancien par le nouveau.
Cordialement,
YN
