### ISSUE TITLE
1 seul pour une ressource

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#214]
Bonjour,
on utilise la version GRR 3.4.3b pour faire des pré demandes de congés, télétravail, maladie .. ( type de réservations )
nous avons remarqué que si on est usagés on peu écrire partout. ( toutes les ressources )

notre configuration : 
20 utilisateurs 
et 3 qui peuvent valider les réservations
on souhaite que , par exemple : 
l'utilisateur Jérôme ( usager )
puisse écrire , modifier ou effacer une réservation que sur la ressource Jérôme , le prénom qui s'affiche dans la brève description )
mais Jérôme ne doit rien pouvoir faire chez d'autres personnes
seuls les valideurs doivent pouvoir valider .. ( c'est parfait comme ça pour eux )
mais actuellement Jérôme peux écrire chez Sandra et les autres
si je dis que Jérôme est gestionnaire de la ressource Jérôme , dans ce cas Jérôme peut valider ses congés ( il ne doit pas pouvoir le faire )

**Comment by ynaessens** [comment]
Bonjour,
si je comprends bien votre utilisation de GRR, il faudrait que les personnes autorisées à valider soient gestionnaires des ressources ou du domaine et que les ressources soient modérées et restreintes.
Si vous restreignez l'accès à la ressource restreinte à une seule personne, elle ne pourra accéder qu'à la ressource qui lui a été attribuée, sans toutefois pouvoir valider du fait de la modération.
À tester...
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
oui, ça fonctionne , case cochée pour faire une ressource restreinte 
( Jérôme ) 
les droits donnés à Jérôme
et si je coche la case ( ressource restreinte à Sandra
et les droits que pour Sandra
Jérôme ne peux rien faire dans la ressource Sandra
nous n'avions pas coché la case 
et quand nous avions coché la case, nous n'avions pas donné de droits
du coup , il manquait une partie

Et Jérôme ne peux pas valider ses congés

merci
c'est parfait
