### ISSUE TITLE
Bug ressource restrainte

### ISSUE THREAD

**Issue by skid9000** [JeromeDevome/GRR#221]
Bonjour,

je ne sais pas si c'est moi qui m'y prend mal, mais je n'arrive pas à ajouter un utilisateur pour qu'il puisse accéder à une ressource restreinte sans droit de gestion.

Contexte :
GRR version 3.4.3

J'ai une ressource restreinte dans un domaine non restreint.
Quand je veux aller dans l'administration -> Utilisateurs et accès -> Accès à la réservation des ressources restreintes, je ne peux ajouter aucun utilisateur dans ma ressource, la liste est vide.

Par contre si j'ajoute cet utilisateur dans la section "Gestion des ressources", il apparaît bien ensuite dans la section "Accès à la réservation des ressources restreintes".

Je m'y prend mal ou c'est un bug ? (note : l'utilisateur que je test est en privilège "usager")

**Comment by ynaessens** [comment]
Bonjour,
je ne reproduis pas ce bug, la liste des utilisateurs contient bien tous ceux qui ne sont pas déjà autorisés à réserver.
Voici mon contexte : 
Numéro de version GRR fichier : 3.4.3b 
Numéro de version GRR BDD : 3.4.3

Version PHP : 7.4.27
Base de donnée : mysql 5.5.5-10.4.22-MariaDB
---
Time : 1671028757
Date du serveur (Jour-Mois-Annee) : 14-12-2022. Heure : 15:39
Timezone (date_default_timezone_set) : Europe/Paris

Cordialement,
YN

**Comment by skid9000** [comment]
Avez vous essayé avec des utilisateurs "externes" ? J'utilise CAS en SSO de mon côté.

**Comment by skid9000** [comment]
Ce qui m'étonne c'est que la requête sql utilisée ressort bien toute la liste des utilisateurs...

`SELECT login, nom, prenom FROM grr_utilisateurs WHERE (etat!='inactif' and (statut='utilisateur' or statut='visiteur' or statut='gestionnaire_utilisateur')) AND login NOT IN (SELECT DISTINCT login FROM grr_j_userbook_room WHERE id_room = '14') order by nom, prenom`

**Comment by skid9000** [comment]
Alors j'ai inversé le if en ligne 198 de `admin/admin_book_room.php` , ça affiche bien la liste maintenant mais par contre quand j'ajoute un utilisateur, ça lui donne pas les droits pour voir la ressource et réserver dessus...

```php
if (!verif_acces_ressource($row[0],$id_room))
```

**Comment by ynaessens** [comment]
Il semble que vos utilisateurs n'ont pas accès à la ressource, hormis les gestionnaires de ressource et plus.
Dans les réglages de la ressources, avez-vous bien autorisé les utilisateurs à voir la ressource ? C'est l'item juste avant la case à cocher pour rendre la ressource restreinte.

**Comment by skid9000** [comment]
Ah oui effectivement j'avais oublié ce détail.

Par contre du coup il n'est pas possible de cacher la ressource sauf aux personnes autorisées à y reserver ?

**Comment by ynaessens** [comment]
Bonjour,
actuellement, non. La notion de ressource restreinte ne s'applique qu'au droit à réserver, la visibilité est gérée indépendamment.
Si vous voulez cacher des ressources aux utilisateurs non gestionnaires, il faut les inclure dans un domaine restreint.
Cordialement,
YN
