### ISSUE TITLE
Bug avec les créneaux

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#222]
Bonjour,
je constate un bug avec les créneaux 
version GRR : 3.4.3b

situation : 

3 créneaux dans cet ordre d'affichage
Journée
Matin
Après-midi
basé sur 
date de début
date de fin

si je fais une réservation le 9 Janvier 2023 - Journée

dans le formulaire , ça donne
début 9 Janvier 2023 - Journée
fin 9 Janvier 2023 - Journée
dans la réservation , il est indiqué - Journée

mais si je sélectionne un autre créneau 
ex : Matin 
dans le formulaire , ça donne
début 9 Janvier 2023 - Matin
fin 9 Janvier 2023 - Matin
dans la réservation , il est indiqué - Journée à Matin

c'est comme si les deux derniers étaient aussi sur la même tranche horaire 

Pour résumer ; 
dans le calendrier , si je clique sur le + du créneau Journée , il n'y a que cette case rempli , si je clique sur le + du créneau Matin , les créneaux Journée et Matin sont rempli et si je clique sur le + du créneau Après-midi les 3 créneaux rempli 

cordialement

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre signalement.
A priori le commit https://github.com/JeromeDevome/GRR/commit/d56ec5a6ed8b9a6eeef963105154d9596dd2b929 corrige ce bug.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
je vais voir ce que ça donne

merci

**Comment by ynaessens** [comment]
Bonjour,
pour la meilleure expérience, vous devriez tester les fichiers à ce commit https://github.com/JeromeDevome/GRR/commit/e297eb65b798d0df46b4d56de077195df96c070c
Merci de confirmer que les derniers correctifs sont efficaces.
Cordialement,
YN

**Comment by lachainestoplinky** [comment]
Bonjour,
non, ça ne change rien. 
pur la version 3.5.0a

Une réservation en mode créneaux

date de début : Matin
date de fin : Matin
Brève description : Nom de la ressource
type de réservation : Congé

dans les vue du planning , on voit : 
Nom de la ressource
Congé
mais pas le Nom du créneau choisi
dans la version 3.4.3b , c'est le cas

quand je clique sur le lien du pop-up du détail de la réservation : 

j'ai bien tout le détail mais il y a des erreurs
j'ai fais une réservation sur le créneau Matin
date de début : Journée
date de fin : Matin
et c'est indiqué 2 Créneaux
la réservation est bien placée dans la case du créneau Matin 

en fait , la date de début est considérée comme étant le créneau 1 ( Journée )
la date de fin est considérée comme étant le second créneau 1 ( Matin )
mais 1+1 = 2
ce qui donne 2 créneaux dans le pop-up

**Comment by ynaessens** [comment]
Avez-vous bien récupéré tous les fichiers modifiés depuis la version 3.5.0a ?
