### ISSUE TITLE
le texte - type de réservation ne s'affiche pas

### ISSUE THREAD

**Issue by lachainestoplinky** [JeromeDevome/GRR#225]
Bonjour,
dans la version 3.4.3b, même si je coche : 
type 
pour toutes les vues, le texte ne s'affiche pas.
couleur du fond verte , couleur du texte noire
j'ai testé avec la version 3.5 et là, j'ai bien le texte

il y a un bug ?

**Comment by ynaessens** [comment]
Bonjour,
je ne reproduis pas.
Cela se produit-il pour tous les types ?
Cordialement,
YN
P.S.: vous avez tout intérêt à utiliser la version 3.5, et même la 3.5.1 qui ne devrait pas tarder à sortir en stable.

**Comment by lachainestoplinky** [comment]
Bonjour, 

version 3.4.3bss
oui, le texte des types de réservations ne s'affichent pas pour tous  les types ( 12 )
le texte s'affiche bien dans la légende 
je vais voir avec la version 3.5 et notre base sql
car avec une installation complète ( fichiers et création de la base  ça fonctionne avec les types par défauts

**Comment by lachainestoplinky** [comment]
Bonjour,
j'ai installé la version 3.5.0a 
le texte ( type de réservation  s'affiche dans les vues du planning .
le problème est donc réglé pour ça.
Cordialement

**Comment by lachainestoplinky** [comment]
pour ce problème dans la version 3.4.3b
c'est comme si la couleur de fond et la couleur du texte étaient les mêmes
ex :  rouge sur rouge 
mais uniquement à l'affichage sur les vues.
