### ISSUE TITLE
Erreur lors du changement mot de passe.

### ISSUE THREAD

**Issue by saf-bredow** [JeromeDevome/GRR#227]
**Décrivez le bogue**
Impossible de changer son mot de passe pour un utilisateur, l'ancien mot de passe n'est pas reconnu.

**Infos GRR**
Version de GRR : 4.0.0b GitHub-Master
Version PHP : 7.4.33
Problème suite à une installation ou mise à jour : 
Depuis la dernière mise à jour, un utilisateur ne peut plus changer son mot de passe. Un message d'erreur

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans 'username - gérer mon compte'
2. Saisir ancien mot de passe (copié-collé de celui qui a permis de s'authentifier.), puis deux fois le nouveau mot de passe
3. Cliquer sur "enregistrer" 
4. Voir l'erreur : "L'ancien mot de passe n'est pas correct !"

**Comportement attendu**
Validation du nouveau mot de passe de l'utilisateur.

**Comment by JeromeDevome** [comment]
Bonjour, 
Cela ce produit uniquement sur certains utilisateurs ?
Pouvez vous contrôler en base si le mot de passe de l'utilisateur est stocké en md5 ou non ? (Pour cela comparé le champ avec un son mot de passe dans un générateur md5)

**Comment by JeromeDevome** [comment]
Je pense que le [commit ici](https://github.com/JeromeDevome/GRR/commit/b455f7ae0188aac9cb8e5d8debeaaafa2db758f) , résout le problème

**Comment by JeromeDevome** [comment]
Vous pouvez tester avec la version 4.0.1

**Comment by saf-bredow** [comment]
Mise à jour effectuée, le problème persiste. Testé avec plusieurs comptes.

**Comment by ynaessens** [comment]
Bonjour,
je viens de tester avec les fichiers à jour de ce commit : https://github.com/JeromeDevome/GRR/commit/f0d9d1bc97707ca54e21385607728b86b7eb59cd
et j'ai pu changer avec succès le mot de passe d'un utilisateur en tant qu'administrateur, et changer le mot de passe en tant qu'usager.
Pouvez-vous confirmer ?

**Comment by saf-bredow** [comment]
J'ai toujours le même message d'erreur après avoir remplacé le fichier AdminFonctions.php par celui du commit.

**Comment by ynaessens** [comment]
Je suggérais que vous chargiez l’ensemble des fichiers à jour de ce commit.
D’ailleurs je voudrais savoir quel est l’historique de votre base de données, qui mène à cette situation.

**Comment by JeromeDevome** [comment]
Je confirme qu'il y réside un problème.
https://github.com/JeromeDevome/GRR/commit/3ca922b31bc4f75cae728503269b8c24fdc7f6ae

Cela devrait corriger une release 4.0.2 va être livré je vous conseil de faire la mise à jour

**Comment by saf-bredow** [comment]
@JeromeDevome : Merci :) 

@ynaessens : Pour l'historique de la base de donnée : c'est une installation ancienne, au moins une dizaine d'années. Les mises à jour ont été faites régulièrement sauf en 2022 où il n'y a pas eu de suivi.

**Comment by ynaessens** [comment]
@saf-bredow : merci pour votre retour. 
Cela signifie qu'il faudra être vigilant dans le processus de mise à jour des versions 3 vers 4.
