### ISSUE TITLE
Mise à jour : champ login, create_by et beneficiaire en varchar(190) pour compatibilité avec certains SSO

### ISSUE THREAD

**Issue by Aurely9n** [JeromeDevome/GRR#229]
Bonjour,

J'ai remonté en octobre dernier, un problème concernant les champs "login", "create_by" et "bénéficiaire" dans la DB qui ne peuvent contenir qu'un nombre trop restreint de caractères. En effet, 40 est trop peu pour des logins qui peuvent avoir des préfixe et/ou des suffixes qui ajoutent un nombre de caractères non négligeable à des motifs d'identifiants parfois déjà long de base.
Surtout dans le cas d'enregistrement de logins SSO.

J'ai proposé une solution qui a été intégrée  dans la version 3.5.X via le commit [bc5b941](https://github.com/JeromeDevome/GRR/commit/bc5b94176bd1549f82900ebc3ca2f7fef8e2397b).

Il faudrait pousser cette augmentation de nombre de caractère dans la DB pour la version 4.X également. Afin d'éviter de bloquer des utilisateur à cause de leur login long.

Cordialement,

**Comment by ynaessens** [comment]
Bonjour,
c'est fait avec ce commit https://github.com/JeromeDevome/GRR/commit/58056adf08ab58f490bdd7f2741322a0d516f6a0
Cordialement,
YN
