### ISSUE TITLE
Erreurs après la mise à jours en v4.0

### ISSUE THREAD

**Issue by Larsene** [JeromeDevome/GRR#231]
Bonjour,

à l'issue de la mise à jour, lors de la création d'une nouvelle réservation, j'ai plein de lignes :

`Notice: Trying to access array offset on value of type null in /home/ccps/webapps/grr/include/generationxmlplus.php on line 38
Notice: Trying to access array offset on value of type null in /home/ccps/webapps/grr/include/generationxmlplus.php on line 39
`

Néanmoins, tout semble bien fonctionner à part cela. 

Comment je peux corriger cette erreur ?
![image_2023-01-24_103012065](https://user-images.githubusercontent.com/8544729/214256342-600c2d7d-4a20-42d3-867e-15aaae56a627.png)

**Comment by ynaessens** [comment]
Bonjour,
quelle version de GRR avez-vous installée ? Dans quel contexte (serveur, version de php/MySQL) ?
Je pense que si vous désactivez le module de génération du fichier xml dans les réglages, cela devrait disparaître.
Cordialement,
YN

**Comment by JeromeDevome** [comment]
Il semble y avoir un oublis de ce côté. Dans l'immédiat il faut le désactiver dans le module setting.

**Comment by Larsene** [comment]
Bonjour, merci pour vos retours.
J'ai installé la v4 depuis la 3.4
Effectivement, en changeant la valeur de export_xml_plus_actif à Non, alors plus d'erreurs. 

Merci ! :-)

**Comment by JeromeDevome** [comment]
Bonjour,
Je viens de corriger.
Désormais la génération XML est sous forme de mule externe, téléchargeable gratuitement sur https://github.com/JeromeDevome/GRR-Modules/blob/main/Export%20XML/GRR%204.X.X/devome__export_xml.zip
