### ISSUE TITLE
Connexion administrateur impossible fresh install

### ISSUE THREAD

**Issue by nico-opp** [JeromeDevome/GRR#235]
**Décrivez le bogue**
la première connexion ADMINISTRATEUR ne fonctionne pas suite à une nouvelle installation 

erreur PHP:
AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "login" in /var/www/grr/include/session.inc.php on line 370PHP message: PHP Warning:  Undefined array key "login" in /var/www/grr/include/session.inc.php on line 632'

**Infos GRR**
Version de GRR : 4.0.1
Version PHP : PHP 8.1
Version DB : MariaDB 10.5
Problème suite à une installation ou mise à jour :  installation 

**Reproduire**
Étapes pour reproduire le comportement :
1. lancer l'installeur interactif
2. suivre les 5 étapes d'installation 
3. faire la mise à jour de la DB comme demandée 
4. aller sur l'accueil et se connecter avec le compte ADMINISTRATEUR

**Comportement attendu**
Une connexion réussie ,

**Contexte supplémentaire**
la DB est bien créée et le compte ADMINISTRATEUR bien présent dans la table grr_utilisateurs

**Comment by ynaessens** [comment]
Bonjour,
ce bug est déjà décrit dans la discussion #234 
les investigations sont en cours...
désolé pour le dérangement.
Pour une installation fonctionnelle, la v3.5.0b est conseillée.
Cordialement,
YN

**Comment by nico-opp** [comment]
le commit https://github.com/JeromeDevome/GRR/commit/c3e48362fbdc230a733fb80d2b8f5036745e6cc8 semble avoir résolu le problème .
Merci
HS: A noter que la version v3.5.0b  semble poser un autre problème  après activation du multisite et du CAS:
_AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'grr.grr_j_groupe_se3' doesn't exist in /var/www/grr/include/mysql.inc.php:81\nStack trace:\n#0 /var/www/grr/include/mysql.inc.php(81): mysqli_query()\n#1 /var/www/grr/include/session.inc.php(763): grr_sql_query()\n#2 /var/www/grr/login.php(44): grr_opensession()\n#3 {main}\n  thrown in /var/www/grr/include/mysql.inc.php on line 81'_

**Comment by ynaessens** [comment]
Voici un correctif qui devrait résoudre votre problème de connexion : https://github.com/JeromeDevome/GRR/commit/849b65b66f5ee63fb5fb38a92e45b6138a817e1d
Merci de nous dire si cela convient et si votre installation est en php8.
