### ISSUE TITLE
GRR 3-0-0-RC2.zip erreur Undefined variable: dbPort in /var/www/grr/include/mysql.inc.php on line 36 

### ISSUE THREAD

**Issue by ychoucha** [JeromeDevome/GRR#24]
Bonjour,

j'ai installer la version et j'ai le message d'erreur suivant : 

Undefined variable: dbPort in /var/www/grr/include/mysql.inc.php on line 36 

qu'en est il de la version stable svp ?

**Comment by JeromeDevome** [comment]
Bonjour,
Le fichier config a était modifier dans la version 3, merci de comparer avec le votre.
