### ISSUE TITLE
Erreur : mysqli_query - Php 8.1

### ISSUE THREAD

**Issue by Trickscenique** [JeromeDevome/GRR#241]
**Infos GRR**
Version de GRR : 3.4
Version PHP : 8.1
Problème suite à mise à jour : de php

**Reproduire**
Erreur 500 à la racine du site. 
Pour voir de quoi il s'agit ajouter les lignes suivantes au fichier index.php
`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);`
Voici l'erreur
`Fatal error: Uncaught ArgumentCountError: mysqli_query() expects at least 2 arguments, 1 given in /home/solidairvf/grr/index.php:48 Stack trace: #0 /home/solidairvf/grr/index.php(48): mysqli_query('SET NAMES utf8') #1 {main} thrown in /home/solidairvf/grr/index.php on line 48`

**Comportement attendu**
Code de retour 200

**Résolution du bug**
Changer la ligne 48
`@mysqli_query("SET NAMES utf8");`
en
`$db->set_charset("utf8");`

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre retour d’expérience.
GRR 3.4 n’est pas censé fonctionner avec php8… il aurait fallu installer Grr 3.5.
Néanmoins je prends en compte votre suggestion.
Cordialement 
YN

**Comment by Trickscenique** [comment]
Bonjour,

Je vais tester les mises à jour du coup :)

Est-ce qu'il faut que je passe successivement par l'ensemble des 
versions afin d'arriver en 4.0 ?

Merci par avance.

--- Nassim

Le 21/02/2023 à 11:40, ynaessens a écrit :

**Comment by ynaessens** [comment]
Cela dépend de votre situation : migration depuis un ancien GRR ou installation neuve ?
Dans le premier cas, la 3.5.0 ou 3.5.1 sont les meilleurs choix, dans le second cas, 3.5.1 ou 4.0.2.

**Comment by Trickscenique** [comment]
Merci beaucoup ! Je vais tester la 3.5

--- Nassim

Le 21/02/2023 à 12:07, ynaessens a écrit :
