### ISSUE TITLE
Login non transfé

### ISSUE THREAD

**Issue by Trickscenique** [JeromeDevome/GRR#246]
**Décrivez le bogue**
Lors de la connexion le login n'est pas enregistré en session ce qui ne permet pas d'accéder à l'administration. 

**Infos GRR**
Version de GRR : 4.0.2
Version PHP : Php 8.1

**Solution**
Correctif pour le fichier include/session.inc.php Ligne 614
`$_SESSION['login'] = /*$row['LOGIN'];*/ $_login;`

Cela vient de la fonction grr_sql_row_keyed() qui semble supprimer le champs indexé du tableau de valeur.

**Comment by ynaessens** [comment]
Bonjour,
à mon avis, le problème ne vient pas de grr_sql_row_keyed() mais du fait que LOGIN est distinct de login.
Dans le script vous devriez avoir $_SESSION['login'] = $row['login'];
Cordialement,
YN

**Comment by Trickscenique** [comment]
Je vais essayer comme ceci, cependant en base de donnée le champs s'appelle bien LOGIN (en majuscule).

**Comment by ynaessens** [comment]
Dans quelle table ?

**Comment by Trickscenique** [comment]
Autant pour moi, c'est dans la table grr_log, il me semblait l'avoir vu dans la table grr_utilisateurs.
Par contre sur mon installation, ma modification était bien nécessaire pour que l'authentification reste en $_SESSION. 
Je n'ai pas eus le temps de vérifier avec la clef **login** en minuscule.

**Comment by ynaessens** [comment]
Pas de souci.
Je préfère l'appel par `$row` puisqu'il y a nettoyage de `$_login` lors de la requête.

**Comment by JeromeDevome** [comment]
Bonjour @Trickscenique ,
J'ai corrigé l'état de l'utilisateur dans la version 4.0.2 qui empêché la visualisation du lien admin. Et vu la date du post vous n'êtes pas en 4.0.2 mais plutôt une version RC.

**Comment by JeromeDevome** [comment]
Bonjour  @Trickscenique , votre problème est-il résolut avec la dernière version ?

**Comment by Trickscenique** [comment]
Oui tout à fait !

--- Nassim

Le 21/03/2023 à 20:53, JeromeB a écrit :
