### ISSUE TITLE
Version 4.0.2 stable est affiché 4.0.2-RC1

### ISSUE THREAD

**Issue by xillibit** [JeromeDevome/GRR#248]
**Décrivez le bogue**
La version 4.0.2 stable est considéré comme étant la 4.0.2-RC1

**Infos GRR**
Version de GRR : 4.0.2 stable
Version PHP : 8.0
Problème suite à une installation ou mise à jour : mise à jour et installation produisent le même probléme

**Reproduire**
Étapes pour reproduire le comportement :
1. Télécharger le paquet de la version 4.0.2 stable
2. Allez dans include puis misc.inc.php
3. Dans le fichier c'est indiqué 4.0.2RC1

**Comportement attendu**
Quand on installe la version 4.0.2 stable ça ne devrait pas être affiché la 4.0.2-RC1

**Comment by saf-bredow** [comment]
J'ai le même souci qui entraine un message dans l'interface d'administration : "Version de développement, ne pas utiliser en production !"

**Comment by ROYERDidier** [comment]
Bonjour,
J'ai le même souci avec le message  "Version de développement, ne pas utiliser en production !" alors qu'il est bien indiqué _$version_grr = "4.0.2";_ dans _/include/misc.in.php_
Une idée ?

**Comment by JeromeDevome** [comment]
Bonjour,
J'ai corrigé la version, ceci est suite à une erreur avec un duplicata de tag dans GitHub.  Ceci es corrigé.

Merci à vous
