### ISSUE TITLE
Présence de la fonction error_reporting 

### ISSUE THREAD

**Issue by fbredow** [JeromeDevome/GRR#249]
Des erreurs "deprecated" apparaissent lors de la création d'une réservation malgré une configuration de PHP spécifiant de les masquer.

**Infos GRR**
Version de GRR : 4.0.2
Version PHP : 8.2.1

Le fichier `edit_entry.php` contient la fonction `error_reporting` qui altère la configuration de PHP entrainant l'apparition des erreurs.

**Comment by saf-bredow** [comment]
Voici les erreurs qui s'affichent : 
`Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193 Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124 Deprecated: Function utf8_encode() is deprecated in /var/www/html/include/language.inc.php on line 124`

J'ai commenté les lignes dans le fichier edit_entry.php.

Je pense que c'est une mauvaise pratique que forcer les paramètres de PHP dans le code. Peut-être y a-t-il une bonne raison qui m'échappe.

**Comment by ynaessens** [comment]
Merci pour votre retour.
La compatibilité avec php 8.2 reste donc à améliorer.
Oui, ce n'est pas bien de jouer avec les réglages de php dans le code, mais je pense que ce sont des scories de débogage... et que le fichier définitif ne devrait pas contenir ces lignes.

**Comment by ynaessens** [comment]
Bonjour @saf-bredow ,
j'ai eu beau essayer à partir de mon ancienne installation ou sur une installation depuis zéro (GRR 4.0.2 sur php 8.2.0), je n'ai pas retrouvé les erreurs mentionnées.
Cependant, je propose une réécriture de la fonction test_utf8() qui posait problème :
`function test_utf8($str){
    if (is_null($str))
        return TRUE;
    else 
        return mb_check_encoding($str, "UTF-8");
}`
Cette modification est-elle utile dans votre cas ?
Merci d'avance pour votre aide.
Cordialement,
YN

**Comment by saf-bredow** [comment]
Les erreurs `Deprecated: Function utf8_decode() is deprecated in /var/www/html/include/language.inc.php on line 124` disparaissent, mais il reste les erreurs `Deprecated: Function strftime() is deprecated in /var/www/html/include/language.inc.php on line 193`.

Pour info, j'utilise php-fpm dans un container docker sous Alpine linux :`FROM php:8.2-fpm-alpine`.

**Comment by ynaessens** [comment]
Bonjour,
les erreurs sur strftime() avec php 8+ se produisent soit parce que vous n'avez pas chargé le module intl dans php, soit parce que le niveau d'erreur deprecated est activé. En effet, c'est une erreur non bloquante (le script fonctionne bien) mais strftime() ne devrait plus être utilisée avec php 8. Je mets Readme.md à jour sur ce point.
Cordialement,
YN

**Comment by saf-bredow** [comment]
Effectivement en ajoutant le module "intl" l'erreur n'apparait plus. Merci pour l'info.
