### ISSUE TITLE
Affichage des domaines et ressources

### ISSUE THREAD

**Issue by ROYERDidier** [JeromeDevome/GRR#252]
Bonjour,
Impossible d'afficher les listes des domaines et ressources sous une autre forme que des boutons (menu de gauche).
Je précise que j'utilise le mode multisites mais cela fait pareil sans le multisites.

**Infos GRR**
Version de GRR : 4.02 (latest)
Version PHP : 7.4.33

![image](https://user-images.githubusercontent.com/82160773/226886971-c04b9ec0-d117-48b3-9a7b-8afefe197bd6.png)

![image](https://user-images.githubusercontent.com/82160773/226886685-65d026e9-aa81-4f12-abeb-a0a187d12cfd.png)

**Comment by ynaessens** [comment]
Bonjour,
avez-vous vérifié que dans les réglages de votre compte personnel, l'affichage en boutons n'est pas sélectionné ? Ce sont en effet les réglages personnels qui prévalent sur l'affichage par défaut.
Cordialement,
YN

**Comment by ROYERDidier** [comment]
Oups !
Oui, effectivement, ça fonctionne.
Désolé d'avoir polluer.
