### ISSUE TITLE
Bug sur le choix des ressources

### ISSUE THREAD

**Issue by fabboyrie** [JeromeDevome/GRR#256]
**Décrivez le bogue**
Suivant les utilisateurs, pour les ressources à accès restreint, ils ne voient aucune ressource dans la liste, ce qui les empêche de réserver.

**Infos GRR**
Version de GRR : 3.5.0c
Version PHP : 7.2
Problème suite à une installation ou mise à jour : le problème existait déjà en 3.4.x, ce qui a motivé l'upgrade en  3.5

**Analyse du problème**
Notre instance grr s'authentifie sur l'annuaire ldap. Les logins de notre annuaire ldap ont des majuscules/minuscules.
Dans edit_entry on a 
$tab_rooms_noaccess = no_book_rooms($user_name);

Et le $user_name passé à cette fonction semble être le login ldap en majuscule. (Choix curieux vu que dans la table utilisateur, les logins respectent la casse du ldap)

Dans ./include/functions.inc.php si on regarde la fonction no_book_rooms($user_name), on a des requêtes sql qui opérant sur une table en collation case insensitive ne posent pas de problème. Puis le bout de code suivant.
            __if (($login != $user) && ($auth_level < 3)){ // un gestionnaire de ressource peut toujours accéder !__

Et là, ça ne passe plus...

J'ai rajouté un strtolower des deux côtés de la comparaison, mais ce n'est peut être pas la solution optimale.

**Comment by ynaessens** [comment]
Je complète : c'est la variable de session qui est en majuscules et qui est retournée par getUserName(), donc il devrait suffire de tester `if ((strtoupper($login) != $user) && ($auth_level < 3)){`
Mais comme les tables sont en classement utf8mb4_unicode_ci, votre idée est tout aussi valable. On ne peut avoir dans la table deux utilisateurs tels que Martin et MARTIN...
Poussé sur le dépôt : https://github.com/JeromeDevome/GRR/commit/dea627a22d7a4ff6c385a89cca0be42b18034a14
À confirmer en authentification sur LDAP, car en base locale la modification du code est sans effet apparent.
Cordialement,
YN

**Comment by fabboyrie** [comment]
Bonjour

après plusieurs jours de fonctionnement je n'ai plus aucune plainte des utilisateurs.

Je pense donc que l'on peut clore le bug.

Cordialement

F B
