### ISSUE TITLE
Version 4 : jour et mois en anglais / test de la langue française erroné ?

### ISSUE THREAD

**Issue by sdelcroix** [JeromeDevome/GRR#257]
**Décrivez le bogue**
Depuis la version 4 de GRR, l'identifiant interne pour la langue française est "fr-fr".

Or, dans le fichier **include/language.inc.php**, le test suivant est fait pour savoir si la langue de GRR est le français :
```PHP
if ($locale == 'fr')
{
    ...
}
```
Le test est ainsi toujours faux et l'on rentre dans le bloc suivant dédié aux autres langues :
```PHP
// Les autres langues que le français
if ($locale != 'fr')
{
    ...
}
```
Ce qui aboutit, dans mon cas, à `setlocale(LC_ALL, "fr-fr");` qui ne peut pas s'appliquer car la locale n'existe pas.
Par conséquent, la locale utilisée est "C" et les jours et mois sont affichés en anglais.

**Infos GRR**
Version de GRR : 4.0.2
Version PHP : 7.2
Problème suite à une installation ou mise à jour : installation

**Comportement attendu**
Le jour et le mois de la date du jour devraient être traduits en français.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Ubuntu

**Contexte supplémentaire**
```bash
cat /etc/default/locale
 
LANG=fr_FR.UTF-8
```
```bash
locale -a

C
C.UTF-8
fr_FR.utf8
POSIX
```
```bash
locale

LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by sdelcroix** [comment]
En modifiant le test de la manière suivante, j'obtiens les jours et mois en français :
```PHP
if ($locale == 'fr-fr')
{
    ...
}
```

**Comment by JeromeDevome** [comment]
Bonjour,
J'ai fais un commit [4a3a22c](https://github.com/JeromeDevome/GRR/commit/4a3a22c262571a161fd98383cd1a873c0ed784ab)

Pouvez-vous me dire si c'est bon pour vous ?

Vous en remerciant,

**Comment by sdelcroix** [comment]
Bonjour,

c'est bon pour moi avec ces corrections. Merci ;)
