### ISSUE TITLE
New install 4.0.3

### ISSUE THREAD

**Issue by gregouzdev** [JeromeDevome/GRR#259]
Install.txt :
-> ligne 10. manque la spécification du dossier "/personnalisation/" pour connect.inc.php
-> ligne 36 . "/personnalisation/config.inc.php"; le fichier n'existe pas par default

/include/config.inc.php :
-> ligne 232 : deux fois le meme include ?!

**Comment by ynaessens** [comment]
Merci pour votre retour.
C'est corrigé.
Cordialement,
YN
