### ISSUE TITLE
Illegal mix of collations 

### ISSUE THREAD

**Issue by n57b** [JeromeDevome/GRR#261]
**Décrivez le bogue**
Il m'est impossible en installation automatiser de valider la base de donnée.

**Infos GRR**
Version de GRR : 4.0.3
Version PHP : 7.4.33
MariaDB : 15.1 Distrib 10.5.18-MariaDB

Problème suite à une installation ou mise à jour : 
Installation automatique

**Reproduire**
Étapes pour reproduire le comportement :
Faire une installation automatique 

**Comportement attendu**
Pouvoir finir l'installation

**Captures d'écran**
Le cas échéant, ajoutez des captures d'écran pour aider à expliquer votre problème.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : DEBIAN 11

**Contexte supplémentaire**
Voir les screen et info complémentaire en dessous : 

Quand je clique sur privilege,.
![erreur sql1](https://user-images.githubusercontent.com/131746162/234195705-c53d9121-220f-4613-a4e5-41f442a52c6b.JPG)

( SELECT `User`, `Host`, `Select_priv`, `Insert_priv`, `Update_priv`, `Delete_priv`, `Create_priv`, `Drop_priv`, `Grant_priv`, `Index_priv`, `Alter_priv`, `References_priv`, `Create_tmp_table_priv`, `Lock_tables_priv`, `Create_view_priv`, `Show_view_priv`, `Create_routine_priv`, `Alter_routine_priv`, `Execute_priv`, `Event_priv`, `Trigger_priv`, '*' AS `Db`, 'g' AS `Type` FROM `mysql`.`user` WHERE NOT (`Select_priv` = 'N' AND `Insert_priv` = 'N' AND `Update_priv` = 'N' AND `Delete_priv` = 'N' AND `Create_priv` = 'N' AND `Drop_priv` = 'N' AND `Grant_priv` = 'N' AND `References_priv` = 'N' AND `Create_tmp_table_priv` = 'N' AND `Lock_tables_priv` = 'N' AND `Create_view_priv` = 'N' AND `Show_view_priv` = 'N' AND `Create_routine_priv` = 'N' AND `Alter_routine_priv` = 'N' AND `Execute_priv` = 'N' AND `Event_priv` = 'N' AND `Trigger_priv` = 'N')) UNION ( SELECT `User`, `Host`, `Select_priv`, `Insert_priv`, `Update_priv`, `Delete_priv`, `Create_priv`, `Drop_priv`, `Grant_priv`, `Index_priv`, `Alter_priv`, `References_priv`, `Create_tmp_table_priv`, `Lock_tables_priv`, `Create_view_priv`, `Show_view_priv`, `Create_routine_priv`, `Alter_routine_priv`, `Execute_priv`, `Event_priv`, `Trigger_priv`, `Db`, 'd' AS `Type` FROM `mysql`.`db` WHERE 'grr' LIKE `Db`     AND NOT (`Select_priv` = 'N' AND `Insert_priv` = 'N' AND `Update_priv` = 'N' AND `Delete_priv` = 'N' AND `Create_priv` = 'N' AND `Drop_priv` = 'N' AND `Grant_priv` = 'N' AND `References_priv` = 'N' AND `Create_tmp_table_priv` = 'N' AND `Lock_tables_priv` = 'N' AND `Create_view_priv` = 'N' AND `Show_view_priv` = 'N' AND `Create_routine_priv` = 'N' AND `Alter_routine_priv` = 'N' AND `Execute_priv` = 'N' AND `Event_priv` = 'N' AND `Trigger_priv` = 'N')) ORDER BY `User` ASC, `Host` ASC, `Db` ASC;

 MySQL a répondu : Documentation
#1267 - Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_unicode_ci,COERCIBLE) for operation '<>'

**Comment by ynaessens** [comment]
Bonjour,
je ne reproduis pas ce bug en installation depuis la page de GRR 4.0.3.
Cependant je note un mélange des genres, certains champs sont en utf8mb4_general_ci et d'autres en latin1_swedish_ci. Mais comme ils ne sont pas mis en relation, cela ne devrait pas être problématique.
Je ne vois pas d'où sort le utf8mb4_unicode_ci. Peut-être des réglages de votre serveur MariaDB ?
Désolé de ne pouvoir vous aider davantage.
Cordialement,
YN

**Comment by n57b** [comment]
Bon la solution est simple : CHMOD 777 sur le dossier GRR ...

**Comment by ynaessens** [comment]
C'est plutôt brutal et pas très sage du point de vue de la sécurité.
Il faudrait retester en environnement Linux pour corriger plus raisonnablement...
