### ISSUE TITLE
Champs personnalisé : "case à cocher" et ordre des champs

### ISSUE THREAD

**Issue by Larsene** [JeromeDevome/GRR#262]
**Il s'agit d'une demande de fonctionnalité**

**Gestion de case à cocher (checkbox)**
Il serait super d'avoir la possibilité de rajouter un champ de type checkbox parmi les champs additionnels disponibles dans le logiciel (il y a cependant une alternative simple utilisée : une liste avec des valeurs oui/non)

**Gestion d'un ordre d'affichage dans les champs additionnels**
Les champs additionnels semblent actuellement triés par ordre alphabétique. Il serait super d'avoir un index afin de pouvoir trier de façon plus précise les différents champs additionnels

**Comment by ynaessens** [comment]
Bonjour,
je pense que les champs additionnels de type liste de valeurs (avec l'option obligatoire éventuellement) répondent à votre problème s'il n'y a qu'une valeur à sélectionner dans une liste (équivalent à des boutons radio) et s'il y a plusieurs valeurs à choisir, le type liste à valeurs oui/non convient come vous le suggérez.
Pour ce qui est du tri des champs, je note votre suggestion pour une future évolution des champs additionnels.
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
les commits https://github.com/JeromeDevome/GRR/commit/47740c6d3d2776b769fd4c8050abd048c482a0e7 pour la version 4.1.1 et https://github.com/JeromeDevome/GRR/commit/82293d2ce17d7135b71e7170ba49bc46e7585831 pour la 3.5.1 devraient répondre à votre demande de champs additionnels de type checkbox.
Cordialement,
YN
