### ISSUE TITLE
Affichage de la saisie d'une réservation

### ISSUE THREAD

**Issue by Larsene** [JeromeDevome/GRR#263]
## Amélioration de l'affichage
l'affichage des champs lors d'une saisie de réservation n'est pas optimal (ex, largeur des champs, positionnement, etc)

### Proposition
modifier le template d'affichage de la page en utilisant les fonctionnalités rendues possibles par Bootstrap et supprimer totalement le positionnement par table (mais utiliser les container/row/column de bootstrap)

### Suggestion
Je pourrais éventuellement regarder ce point et proposer une modification de la page, si vous le souhaitez

**Comment by ynaessens** [comment]
Bonjour,
vos remarques s'appliquent à quelle version de GRR ?
En particulier avez-vous testé la version 3.5.1 ?
Cordialement,
YN

**Comment by Larsene** [comment]
Bonjour, j'utilise la version 4.0.0b...

en l'occurence, voici ce que j'ai sur mon install (si ça peut vous aider !) :
![image](https://user-images.githubusercontent.com/8544729/234281912-a4d38a82-302a-4c41-afb9-3b6d18399431.png)

**Comment by ynaessens** [comment]
Bonjour,
il faudrait mettre à jour votre version bêta vers une version stable.
Mais votre remarque sur le code html est tout à faut pertinente. C'est a priori mieux en 3.5.1, mais si vous voulez contribuer, vous êtes bienvenu :-)
Cordialement,
YN

**Comment by ynaessens** [comment]
Cela dépend des fonctionnalités de journaux que vous avez mises en place. La 3.5.1 est en retard sur ce point, ainsi que la table des participants... Le script de mise à jour fonctionne selon les indices croissants, je n'ai jamais testé une rétrogradation de 4 vers 3. Le mieux serait peut-être de tenter la mise en place de edit_entry de 3.5.1 vers 4.0.3 puis ajuster, mais pas sûr que ce soit immédiat.
J'ai d'autres tâches qui attendent, mais la reprise du code html est à faire...

**Comment by JeromeDevome** [comment]
Je vous déconseiller dans le sens là , passé plutôt à la version 4.0.3.
