### ISSUE TITLE
Décalage réservation

### ISSUE THREAD

**Issue by Mat8556** [JeromeDevome/GRR#267]
**Décrivez le bogue**
Une description claire et concise de ce qu'est le bogue.

**Infos GRR**
Version de GRR : 3.5.1
Version PHP : 7.4.9
Problème suite à une installation ou mise à jour :  Installation

**Reproduire**
Page semaine avec une seule ressource
Voir capture d'écran jointe

**Comportement attendu**
Pas de décalage
La réservation de 1h30 prend deux places au lieu d'une

**Captures d'écran**
![Sans titre](https://user-images.githubusercontent.com/132690013/236505750-744c7e15-f358-42a2-a812-2ddd4d917550.png)

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : W11
  - Navigateur : Firefox
  - Version 112

**Contexte supplémentaire**
Quand je fais une réservation de 3h aucun problème

Après quelques recherche j'ai mis en commentaire les lignes 329 à 331 dans week.php :
if(!in_array(date('i', $d[$weekday][$slot]["horaireFin"]), $minutesFinCreneaux)) {
$d[$weekday][$slot]["duree"] += 1;
}

Le problème a disparut mais j'en ai peut-être causé un autre....

**Comment by ynaessens** [comment]
Bonjour,
je ne reproduis pas ce bug avec ma version de GRR 3.5.1...
Avez-vous réglé correctement les paramètres du domaine, notamment 

Plus petit bloc réservable, en secondes (1800 secondes = 1/2 heure) : 5400
Durée par défaut d'une réservation, en secondes (doit être un multiple de la valeur précédente) : 5400

pour coller à votre capture d'écran ?
Cordialement,
YN

**Comment by Mat8556** [comment]
Bonjour,
Correctement je ne sais pas mais oui j'ai mis 5400, au deux.

@JeromeDevome  votre solution fonctionne dans mon cas.

**Comment by ynaessens** [comment]
Bonjour,
ce n'est pas très satisfaisant : vous avez ce bug d'affichage et pas moi, avec les mêmes créneaux de durée 1h 30min.
Ce serait intéressant de connaître les valeurs de start_time et end_time pour la réservation qui pose problème.
Votre domaine est bien en mode intervalle de temps, pas en mode créneaux prédéfinis ?
