### ISSUE TITLE
"case courrier"

### ISSUE THREAD

**Issue by remyd1** [JeromeDevome/GRR#27]
Bonjour,

J'ai remarqué que des champs apparaissent automatiquement comme "ressource empruntée" ou "case courrier". Certaines ressources réservables ne nécessitent pas ces champs superflus. Il serait intéressant de pouvoir les désactiver sans avoir à commenter le code correspondant...

Rémy

**Comment by JeromeDevome** [comment]
Bonjour,
Nous le ferrons dans une future version ;)
