### ISSUE TITLE
accès annuaire ldap grr version 4.0.3 et 4.1.0

### ISSUE THREAD

**Issue by ClementBoulmont** [JeromeDevome/GRR#271]
**Décrivez le bogue**
j'ai le message suivant qui apparait : L'accès à l'annuaire LDAP n'est pas configuré
L'authentification LDAP est donc pour le moment impossible.

Et quand j'appuie sur configurer LDAP je rentre toute mes infos et j'ai l'erreur :  La connexion au serveur LDAP a échoué
Revenez à la page précédente et vérifiez les informations fournies.

Sur la version 3.1.0.2 je n'ai pas ce genre de problème

**Infos GRR**
Version de GRR : 4.0.3 et 4.1.0
Version PHP : 7.4
Problème suite à une installation ou mise à jour : 

**Captures d'écran**
![Capture grr 1](https://github.com/JeromeDevome/GRR/assets/73893380/06db2fe3-10dc-47d7-bd9b-1eff5af15386)
![Capture grr 2](https://github.com/JeromeDevome/GRR/assets/73893380/eacdd489-fb2f-40c5-ba30-da1c3d832b07)

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10
  - Navigateur : chrome
  - Version 113.0.5672.127

**Comment by ynaessens** [comment]
Bonjour,
la signature de la fonction de connexion à un annuaire LDAP a changé.
Si vous reprenez les anciens réglages, il est probable que ce soit la cause de l'échec.
En gros, il faut préciser dans l'adresse le protocole ldap://nom_du_serveur ou ldaps://nom_du_serveur et pas seulement nom_du_serveur comme dans les anciennes versions de GRR.
Si vous avez renseigné le serveur ainsi et que ça ne passe pas, pouvez-vous essayer avec les versions récentes (3.5.1, ou 3.5.0 ou 3.4.3) et rapporter à partir de laquelle la connexion est refusée ?
Cordialement,
YN

**Comment by ClementBoulmont** [comment]
> Bonjour, la signature de la fonction de connexion à un annuaire LDAP a changé. Si vous reprenez les anciens réglages, il est probable que ce soit la cause de l'échec. En gros, il faut préciser dans l'adresse le protocole ldap://nom_du_serveur ou ldaps://nom_du_serveur et pas seulement nom_du_serveur comme dans les anciennes versions de GRR. Si vous avez renseigné le serveur ainsi et que ça ne passe pas, pouvez-vous essayer avec les versions récentes (3.5.1, ou 3.5.0 ou 3.4.3) et rapporter à partir de laquelle la connexion est refusée ? Cordialement, YN

Bonjour,
J'ai essayé sur la version 4 ça n'a pas fonctionné mais en revanche sur la 3.5.1 ça fonctionne bien

**Comment by ynaessens** [comment]
Merci pour votre retour.
Faut-il comprendre que vous avez repris le fichier de la version 3.5.1 et qu’alors la connexion depuis la version 4 s’est établie ?

**Comment by ClementBoulmont** [comment]
> Merci pour votre retour. Faut-il comprendre que vous avez repris le fichier de la version 3.5.1 et qu’alors la connexion depuis la version 4 s’est établie ?

Bonjour,
En faite j'ai installé 2 versions de GRR sur ma machine. Une version 3 et une version 4.
J'ai d'abord testé sur la version 4 sur l'interface graphique mais ça n'avait pas fonctionné du coup je suis passé sur la version 3.5.1 . J'ai remarqué que ça avait fonctionné.
Puis, histoire de faire un test je me suis mis à modifier le fichier config_ldap.inc.php présent sur les fichiers de la version 4 de GRR présent sur ma machine. Une fois que j'ai fait les modifications avec le ldap:// devant l'adresse de mon serveur ldap je me suis rendu sur l'interface graphique pour configurer ldap directement dessus. Finalement, j'ai pu réussir à configurer ldap sur ma version 4 de GRR

**Comment by ynaessens** [comment]
Bonjour,
pouvez-vous me confirmer que ce commit https://github.com/JeromeDevome/GRR/commit/7f7ff83fe09ed280d2ca5d4f3d81fc5f51c08cf4 reprend bien les éléments que vous avez utilisés pour configurer la connexion LDAP avec la version 4.0.3 ?
Cordialement,
YN

**Comment by ClementBoulmont** [comment]
> Bonjour, pouvez-vous me confirmer que ce commit [7f7ff83](https://github.com/JeromeDevome/GRR/commit/7f7ff83fe09ed280d2ca5d4f3d81fc5f51c08cf4) reprend bien les éléments que vous avez utilisés pour configurer la connexion LDAP avec la version 4.0.3 ? Cordialement, YN

Bonjour,
Sur mon interface de la version 4.0.3 j'ai plutôt "Adresse de l'annuaire. Laissez «localhost» si l'annuaire est installé sur la même machine que GRR. Sinon, indiquez l'adresse du serveur. *" qui est affiché. Mais j'ai en tout cas utilisé ldap://adresse_ip_annuaire_ldap dans ma configuration

Cordialement,
