### ISSUE TITLE
GRR version 4.0.3 : problème avec UTF-8 ?

### ISSUE THREAD

**Issue by ClementBoulmont** [JeromeDevome/GRR#274]
**Décrivez le bogue**
Incorrect string value: '\xE9ment' for column `grr`.`grr_utilisateurs`.`prenom` at row 1 Q=UPDATE grr_utilisateurs SET nom='nom', prenom='pr�nom', email='p.nom@mon-domaine.org' WHERE login='p.nom' qui apparait quand je me connecte avec mes identifiants sur l'interface graphique de GRR

**Infos GRR**
Version de GRR : 4.0.3
Version PHP : 7.4.33
Problème suite à une installation ou mise à jour : les deux

**Comportement attendu**
J'arrive à me connecté avec mes identifiants

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10
  - Navigateur : chrome
  - Version : 114.0.5735.110

**Contexte supplémentaire**
J'utilise un powershell pour me connecter en ssh sur un raspberry pi 3 où je stocke ma version 4 de GRR. J'ai aussi une version 3 dessus où je n'ai pas ce problème

**Comment by ClementBoulmont** [comment]
Bonjour,
C'est la version 3.5.1
Cordialement

**Comment by ynaessens** [comment]
Merci pour votre retour.
C'est donc une erreur spécifique à la version 4.

**Comment by JeromeDevome** [comment]
Bonjour,
Avez-vous bien installé l'utf-8 sur votre serveur ?

**Comment by ynaessens** [comment]
Bonjour,
je reviens sur votre question : dans ce type d'installation, l'authentification se fait-elle sur la base locale de GRR, ou à la manière d'une authentification LDAP ou CAS ?
Cordialement,
YN

**Comment by ClementBoulmont** [comment]
> Bonjour, je reviens sur votre question : dans ce type d'installation, l'authentification se fait-elle sur la base locale de GRR, ou à la manière d'une authentification LDAP ou CAS ? Cordialement, YN

Bonjour,
L'authentification peut se faire aussi bien sur la base locale de GRR qu'avec l'authentification LDAP
Cordialement

**Comment by ClementBoulmont** [comment]
> Bonjour, Avez-vous bien installé l'utf-8 sur votre serveur ?

Bonjour,
Normalement, oui je l'ai bien installé je vérifierais à l'occasion quand je pourrais

**Comment by ynaessens** [comment]
Bonjour @ClementBoulmont ,
si l'erreur que vous rapportez se produit lors d'une authentification sur l'annuaire LDAP, le commit https://github.com/JeromeDevome/GRR/commit/d2240e0e8f743a4097dbed85188c0e2789df79f1 devrait corriger le bug.
Pouvez-vous tester et rendre compte ?
Cordialement,
YN

**Comment by ClementBoulmont** [comment]
> Bonjour @ClementBoulmont , si l'erreur que vous rapportez se produit lors d'une authentification sur l'annuaire LDAP, le commit [d2240e0](https://github.com/JeromeDevome/GRR/commit/d2240e0e8f743a4097dbed85188c0e2789df79f1) devrait corriger le bug. Pouvez-vous tester et rendre compte ? Cordialement, YN

Bonjour,

En modifiant les bouts de code comme indiqué sur le commit d2240e0 a bien corrigé le bug.

Merci pour votre aide,

Cordialement
