### ISSUE TITLE
Permettre aux administrateurs de marquer une ressource comme empruntée quand ils créent une réservation

### ISSUE THREAD

**Issue by CVZ-es** [JeromeDevome/GRR#275]
Bonjour à toutes et tous,

Tout d'abord, merci pour le travail réalisé, et pour les améliorations des derniers mois.

J'avais une petite suggestion à faire, celle de permettre aux administrateurs de marquer une ressource comme empruntée quand ils créent une réservation (directement sur le formulaire de création de la résa)
On a bcp de mal à faire créer les réservations par les utilisateurs, et donc on les crée souvent pour eux, il serait donc utile de pouvoir marquer la ressource comme empruntée au moment de la création de la réservation (comme pour la clef).

Voilà, merci d'avance et bon week-end
Damien

**Comment by JeromeDevome** [comment]
Bonne idée, je vais regarder pour dans une des prochaines versions

**Comment by CVZ-es** [comment]
Super, merci !

**Comment by CVZ-es** [comment]
Bonsoir @ynaessens, 
Voici quelques éléments complémentaires pour vous permettre de juger de la pertinence de la demande.
Nous utilisons GRR pour les prêts de matériels, ce sont au total 210 ressources disponibles au prêt dans 14 domaines, dans dans une résidence pour artistes.
Ensuite, il y a deux cas d'usage, le premier, qui devrait être la norme : un artiste fait une réservation de matériel sur une plage de temps, puis il passe emprunter la ressource. Dans ce cas , nous la marquons comme empruntée puis au retour du matériel nous la marquons comme restituée.
Le second cas d'usage, qui est malheureusement trop fréquent, il passe, sans avoir fait préalablement de réservation. On crée donc la réservation pour lui, et ensuite (si on n'oublie pas); on doit rechercher la réservation, pour marquer la ressource comme empruntée. Si comme pour la clef, il y avait, pour les administrateurs et les personnes chargée du dépôt du matériel, il existait une case à cocher "ressources empruntée", on pourrait faire les deux opérations à la fois, et surtout il y aurait bcp moins de risque d'oublis de la marquer comme emprunté.

J'espère que cela vous aide dans la compréhension de notre usage.
N'hésitez pas si vous avez des questions.
Bien cordialement
Damien

**Comment by ynaessens** [comment]
Bonjour @CVZ-es ,
merci pour vos explications qui montrent bien la pertinence de votre demande.
Ce sera donc intégré dès que possible dans GRR.
Cordialement,
YN

**Comment by CVZ-es** [comment]
Bonjour @ynaessens, 
Quelle réactivité  !
En fait, on a déjà migré sur la branche 4.0.3
Mais pas de panique la fin de l'année universitaire approchant, on est plus sur les retours de matériel en ce moment !
En tout cas, un grand merci !
Damien

**Comment by JeromeDevome** [comment]
Bonjour @CVZ-es  , j'ai fait un commit (7b893a18) sur la version 4. Elle contient l'ajout de @ynaessens .
L'option sera disponible dans la version 4.1.1 qui arrive bientôt (max 4jours).

**Comment by CVZ-es** [comment]
Bonjour Jérôme,
Super, merci, du coup, je ferai le saut vers la 4.1.1 et tout sera opérationnel pour la rentrée :-)
Merci encore
Damien

**Comment by JeromeDevome** [comment]
La version 4.1.1 est disponible.

**Comment by CVZ-es** [comment]
Merci Jérôme.
Je viens de déployer la 4.1.1 et de tester, c'est nickel !
Encore merci, et bel été !
Damien
