### ISSUE TITLE
GRR 4.0.3 : Erreur configperso.inc

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#276]
Bonjour,

J'ai fais la mise à jour 4.0.3 sur grr, puis je ne pouvais plus faire de reservation, j'avais ce code d'erreur :

Warning: file_exists(): open_basedir restriction in effect. File(../personnalisation/configperso.inc.php) is not within the allowed path(s): (/var/www/grr/:/usr/lib/php/:/tmp/) in /var/www/grr/include/config.inc.php on line 232

Warning: Cannot modify header information - headers already sent by (output started at /var/www/grr/include/config.inc.php:232) in /var/www/grr/include/admin.inc.php on line 41

J'ai donc commanté les deux derniere ligne du fichier include/config.inc.php

#if(file_exists('../personnalisation/[configperso.inc](https://configperso.inc/).php'))
#       include('../personnalisation/[configperso.inc](https://configperso.inc/).php');

**Comment by ynaessens** [comment]
Bonjour,
je ne pense pas à un bug mais plutôt à une restriction de parcours des dossiers sur votre serveur (hébergement mutualisé ?).
Il faudrait, dans les réglages de GRR, renseigner l'adresse (URL) de la racine de votre GRR. Alors, php ne va pas calculer l'adresse à partir du contexte mais à partir de l'URL renseignée.
Merci de nous dire si cela corrige le bug.
Cordialement,
YN
