### ISSUE TITLE
Debian 12 - PHP 8.2

### ISSUE THREAD

**Issue by plegrand1** [JeromeDevome/GRR#278]
Bonjour,
j'utilise **GRR** en version **3.4.3**, sur une Debian stable.
Suite à la mise à jour vers Debian BookWorm (12) donc passage à **PHP 8.2**, GRR n'est plus fonctionnel et j'ai ces messages d'erreur:

```
PHP Warning:  session_name(): Session name cannot be changed when a session is active in /var/www/grr/include/session.inc.php on line 624
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'grr.grr_j_groupe_se3' doesn't exist in /var/www/grr/include/mysql.inc.php:81\nStack trace:\n#0 /var/www/grr/include/mysql.inc.php(81): mysqli_query()\n#1 /var/www/grr/include/session.inc.php(762): grr_sql_query()\n#2 /var/www/grr/index.php(135): grr_opensession()\n#3 {main}\n  thrown in /var/www/grr/include/mysql.inc.php on line 81
```
J'ai ajouté les lignes suivantes dans le fichier index.php:
**ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);**
afin d'afficher les erreurs:
```
Deprecated: Creation of dynamic property CAS_Client::$_server_base_url is deprecated in /var/www/grr/include/CAS/Client.php on line 953
Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/grr/include/CAS/Client.php on line 1055
Deprecated: Function utf8_decode() is deprecated in /var/www/grr/include/session.inc.php on line 1201
Deprecated: Function utf8_decode() is deprecated in /var/www/grr/include/session.inc.php on line 1202
Deprecated: Function utf8_decode() is deprecated in /var/www/grr/include/session.inc.php on line 1203
Deprecated: Function utf8_encode() is deprecated in /var/www/grr/include/session.inc.php on line 487
Deprecated: Function utf8_encode() is deprecated in /var/www/grr/include/session.inc.php on line 488
Deprecated: Function utf8_encode() is deprecated in /var/www/grr/include/session.inc.php on line 489
Warning: session_name(): Session name cannot be changed when a session is active in /var/www/grr/include/session.inc.php on line 624
Fatal error: Uncaught mysqli_sql_exception: Table 'grr.grr_j_groupe_se3' doesn't exist in /var/www/grr/include/mysql.inc.php:81 Stack trace: #0 /var/www/grr/include/mysql.inc.php(81): mysqli_query() #1 /var/www/grr/include/session.inc.php(762): grr_sql_query() #2 /var/www/grr/index.php(135): grr_opensession() #3 {main} thrown in /var/www/grr/include/mysql.inc.php on line 81
```

Pourriez-vous m'indiquer la marche à suivre pour rendre GRR de nouveau fonctionnel ?

D'avance merci pour votre aide.
Cordialement
Pascal

**Comment by ynaessens** [comment]
Bonjour,
Grr 3.4.3 n’est pas compatible avec php8.2.
Veuillez installer Grr 3.5.1 ou 4.0.3.
N’hésitez pas à revenir si vous avez encore des erreurs.
Cordialement 
YN

**Comment by plegrand1** [comment]
Merci pour votre réponse,
faut-il faire des mise à jour successives ou bien utiliser directement la "latest" sur une installation existante ?

**Comment by plegrand1** [comment]
Bonjour et merci encore pour votre réponse.
Du coup je suis cette procédure : https://site.devome.com/fr/grr/telechargement/category/2-informations-documentations?download=2:mise-a-jour-de-votre-grr

**Comment by ynaessens** [comment]
Bonjour,
la procédure de mise à jour est décrite dans le fichier install.txt, mais comme je vous le disais précédemment, je préfère faire une installation neuve puis restaurer les anciennes données et terminer par la mise à jour de la base lorsque Grr le demande.
Cordialement,
YN

**Comment by plegrand1** [comment]
J'ai procédé à la mise à jour en installant les nouveaux fichiers puis à la première connexion, la mise à jour de la base de données s'est faite sans soucis visiblement. OK partout.

Je rencontre des soucis à l'utilisation


**Par défaut, l'authentification se fait via le CAS et semble fonctionner à quelques messages d'erreur prêts :** 
```
[Wed Jun 21 08:31:18.595610 2023] [php:warn] [pid 465319] [client 192.168.151.38:62465] PHP Warning:  session_name(): Session name cannot be changed when a session is active in /var/www/grr/include/session.inc.php on line 610
[Wed Jun 21 08:31:18.596294 2023] [php:warn] [pid 465319] [client 192.168.151.38:62465] PHP Warning:  Undefined array key "changepwd" in /var/www/grr/include/session.inc.php on line 669
[Wed Jun 21 08:31:18.597377 2023] [php:warn] [pid 465319] [client 192.168.151.38:62465] PHP Warning:  Undefined array key "changepwd" in /var/www/grr/include/session.inc.php on line 747

```

**Lorsque je me déconnecte et que je tente une connexion avec l'administrateur local, j'obtiens une page blanche et ces message d'erreur.
Clic sur "Ouvrir une session" :** 
`[Wed Jun 21 08:32:31.008035 2023] [php:warn] [pid 465233] [client 192.168.151.38:62485] PHP Warning:  Undefined variable $gcDossierImg in /var/www/grr/login.php on line 166, referer: http://SITE_GRR.FR/grr/logout.php?auto=0`

**Saisie des identifiants et clic sur "Valider"**
```
[Wed Jun 21 08:33:32.914284 2023] [php:warn] [pid 462406] [client 192.168.151.38:62491] PHP Warning:  Undefined variable $nbMaxJoursLogEmail in /var/www/grr/login.php on line 142, referer: http://SITE_GRR.FR/grr/login.php
[Wed Jun 21 08:33:32.914409 2023] [php:error] [pid 462406] [client 192.168.151.38:62491] PHP Fatal error:  Uncaught Exception: Unknown or bad format (PD) in /var/www/grr/include/functions.inc.php:5972\nStack trace:\n#0 /var/www/grr/include/functions.inc.php(5972): DateInterval->__construct()\n#1 /var/www/grr/login.php(142): nettoieLogEmail()\n#2 {main}\n  thrown in /var/www/grr/include/functions.inc.php on line 5972, referer: http://SITE_GRR.FR/grr/login.php

```
Une idée d'où pourrait venir le problème ?

Merci encore pour votre aide.

**Comment by plegrand1** [comment]
> Bonjour, la procédure de mise à jour est décrite dans le fichier install.txt, mais comme je vous le disais précédemment, je préfère faire une installation neuve puis restaurer les anciennes données et terminer par la mise à jour de la base lorsque Grr le demande. Cordialement, YN

Du coup 
vous supprimez l'ancienne base de données (après l'avoir sauvegardée bien sûr)?
quelle commande utilisez vous pour restaurer la base une fois les fichiers copiés?

**Comment by ynaessens** [comment]
Deux points :
- d'après votre premier message, vous avez tenté l'installation de GRR 4.0.3 et il reste des erreurs. Merci pour votre retour, j'essaie d'en analyser la cause.
- pour la mise à jour, si vous gardez le même nom de base, l'installation nettoie les données ; il faut donc faire une sauvegarde auparavant ! Donc, je récapitule : 1. je fais une sauvegarde des données depuis l'ancienne installation ; 2. je fais l'installation de la nouvelle version soit dans un nouveau dossier, soit dans le même dossier après l'avoir vidé ; 3. je me connecte en administrateur sur la nouvelle version et je restaure les données précédemment sauvegardées ; 4. je me reconnecte en administrateur (avec le couple login:mot_de_passe de l'ancienne version), alors GRR doit constater que les données ne sont pas à jour et demande à mettre à jour la base de données, ce que j'accepte. Finalement, GRR doit être à jour, la base également, et GRR doit être fonctionnel :-)

Pour ce qui est des erreurs que vous avez rapportées, les dernières corrections apportées à la branche 3.5.1, récupérables ici https://github.com/JeromeDevome/GRR/tree/2cf10dc75b2fa70e215fde97b46c4be4c1ec9ef3, devraient les avoir corrigées.
Si vous confirmez, je pourrais publier une sous-version corrective.
D'avance merci pour votre retour,
cordialement,
YN

**Comment by plegrand1** [comment]
Vous me conseillez donc de refaire une installation vierge mais avec la version 3.5.1 plutôt que la version 4.0.3 ?

**Comment by ynaessens** [comment]
Je suis plus confiant dans les fichiers correspondants au lien donné, car sur la branche master je ne sais pas où vous orienter vers une version fiable.
Pour l’étape 3 : normalement après l’étape 2, vous avez un Grr fonctionnel avec juste un domaine et une ressource. Connecté en administrateur, vous allez vers la page de gestion des sauvegardes et vous restaurez la sauvegarde faite au 1.

**Comment by plegrand1** [comment]
Je comprends que la sauvegardes des données aurait dû être faite depuis l'interface web de GRR en tant qu'administrateur.
Or dans l'état actuel des choses, je ne suis plus en mesure de me connecter en tant qu'administrateur et les seules sauvegardes en ma possession sont celles faites via une crontab et la commande suivante:
mysqldump -u USER -p"PASSWORD" --add-drop-table -c grr > grr.sql
Une idée de comment m'en sortir du coup ?
Désolé

**Comment by plegrand1** [comment]
Du coup je repars sur une installation totalement vierge
Je me connecte une première fois en Admin
Puis depuis phpmyadmin ou autre, j'importe ma vielle base?

**Comment by plegrand1** [comment]
Lors de la nouvelle installation, je reste bloqué sur ce message et il ne se passe rien d'autre : 
Quatrième étape : Création des tables de la base

**Comment by plegrand1** [comment]
Le message précédent était visiblement dû au fait d'une incompréhension par rapport au préfix.
Ensuite j'ai importé l'ancienne base avec "Adminer"
Mise à jour depuis grr
Tout semble fonctionner

Juste une interrogation sur le fait qu'il faille s'authentifier 2 fois pour le dépôt d'un cookie

Sinon tout semble fonctionner avec la version préconisée plus haut

Merci pour vos aides !!
Pascal

**Comment by ynaessens** [comment]
En principe la double authentification n’est requise que lors de la première connexion sur base Grr. Pour les connexions LDAP, il ne devrait pas y avoir de problème.
C’est lié au changement de codage des mots de passe dans la BDD.
