### ISSUE TITLE
Affichage du menu de gauche

### ISSUE THREAD

**Issue by remyd1** [JeromeDevome/GRR#28]
Il serait intéressant de pouvoir avoir le menu de gauche en vue par défaut, plutôt qu'avoir à cliquer sur "Afficher le menu à gauche" à chaque fois, en particulier pour les réservations de longues durées ( > 1 jour).

**Comment by ynaessens** [comment]
bonjour,
si j'ai bien compris la question, cela peut se régler en page de configuration générale.
