### ISSUE TITLE
Affichage de "Mes réservations"

### ISSUE THREAD

**Issue by Larsene** [JeromeDevome/GRR#281]
**Décrivez le bogue**
en passant dans "Mon compte" puis "Mes réservations" (sachant que je n'en ai jamais faites), j'ai ce message d'erreur qui apparaît : 

Version de GRR : 4.1.0

`Fatal error: Uncaught Symfony\Polyfill\Intl\Icu\Exception\MethodArgumentValueNotImplementedException: The Symfony\Polyfill\Intl\Icu\IntlDateFormatter::__construct() method's argument $locale value 'fr-fr' behavior is not implemented. Only the locale "en" is supported. Please install the "intl" extension for full localization capabilities. in /home/ccps/webapps/grr/vendor/symfony/polyfill-intl-icu/IntlDateFormatter.php:148 Stack trace: #0 /home/ccps/webapps/grr/include/language.inc.php(311): Symfony\Polyfill\Intl\Icu\IntlDateFormatter->__construct('fr-fr', 0, 0, NULL, NULL, 'cccc' 'dd' 'LLL...') #1 /home/ccps/webapps/grr/include/language.inc.php(332): date_formatter_intl('%A %d %B %Y', '1689328800', 'fr-fr') #2 /home/ccps/webapps/grr/include/functions.inc.php(4485): utf8_strftime('%A %d %B %Y', '1689328800') #3 /home/ccps/webapps/grr/compte/modeles/mesreservations.php(67): describe_span('1689328800', '1689336000', '%A %d %B %Y') #4 /home/ccps/webapps/grr/compte/modeles/mesreservations.php(47): MesReservations::reportone(A in /home/ccps/webapps/grr/vendor/symfony/polyfill-intl-icu/IntlDateFormatter.php on line 148`

**Comment by ynaessens** [comment]
Bonjour,
avez-vous installé le module intl comme indiqué dans install.txt ?
Cordialement,
YN
