### ISSUE TITLE
MAJ de 3.5.1 vers 4.1.0

### ISSUE THREAD

**Issue by nderambure** [JeromeDevome/GRR#283]
Hello et merci pour ce projet.

Je ne trouve nulle part la procédure de mise à jour à suivre pour passer de la version 3.5.1 à la 4.1.0.
La doc sur la mise à jour date de la version 2 et est obsolète, et je me demandais ce qu'il fallait modifier pour mettre à jour sans embûches.

Merci !

**Comment by ynaessens** [comment]
Bonjour,
je n’ai pas encore mis au point le script de mise à jour de 3.5.1 vers 4.1.0.
En procédant comme indiqué dans le fichier install.txt, vous aurez peut-être un Grr 4.1.0 fonctionnel.
Quelle est votre motivation pour passer en 4.1.0 ?
Cordialement,
YN

**Comment by nderambure** [comment]
Ok merci, mais est ce que la base de données a besoin d'une MAJ aussi et du coup est-ce pris en compte par l'update ?

**Comment by ynaessens** [comment]
Bonjour,
s'il y a une discordance entre la version installée et la version de la BDD, le script de login le détecte et vous envoie vers la page de mise à jour.
La migration v3.4.3 -> v4.0.3 a été testée, mais pas v3.5.1 -> v4.x.y, donc, si vous voulez tester et ainsi contribuer à la stabilisation de GRR, vous êtes bienvenu.
Cordialement,
YN
