### ISSUE TITLE
4.1.0 : pas possible de supprimer des utilisateurs depuis l'administration

### ISSUE THREAD

**Issue by xillibit** [JeromeDevome/GRR#285]
**Décrivez le bogue**
pas possible de supprimer des utilisateurs depuis l'administration de GRR 4.1.0

**Infos GRR**
Version de GRR : 4.1.0
Version PHP : 8.0.29
Problème suite à une installation ou mise à jour : 

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans l'administration
2. Cliquez sur utilisateurs et accès puis utilisateurs
3. Cliquer sur l’icône rouge avec la corbeille 
4. L’utilisateur n'est pas supprimé

**Comportement attendu**
Pouvoir supprimer des des utilisateurs depuis l'administration

**Captures d'écran**
![image](https://github.com/JeromeDevome/GRR/assets/876395/118363d3-01ac-486f-bf3d-00c3c7eb422a)

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 11
  - Navigateur [par ex. chrome, safari] : edge
  - Version [par ex. 22] : 114.0.1823.82

**Comment by JeromeDevome** [comment]
Bonjour,
Je viens de faire un commit ( e540c441 ) qui résout le problème. Il serra dans la version 4.1.1 qui arrive soit aujourd'hui soit dans les prochains jours.

**Comment by JeromeDevome** [comment]
La version 4.1.1 est disponible.
