### ISSUE TITLE
L'utilisateur extérieur n'apparait pas dans la fenêtre popup lorsque le mail d'envoi automatique est activé

### ISSUE THREAD

**Issue by Aurely9n** [JeromeDevome/GRR#286]
**Décrivez le bogue**
Un utilisateur extérieur enregistré n'apparait pas dans la fenêtre popup lorsque le mail d'envoi automatique est activé dans la partie administration. Si c'est un utilisateur de la table "_utilisateur", il n'y a pas de problème.
Après investigation, il semble que le problème viennent de la fonction "encode_adresse" du fichier "function.inc.php" (ligne 5291) qui ne renvoie aucune information à afficher.
Et effectivement, je n'ai pas trouvé où est définie cette fonction dans les fichiers "*.js" du dossier "GRR/js/".

Cordialement,

**Infos GRR**
Version de GRR : 4.1.0
Version PHP : 7.2.34-38

**Comment by JeromeDevome** [comment]
Bonjour,
Merci @Aurely9n , pour les remontés des problèmes, cela permet pour nous de corriger GRR.

J'ai corrigé dans le commit (4814bfcf) , sera incorporé dans la version 4.1.1

**Comment by Aurely9n** [comment]
Pas de souci, pour les retours.
Nous utilisons activement ce système donc plus il est performant et stable mieux c'est pour nous (bref, ce n'est pas totalement désintéressé). Merci pour la correction.
J'avoue que je n'étais pas sûr qu'on pouvait se passer de la protection de l'adresse mail via un évènement JavaScript (pour éviter les bots), à ce niveau. Mais c'est probablement paranoïaque de ma part de penser qu'un bot peut aller chercher les informations en allant directement sur "view_entry" et en poussant les infos "onclick de "a.lienCellule".

Merci encore pour votre rapidité.

**Comment by JeromeDevome** [comment]
Il faudrait déjà laissé en visu au public les infos des réservations.
