### ISSUE TITLE
Section "Formulaire de contact pour réservation" ne s'enregistre pas.

### ISSUE THREAD

**Issue by AdraKK67** [JeromeDevome/GRR#289]
**Décrivez le bogue**
Dans Configuration Général, Onglet Apparence, Section Formulaire de contact pour réservation. Le changement de paramètre est impossible. En effet, après avoir modifié et enregistré les paramètres de cette section ils reviennent à leur état initial. 
Pour contourner le problème j'ai édité la base de donnée à la main ce qui à fonctionné.

**Infos GRR**
Version de GRR : 4.1.1
Version PHP : 8.2.8 *
Apache2 sur Debian 11
Problème suite à une installation ou mise à jour : Dès l'installation

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans 'Administration'
2. Cliquez sur 'Configuration Général'
3. Cliquez sur l'onglet Apparence
4. Tenter de changer des paramètres de la section Formulaire de contact pour la réservation.

**Comportement attendu**
Les nouveaux paramètres devraient être enregistrés

**Captures d'écran**
<img width="509" alt="Capture d'écran 2023-08-01 153405" src="https://github.com/JeromeDevome/GRR/assets/127782400/93b34135-ed0b-4f2a-ac0d-6efe6c6a1bcb">

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : windows 11
  - Navigateur Chrome
  - Version 115

**Comment by JeromeDevome** [comment]
Bonjour, je n'ai pas réussi à reproduire le problème, mais une incohérence a était corrigé en 4.2.0.

Merci d'avance pour votre retour.
