### ISSUE TITLE
un administrateur de site ne peut pas créer de domaine et des ressources dans le site 

### ISSUE THREAD

**Issue by nico-opp** [JeromeDevome/GRR#294]
**Décrivez le bogue**
un administrateur de site ne peut pas créer de domaine et des ressources dans le site  --> Accès refusé 
**Infos GRR**
Version de GRR : v4.1.1
Version PHP : 8.1.23
Problème suite à une installation ou mise à jour : 
problème sur plusieurs instances GRR  
**Reproduire**
Étapes pour reproduire le comportement :
1. En tant qu'administrateur de site 
2. Cliquez sur ajouter un domaine sur le site concerné 
3. compléter le formulaire puis cliquer sur le bouton sauvegarder 
4. Voir l'erreur

pour les ressources:
1. En tant qu'administrateur de site 
2. Cliquez sur ajouter une ressource  sur un domaine existant du site 
3. Voir l'erreur

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10
  - Navigateur Chrome
  - Version 116

**Comment by ynaessens** [comment]
Ce commit https://github.com/JeromeDevome/GRR/commit/6186b4fac22a6119c8505abb8d01f2b8f673357d semble résoudre le problème que vous souleviez. À considérer comme un patch car je trouve que cette page a besoin d'un toilettage ;-)
Merci de confirmer son efficacité.
Cordialement,
YN

**Comment by nico-opp** [comment]
çà fonctionne pour l'ajout de domaine mais pas pour l'ajout de ressource dans ce domaine

**Comment by ynaessens** [comment]
Ah oui, j'aurais dû lire votre message plus attentivement. Désolé.
Ce commit https://github.com/JeromeDevome/GRR/commit/2b3b58c3baa8dd38c83932a9db2405f30f3355a4 devrait répondre à la question.
Merci pour vos retours et votre patience.
Cordialement,
YN

**Comment by nico-opp** [comment]
Effectivement tout est OK desormais . Grand merci @ynaessens !
