### ISSUE TITLE
SSO Microsoft / OpenID OAuth2.0

### ISSUE THREAD

**Issue by zpaul91** [JeromeDevome/GRR#296]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Ajouter la prise en charge du OAuth2.0 de Microsoft

**Décrivez la solution que vous souhaitez**
Pouvoir se connecter avec le SSO Microsoft 

**Décrivez les alternatives que vous avez envisagées**
Remplacement du LDAP 

**Contexte supplémentaire**
Ajoutez ici tout autre contexte ou capture d'écran concernant la demande de fonctionnalité.

**Comment by ynaessens** [comment]
Bonjour,
je n'ai aucune idée de comment s'identifier via Oauth2 de Microsoft.
Si vous voulez contribuer : insérer le code convenable dans session.inc.php.
L'idéal serait de repartir de zéro et de modulariser l'authentification de GRR. Là aussi, si vous avez la possibilité de contribuer, vous êtes bienvenu.
Cordialement,
YN
