### ISSUE TITLE
Fonctionnalité participant en tant que visiteur impossible.

### ISSUE THREAD

**Issue by cyrzero** [JeromeDevome/GRR#298]
**Décrivez le bogue**
Les visiteurs ne peuvent pas cliquer sur une réservation pour s'inscrire.
On ne peut donc pas activer le droit : Qui peut utiliser la fonctionnalité "participant" : "même en simple visiteur"

**Infos GRR**
Version de GRR : 4.1.1
Version PHP : 7.4
Problème suite à une installation ou mise à jour : Non

**Reproduire**
Étapes pour reproduire le comportement : 
1 - ajouter un visiteur et lui donner l'accès restreint du domaine.
2 - configurer le domaine et la ressource pour que les visiteurs puissent participer même s'ils sont visiteurs.
3 - Accéder avec le compte du visiteur et cliquer sur une réservation avec de la place disponible.
4 - le visiteur ne peut pas cliquer sur la réservation et donc ne peut pas s'inscrire. 

En contournement, j'ai dû passer mes utilisateurs en "usagers" mais définir au niveau du domaine zéro réservation possible pour les utilisateurs (hors gestionnaires). Mais ceux-ci peuvent ajouter des réservations sur un autre domaine public...  

**Comportement attendu**

Les visiteurs peuvent cliquer sur la réservation en tant que visiteur et s'inscrire sans avoir les droits d'ajouter des réservations.
Je me suis peut-être trompé dans le paramétrage du domaine, mais je pense avoir retourné toutes les configurations possibles... 

Merci !!

**Comment by JeromeDevome** [comment]
Bonjour, je viens de corriger 6497f9ad , la correction sera dans la version 4.2.2. Disponible certainement demain.
