### ISSUE TITLE
Affichage cassée apres migration version

### ISSUE THREAD

**Issue by Chico0008** [JeromeDevome/GRR#301]
**Décrivez le bogue**
Apres migration d'une ancienne 1.9.7 vers une 4.1.1, l'affichage est complètement cassé
j'ai beau changer le thème, ca ne change rien a l'affichage.

**Infos GRR**
Version de GRR : 4.1.1
Version PHP : 8.1.2
Problème suite à une installation ou mise à jour : aucune lors de la migration des données
le menu, qu'il soit afficher en haut ou sur le coté, prend énormément de place, 
et meme si on decide d'afficher sous forme de liste déroulante, ca reste avec tout directement affiché.

**Comportement attendu**
Affichage correcte, voir les captures.

**Captures d'écran**
Version actuelle
![avant](https://github.com/JeromeDevome/GRR/assets/58886243/74398455-27e0-4a44-8e34-e9be68e4454d)
apres migration
![apres](https://github.com/JeromeDevome/GRR/assets/58886243/e190d3ca-fc43-4fca-8a12-352a3022b465)

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10
  - Navigateur : Chrome et Edge

**Comment by ynaessens** [comment]
Bonjour,
avec les fichiers à jour de ce commit https://github.com/JeromeDevome/GRR/tree/c38afec43592b35dc381191997bb9259d0efc66c
et avec les listes déroulantes, j'ai un affichage raisonnablement compact.
Cordialement,
YN

**Comment by Chico0008** [comment]
Ok, ca marche

par contre y'a t'il possibilité de forcer l'affichage en menu deroulant pour tout les utilisateurs ?
car actuellement je l'ai fait pour l'admin, mais mon profil a moi par exemple avait garder un reglage d'affichage en arborescence, qui prenait de la place.

autre point : sur la 1.9, les elements d'inventaire, meme en arborescence etaient afficher sur 3 colonnes, ici c'est toujours sur 1 seul, d'ou le gros pavé pris quand le menu est au dessus, pas de possibilité de personnalisé nous meme pour remettre les item sur 3 colonnes, et que ca prenne moins de place ?

**Comment by ynaessens** [comment]
Bonjour,
les choix individuels l'emportent toujours sur le choix par défaut défini par l'administrateur.
Pour ce qui est de l'affichage en arborescence, il faudrait voir le code de la page de la v1.9.7 et le comparer avec celui de la v4.1.1 : il doit manquer un <div> ou autre balise.
Cordialement,
YN
