### ISSUE TITLE
Incohérence entre l'information affichée sur la page d'accueil et le contenu réel du tableau de bord.

### ISSUE THREAD

**Issue by SiRiLiS** [JeromeDevome/GRR#303]
**Décrivez le bogue**
Lors de l'utilisation de l'interface d'administration de GRR, un souci d'affichage est survenu. Sur la page d'accueil, il est clairement indiqué que "2 réservations à modérer" sont en attente. Cependant, lorsqu'on accède au tableau de bord administrateur pour modérer ces réservations, aucune réservation à modérer n'apparaît. Ceci crée une incohérence entre l'information affichée sur la page d'accueil et le contenu réel du tableau de bord.

**Infos GRR**
Version de GRR : : 4.1.1 - Release-v4.1.1
Version PHP : 7.4.33
Problème suite à une installation ou mise à jour : non

**Captures d'écran**
Le cas échéant, ajoutez des captures d'écran pour aider à expliquer votre problème.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : tous
  - Navigateur [par ex. chrome, safari] : tous
  - Version [par ex. 22]: toutes
![Selection_092](https://github.com/JeromeDevome/GRR/assets/69196348/d16c1987-2f2e-4cd9-9f09-a1f090b4be7c)

**Comment by JeromeDevome** [comment]
Bonjour,
Cela ce produit sur des réservations supprimées ?

**Comment by SiRiLiS** [comment]
Bonjour,
justement on retrouve pas la reference aux reservations en attente de moderation. il y a un moyenne de le retrouvé meme dans la bdd?

**Comment by JeromeDevome** [comment]
Bonjour,
Après avoir testé sur une de mes bases en effet le compteurs est erroné quand des réservations sont supprimés.

Voici la correction : 93b20ddb , elle serra livrée avec la version 4.2.0

**Comment by SiRiLiS** [comment]
Merci beaucoup!
