### ISSUE TITLE
En version 3.3.1, le passage au mois suivant change l'affichage

### ISSUE THREAD

**Issue by AndrewHobson** [JeromeDevome/GRR#304]
**Décrivez le bogue**
Avec la version 3.3.1 de Grr, lorsque je clique sur le bouton pour passer au mois suivant, l'affichage change. Il n'y a plus le descriptif des ressources ni les " + " qui s'affichent pour créer des nouvelles réservations.
Par contre de cliquer sur le bouton pour passer à la journée suivante, ça fonctionne. L'affichage respecté.

**Infos GRR**
Version de GRR : 3.3.1
Version PHP :   5.5.9-1
Problème suite à une installation ou mise à jour : Non

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans L'affichage de la journée courante
2. Cliquez sur Bouton pour passer au mois suivant
4. Voir l'erreur => Il n'y a plus les + pour ajouter des réservations ni le descriptif des ressources.

**Comportement attendu**
Conserver le même affichage.
Ceci fonctionne si on passe au jour suivant.

**Captures d'écran**
Le cas échéant, ajoutez des captures d'écran pour aider à expliquer votre problème.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS :  Le serveur est un Linux chamilo-HP-Compaq 3.19.0-68-generic #76~14.04.1-Ubuntu
  Le poste client est un Windows 10
  - Navigateur Firefox  
  - Version 118.2

Est-ce que ceci est corrigé dans les versions suivantes ? Si oui, à partir de laquelle ?

Je sais... je dois mettre à jour mon serveur et mon PHP avant de pouvoir passer à la suite !

**Comment by ynaessens** [comment]
Bonjour,
la version 3.3.1 n'est plus maintenue.
Selon la configuration serveur que vous décrivez, il faudrait essayer, mais sans garantie, les versions 3.5.1, sinon 3.4.3, sachant que les plus récentes sont les mieux sécurisées. Les versions 4 ne passeront pas, à coup sûr.
Le mieux serait quand même de mettre php à jour.
Merci de nous faire part de votre réussite :-)
Cordialement,
YN
