### ISSUE TITLE
who_can_book dans 4.1.1 ? 

### ISSUE THREAD

**Issue by SiRiLiS** [JeromeDevome/GRR#306]
**Décrivez le bogue**
Dans la version 3.x, il y avait, dans la partie admin, la possibilité de gérer la valeur dans la BDD "who_can_book". Sauf erreur de ma part, je ne la trouve pas dans la version 4.1.1.

**Infos GRR**
Version de GRR :4.1.1 - Release-v4.1.1
Version PHP : 7.4.33

Merci.

**Comment by JeromeDevome** [comment]
Bonjour,
Pouvez-vous êtes plus précis, sur ce qu'il y avait et à quel endroit ? Merci

**Comment by JeromeDevome** [comment]
Bonjour,
Je viens de porter les modifications sur GitHub, la fonction sera certainement disponible en version 4.3.0.

**Comment by fabboyrie** [comment]
Bonjour,

Nous venons de mettre à jour un GRR de 3.5 vers 4.2.2. La nouvelle version apporte un rafraichissement bienvenu. Mais le fait ne pas pouvoir autoriser la réservation seule sur les ressources restreintes est très handicapante pour notre utilisation.

 Je vois qu'il y a un commit
 https://github.com/JeromeDevome/GRR/commit/d065d1fab4bfdc45014cae8933192b3c4314151f qui remet la fonction.
Est-ce que l'on peut l'appliquer sans danger sur la 4.2.2 ou sinon quand peut-on espérer la sortie de la 4.3.0

Merci d'avance

**Comment by JeromeDevome** [comment]
Bonjour,
Si j'ai le temps, je fais une version Beta de la 4.3 ce week-end

**Comment by JeromeDevome** [comment]
Bonjour,
https://github.com/JeromeDevome/GRR/releases/tag/v4.3.0-RC1

Comme toute version RC , je vous conseil de la tester sur un environnement de test.
