### ISSUE TITLE
Erreurs chargement fichiers JS sur la 4.2.1 et problème enregistrement des bénéficiaires extérieurs sur un réservation.

### ISSUE THREAD

**Issue by Aurely9n** [JeromeDevome/GRR#315]
Bonjour,
Je viens d'installer la nouvelle version de GRR 4.2.1 pour test et je suis tombé un souci et une interrogation...
En essayant d'ajouter un bénéficiaire extérieure à ma réservation, le champs "email bénéficiaire" pose un problème à l'affichage.
L'erreur vient de la ligne 160 du fichier "edit_entry.php" :
`placeholder="'.get_vocab("email beneficiaire").'"`
Ici la fonction ne peut pas traduire la valeur "Email bénéficiaire" car elle n'existe pas dans le fichier de lang fr (c'est l'entrée "**email_beneficiare**" avec underscore qui existe).

De plus, des fichiers JS sur cette même page ne peuvent pas être chargés car ils n'existent pas. Entre les lignes 80 et 83 du même fichier (edit_entry.php):
```
<script src="./js/clock_'.$locale.'.js"></script>
<script src="./js/select2.min.js"></script>
<script src="./js/select2_locale_fr.js"></script>
<script src="./js/bandeau.js"></script>
```
Or la variable "$locale" est "fr_fr" et donc, le serveur essaye de charger "./js/clock_fr-fr.js" qui n'existe pas. Comme "./js/bandeau.js" n'existe pas non plus dan le dossier.

Enfin, le fait d'avoir intégré le code du header en dur dans le fichier "edit_entry.php" et le chargement du block bénéficiaire extérieur dans le fichier "edit_entry.php" semble s'éloigner de la manière "historique" de codage de cette page et de ces fonctionnalités. Avant, le header était chargé via la fonction "pageHead2" du fichier "include/function.inc.php" et le block "bénéficiaires extérieurs" via le fichier "edit_entry_beneficiaire.php".
Est-ce que c'est un choix de direction pour les prochaines évolutions de GRR ?

Bien à vous,

**Infos GRR**
Version de GRR : **4.2.1**
Version PHP :   #**8.2.12**

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre retour.
Je suis passé à côté de ces erreurs.
La modification du code a été motivée par des lenteurs pénalisantes lors du chargement de la page dues aux appels AJAX à edit_entry_beneficiaire entre autres.
Pour ce qui est du header, il est vraisemblable qu'un peu de nettoyage sera fait dans d'autres pages.
Cordialement,
YN

**Comment by ynaessens** [comment]
Ce fichier modifié https://github.com/JeromeDevome/GRR/commit/db91d125dcb3045eb4018ff4b73a30f557e1cad2 devrait résoudre les problèmes soulevés.
Cordialement,
YN

**Comment by JeromeDevome** [comment]
Bonjour Yan,
J'avais le commit en attente pour ma part j'avais renommé les fichiers js
![2023-11-29 19_23_25-GitHub Desktop](https://github.com/JeromeDevome/GRR/assets/13278858/d6c6b7c3-c7fc-467b-9b22-7fdd22532ca1)

**Comment by JeromeDevome** [comment]
J'ai appliqué ma méthode qui permet de corriger sur l'ensemble des pages et de plus normalise avec les langues GRR.

**Comment by Aurely9n** [comment]
Bonjour,
Merci beaucoup pour vos retours à tous les deux.
Bien à vous,
