### ISSUE TITLE
Nouvelle réservation - affichage de la périodicité des semaines en anglais

### ISSUE THREAD

**Issue by yangn37** [JeromeDevome/GRR#317]
**Décrivez le bogue**
Affichage partiel en anglais lors de la création d'une nouvelle réservation dans la partie "périodicité"

**Infos GRR**
Version de GRR : 4.2.1
Version PHP : 8.2.13
Problème suite à une installation ou mise à jour :  suite à la mise à jour de grr 3.5.0a à 4.2.1

**Reproduire**
Étapes pour reproduire le comportement :
1. Créer une nouvelle réservation. 
Dans la section périodicité, la section semaine est affiché en anglais

**Comportement attendu**
Lors de la création de la nouvelle réservation la périodicité doit être affiché en français

**Captures d'écran**
![GRR - Reservations - Week](https://github.com/JeromeDevome/GRR/assets/152627539/a1b37256-044a-4a1a-af1f-1ab119bbabef)

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows
  - Navigateur Edge / Firefox
  - Version 119.0.2151.72 / 115.5.0esr

**Contexte supplémentaire**
Ajoutez ici tout autre contexte concernant le problème.

**Comment by JeromeDevome** [comment]
Bonjour le commit 9f963c5b corrige votre problème.
Il y aura probablement une version 4.2.2 ce week-end avec le correctif et bien d'autre.

**Comment by JeromeDevome** [comment]
Version **4.2.2** est mise à disposition, elle corrige le problème signalé.

**Comment by yangn37** [comment]
Bonjour,
Version 4.2.2 implémenté sur le serveur de test, le problème est bien corrigé.
Merci pour la rapidité de correction.
