### ISSUE TITLE
Mails auto smtp

### ISSUE THREAD

**Issue by Birssan** [JeromeDevome/GRR#32]
Bonjour,

Depuis peu, une utilisatrice nous a fait remonter que lors d'une réservation qui est sensée envoyer un mail automatique de récap, elle a un message d'erreur indiquant que la connexion au serveur smtp ne se fait pas.
Ce que je trouve étrange étant donné qu'avant cela semblait fonctionner comme il faut et que le serveur smtp est bien paramétré...

![capture](https://cloud.githubusercontent.com/assets/5689193/19381516/3b6d3efc-91fc-11e6-8eda-dc85ab5ca562.PNG)

J'ai tenté d'aller voir dans le code qui s'occupe des envois de mail étant donné que je développe des appli qui utilise notre serveur smtp en PHP PHPMailer. La seule différence que je voyais était l'utilisation de `SMTPSecure` à `tls` (le port est bien 587), j'ai donc essayé de rajouter ce paramètre mais cela semble plutôt faire planter le chargement de la page lors de la suppression de réservation (qui envoi un mail aussi normalement) ou une nouvelle réservation...

Donc voilà, je suis un peu bloqué.

**Comment by nicolas-san** [comment]
Bonjour, 
je ne suis plus trop dedans, mais ça fonctionnait et d'un coup c'est plus bon ? 
Si le code de grr n'a pas changé, c'est étonnant que ça y soit lié ?

Une mise à jour de php peut être ?

Que disent les logs du serveurs ? (syslog, mail.err, mail.log ?)
As tu testé avec un telnet sur le port 587 directement voir si les accès sont ok ?
Le smtp nécessite une auth ? si oui testes là avec telnet ou bien un client mail

Avec ça déjà ça donnera des pistes :)
