### ISSUE TITLE
Création compte via Imap

### ISSUE THREAD

**Issue by fccl-vandoeuvre** [JeromeDevome/GRR#320]
**Décrivez le bogue**
La création de compte via Imap fonctionne mais ajoute un caractère qui bloque son usage

**Infos GRR**
Version de GRR : V4.2.2
Version PHP : 7.4
Problème suite à une installation ou mise à jour : Non

**Reproduire**
Étapes pour reproduire le comportement :
1. Configurer la connexion à un serveur imap pour les usagers
2. Via un conteneur 2 pour les cookies, créer un compte en utilisant une adresse de messagerie existante sur le serveur
3. Une erreur apparaît sur le navigateur, impossible d’aller plus loin.
4. Retourner dans l’interface d’administration via le conteneur 1
5. Consulter la liste des utilisateurs
6. Constater qu’il y a un @ à la fin de l’adresse de courriel (exemple truc@muche@)
7. Modifier manuellement en supprimant l'@ et en ajoutant nom et prénom car obligatoires
8. Recharger le conteneur de l’usager dans le conteneur 2, il charge une interface consistant à personnaliser son compte.

**Comportement attendu**
Que l’usager puisse lui-même ajouter son nom et prénom.

**Captures d’écran**
Le cas échéant, ajoutez des captures d’écran pour aider à expliquer votre problème.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Xubuntu 20.04
  - Navigateur Mozilla Firefox
  - Version 120

**Comment by JeromeDevome** [comment]
Il semble que le commit 20423113 corrige le problème pour PHP < 8.1.

Je me suis aperçu que la connexion IMAP n'ai pas compatible dans l'état avec PHP 8.1

**Comment by JeromeDevome** [comment]
Je suis allez trop vite....
Nouveau commit corrigeant l'ensemble de la connexion + php 8.1 : 92316373

**Comment by JeromeDevome** [comment]
Corrigé dans la version 4.2.5 et 4.3.1.

**Comment by fccl-vandoeuvre** [comment]
Bonjour,

Merci pour l’intervention. Désolé pour le délai de réponse.

Suite à mise à jour vers la version 4.3.6, nouvelle tentative de connexion à partir d’un serveur IMAP :
L'@ parasite n’est effectivement plus de la partie, cependant l’erreur « 404 Not Found » apparaît toujours lors de la connexion.

Après vérification avec le compte administrateur, les champs Nom et prénom obligatoires sont vides. Lorsque complétés, la connexion est possible.

Si je tente avec un compte inexistant sur le même serveur IMAP, j’ai bien un message d’erreur « Echec de l’authentification IMAP ».

Axel.
