### ISSUE TITLE
erreur lors de l'ajout d'une ressource sur un domaine ( mode multisite )

### ISSUE THREAD

**Issue by nico-opp** [JeromeDevome/GRR#324]
**Décrivez le bogue**
erreur lors de l'ajout d'une ressource sur un domaine ( mode multisite )
**Infos GRR**
Version de GRR : version 4.2.3 et autres version v4 
Version PHP : 8.1.27

Étapes pour reproduire le comportement :
1. Activer le multisite
2. Creer un domaine
3. Creer une nouvelle ressource et cliquer sur 'enregistrer et retour'
4. Erreur: erreur HTTP/2  et la ressource est créée 3 fois 

**Comportement attendu**
Un retour sur la page précédente et la création d'une seule ressource 

**Captures d'écran**
Le cas échéant, ajoutez des captures d'écran pour aider à expliquer votre problème.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10
  - Navigateur Chrome 
  - Version 120

**Comment by JeromeDevome** [comment]
Bonjour,
Je ne reproduit pas le problème.
Chacun de vos sites à bien un code et un nom différents des un et des autres ?

**Comment by JeromeDevome** [comment]
Bonjour,
Pouvez-vous mettre à jour votre GRR en version 4.3.3 et nous dire si le problème est toujours présent ?

Bonne journée.
