### ISSUE TITLE
Upgrade depuis très vieille version

### ISSUE THREAD

**Issue by Yanis-Sauve-CSSDLJ** [JeromeDevome/GRR#325]
Pas un bug en soi, mais j'ai une instance de GRR version 1.9.7e qui aurait grandement besoin d'un upgrade.

Quel serait le meilleur upgrade path pour passer de 1.9.7e à la dernière, selon le concepteur?

**Infos GRR**
Version de GRR :  1.9.7e
Version PHP :  8.2.4
Problème suite à une installation ou mise à jour :  Aucun, en planification
Plateforme: Windows Server 2016, IIS

**Comment by JeromeDevome** [comment]
Bonjour,
Installer la dernière version

http://devome.com/GRR/DOC/installation-et-mise-a-jour/mise-a-jour-depuis-version-less-than-4

**Comment by ynaessens** [comment]
Bonjour,
je vous conseille de suivre les instructions données en fin de fichier install.txt de la branche 3.5.1.
Il est nécessaire de convertir la base de données vers UTF-8.
Bonne réussite !
Cordialement,
YN

**Comment by Yanis-Sauve-CSSDLJ** [comment]
Merci à vous deux.  Le billet peut être fermé.
