### ISSUE TITLE
Champ "Brève description" du tableau des résultats de la section "Recherche & Stat" de la version 4.3.0 de GRR

### ISSUE THREAD

**Issue by Aurely9n** [JeromeDevome/GRR#329]
Bonjour,

Sur la version 4.3.0 de GRR sur la page "Recherche & stats", une modification de la valeur "brève description" dans le tableau des résultats me pose problème. En effet, la valeur retournée est "Réservation n°XXXX" qui est lien qui envoie vers la page "...grr/app.php?p=vuereservation&id=XXXX". Or ce comportement n'est pas très pratique je trouve.
De plus, dans les exports, c'est également cette valeur qui est inscrite dans le fichier mais du coup, nous n'avons plus l'information de la "brève description" enregistrée en DB.

**Décrivez la solution que vous souhaitez**
- Sur la page du navigateur, il faudrait que le lien "Réservation n°XXX" exécute un évènement JavaScript qui ouvre une popup sur ce qui est souhaité (la "p=vuereservation&id=XXXX"). Ou alors n'afficher que la valeur de la "Brève description" de la réservation (sans le lien).
- Dans le fichier exporté, il faudrait uniquement la valeur de la "Brève description" de la réservation

Cordialement,
Aurélien

**Comment by JeromeDevome** [comment]
Bonjour, un effet de la personnalisation en détail de l'affichage. Le commit 1c59567c corrige le problème une version comportant ce commit arrive rapidement.

**Comment by JeromeDevome** [comment]
Corrigé dans la version 4.3.1
