### ISSUE TITLE
Bouton enregistrer absent 

### ISSUE THREAD

**Issue by FredHilbert** [JeromeDevome/GRR#33]
Bonjour à tous,
après une installation assez facile, je suis bloqué pour configurer l'onglet contenu/apparence. Contrairement aux autres pages, je n'ai pas de bouton enregistrer.
Je précise que pour passer l'étape 4 de l'installation et contourner l'erreur j'ai du modifier la date par défaut 0000-00-00 par 2016-01-01 dans le fichier tables.my.sql sinon ça ne passait pas.
http://imgur.com/MNPLjDI
Pas sûr qu'il y ait un rapport mais l'onglet contenu/apparence s’arrête justement à ça:
http://imgur.com/0cPCdAZ 

Merci d'avance pour votre aide.

Version de GRR : GRR3.1.0 RC
Hébergement : interne
Version PHP : 7.0.8-0ubuntu0.16.04.3

**Comment by JeromeDevome** [comment]
Bonjour,

Normalement en bas à droite.

 

Cordialement,

Le support

 

http://devome.com/

 

De : FredHilbert [mailto:notifications@github.com] 
Envoyé : dimanche 20 novembre 2016 17:49
À : JeromeDevome/GRR <GRR@noreply.github.com>
Objet : [JeromeDevome/GRR] Bouton enregistrer absent (#33)

 

Bonjour à tous,
après une installation assez facile, je suis bloqué pour configurer l'onglet contenu/apparence. Contrairement aux autres pages, je n'ai pas de bouton enregistrer.
Je précise que pour passer l'étape 4 de l'installation et contourner l'erreur j'ai du modifier la date par défaut 0000-00-00 par 2016-01-01 dans le fichier tables.my.sql sinon ça ne passait pas.
http://imgur.com/MNPLjDI
Pas sûr qu'il y ait un rapport mais l'onglet contenu/apparence s’arrête justement à ça:
http://imgur.com/0cPCdAZ

Merci d'avance pour votre aide.

Version de GRR : GRR3.1.0 RC
Hébergement : interne
Version PHP : 7.0.8-0ubuntu0.16.04.3

**Comment by FredHilbert** [comment]
Merci pour ta réponse Jerome. 

sur les autres onglets j'ai bien le bouton enregistrer. mais pas sur le premier.

Quand je regarde la page admin_config1.php il y a encore pleins de paramètres mais coté client ça s'arrête à:
Début et fin des réservations
Date de début des réservations :	

Comme tu peux le voir sur ce sreenshot, rien de + ne s'affiche.
![capture4](https://cloud.githubusercontent.com/assets/16060531/20465187/cee82304-af57-11e6-97af-9f2c85ba398a.PNG)

**Comment by JeromeDevome** [comment]
Déjà ta première erreur est étrange, j’ai installé énormément de GRR sans avoir ce problème. 

 

Regarde http://mygrr.net/demo3/ 

Login : Administrateur 

MDP : azerty

 

Regarde dans la table config si tu as bien les paramètres de début et fin de réservation.

 

Peux-tu essayer avec un autre navigateur même si j’y crois pas. 

 

Ensuite il faudrait connaitre la config de ton PHP, surement là le problème… Je travaille beaucoup avec la 5.4 et GRR n’est pas testé avec le PHP 7.

 

 

 

Cordialement,

Le support

 

http://devome.com/

 

De : FredHilbert [mailto:notifications@github.com] 
Envoyé : dimanche 20 novembre 2016 19:31
À : JeromeDevome/GRR <GRR@noreply.github.com>
Cc : JeromeDevome <support@devome.com>; Comment <comment@noreply.github.com>
Objet : Re: [JeromeDevome/GRR] Bouton enregistrer absent (#33)

 

Merci pour ta réponse Jerome. 

sur les autres onglets j'ai bien le bouton enregistrer. mais pas sur le premier.

Quand je regarde la page admin_config1.php il y a encore pleins de paramètres mais coté client ça s'arrête à:
Début et fin des réservations
Date de début des réservations : 

Comme tu peux le voir sur ce sreenshot, rien de + ne s'affiche.
 <https://cloud.githubusercontent.com/assets/16060531/20465187/cee82304-af57-11e6-97af-9f2c85ba398a.PNG>

**Comment by FredHilbert** [comment]
La première erreur quelqu'un en parle sur le forum en juin 2016 dans un sujet nommé "Re: ERREUR à la "Création des tables de la base"  D'ailleurs un certain JermoeB (toi?) intervient pour dire: "Bonjour, 
Merci des retours nous corrigeons sa prochainement." 
J'ai déjà essayé avec d'autre navigateur mais le problème est le même.
GRR est sur une fresh install d'Ubuntu 16. Je vais downgrader PHP on verra bien. 
En tout cas merci pour tes réponses et pour GRR évidement :-)

**Comment by FredHilbert** [comment]
avec une install neuve cette fois sous Windows et Wamp j'ai le même problème a l'étape 4. Je sais vraiment pas ce que je fais de travers.
![capture 5png](https://cloud.githubusercontent.com/assets/16060531/20466762/3a5081ce-af79-11e6-9233-9b025e7fcc8d.PNG)

**Comment by JeromeDevome** [comment]
Bon problème de compatibilité SQL, je corrige dans la prochaine version

**Comment by laedo** [comment]
> avec une install neuve cette fois sous Windows et Wamp j'ai le même problème a l'étape 4. Je sais vraiment pas ce que je fais de travers. Par contre après avoir remplacé 0000-00-00 par 2016-01-01 ça passe et cette fois l'onglet config 1 s'affiche en entier.
> 
> Encore merci pour ton aide.
> 
> ![capture 5png](https://cloud.githubusercontent.com/assets/16060531/20466762/3a5081ce-af79-11e6-9233-9b025e7fcc8d.PNG)


To solve this problem you must delete the default value in the START and END field.
example :

START datetime NOT NULL;

**Comment by ynaessens** [comment]
Bonjour,
pouvez-vous préciser avec quelle branche vous avez ce problème ?
Cordialement,
YN

**Comment by anteldan** [comment]
J'ai eu le même type de problème une fois le calendrier des vacances scolaires activé. 
Dans le chargement de la page ça bloque lors de la création de la <select> pour les zones de vacances scolaires.
J'ai installé php-xml et le problème est résolu. 

Les modules suivants ont dû être installé pour que l'appli fonctionne : 
php-mbstring
php-mysqlnd
php-mysql
php-gd
php-json
php-xml




> Merci pour ta réponse Jerome.
> 
> sur les autres onglets j'ai bien le bouton enregistrer. mais pas sur le premier.
> 
> Quand je regarde la page admin_config1.php il y a encore pleins de paramètres en bas de page mais coté client ça s'arrête à:
> Début et fin des réservations
> Date de début des réservations :
> 
> Comme tu peux le voir sur ce sreenshot, rien de + ne s'affiche.
> ![capture4](https://cloud.githubusercontent.com/assets/16060531/20465187/cee82304-af57-11e6-97af-9f2c85ba398a.PNG)
