### ISSUE TITLE
Nettoyage table utilisateurs_groupes après suppression user GRR 4.3.0

### ISSUE THREAD

**Issue by bambi1013** [JeromeDevome/GRR#330]
Bonjour,

**Décrivez le bogue**
Après suppression d'un utilisateur, la table utilisateurs_groupes n'est pas nettoyer. A l'arriver d'un nouvel utilisateur qui poste le même login, il peut se retrouver dans le groupe de l'ancien utilisateur.

**Infos GRR**
Version de GRR : 4.3.0
Version PHP : 8.1.27

Dans le fichier admin/controleurs/admin_user.php
Dans les ligne 60 à 65, il faudrait rajouter 

`grr_sql_command("DELETE FROM ".TABLE_PREFIX."_utilisateurs_groupes WHERE login='$temp'");`

**Comment by JeromeDevome** [comment]
Bonjour, merci pour votre retour, j'ai fais la modification. Commit : bf2156df

**Comment by bambi1013** [comment]
Bonjour, merci pour votre rapidité.
