### ISSUE TITLE
Champ login de la table utilisateurs_groupes GRR 4.3.0

### ISSUE THREAD

**Issue by bambi1013** [JeromeDevome/GRR#331]
Bonjour,

**Infos GRR**
Version de GRR : 4.3.0
Version PHP : 8.1.27

Dans toutes les tables, le champ login est de type VARCHAR(190) sauf dans la table _utilisateurs_groupes

Correction via  ( peut être à rajouter dans la prochaine mise à jour)
`ALTER TABLE `grr_utilisateurs_groupes` CHANGE `login` `login` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;`

Correctif également dans https://github.com/JeromeDevome/GRR/blob/master/installation/tables.my.sql#L66

**Comment by JeromeDevome** [comment]
Bonjour,
Merci pour ce retour, je met cela dans la 4.3.7 - 8f9239d7

**Comment by JeromeDevome** [comment]
Effectif dans la version 4.3.7 qui vient d'être publiée.
