### ISSUE TITLE
Problème édition profil utilisateur GRR 4.3.0

### ISSUE THREAD

**Issue by bambi1013** [JeromeDevome/GRR#332]
**Décrivez le bogue**
Lorsque d'un utilisateur veut modifier son profil pour simplement changer son mot de passe, une erreur SQL apparait :

`Incorrect integer value: '' for column grr4.grr_utilisateurs.default_room at row 1 Q=UPDATE grr_utilisateurs SET default_site = '-1', default_area = '-1', default_room = '', default_style = 'violet', default_list_type = 'item', default_language = 'fr-fr', login='login_user' WHERE login='login_user'`

**Infos GRR**
Version de GRR : 4.3.0
Version PHP : 8.1.27
Problème suite à une installation ou mise à jour : 

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans mon compte
2. Cliquez sur Enregistrer

La valeur de default_room ne semble pas être récupérée dans la page du formulaire de modification.

**Comment by JeromeDevome** [comment]
Le commit f350fb2d doit résoudre le problème

**Comment by bambi1013** [comment]
Bonjour, merci c'est fonctionnel.
