### ISSUE TITLE
Création nouvel utilisateur : paramètres par défault GRR 4.3.0

### ISSUE THREAD

**Issue by bambi1013** [JeromeDevome/GRR#333]
Bonjour,

**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Je ne sais pas si c'est volontaire, c'est pour cela que je l'ai mis dans les suggestions, mais lors de la création d'un nouvel utilisateur, il n'hérite pas des paramètre par défaut de la plateforme.

Par exemple lorsque sur la plateforme on choisi le mode par défaut de l'affichage des domaines et ressources sous forme de menu déroulant, un nouvel utilisateur se retrouve avec un affichage de type bouton.
Il en est de même pour le site, domaine et ressources par défaut.

**Décrivez les alternatives que vous avez envisagées**
Si on souhaite qu'un nouvel utilisateur hérité des paramètres par défaut, je propose la solution suivante :

Dans le fichier admin/controleurs/admin_user_modify.php

Remplacer les lignes 151 à 156 par :

```
						default_style = '',";
                        if ( isset($AllSettings['default_site']) && ! empty($AllSettings['default_site']) )
                            $sql .= "default_site = '".$AllSettings['default_site']."',";
                        else
                            $sql .= "default_site = '-1',";
                        if ( isset($AllSettings['default_area']) && ! empty($AllSettings['default_area']) )
                            $sql .= "default_area = '".$AllSettings['default_area']."',";
                        else
                            $sql .= "default_area = '-1',";
                        if ( isset($AllSettings['default_room']) && ! empty($AllSettings['default_room']) )
                            $sql .= "default_room = '".$AllSettings['default_room']."',";
                        else
                            $sql .= "default_room = '-1',";
                        if ( isset($AllSettings['area_list_format']) && ! empty($AllSettings['area_list_format']) )
                            $sql .= "default_list_type = '".$AllSettings['area_list_format']."',";
                        else
                        $sql .= "default_list_type = 'item',";
                        if ( isset($AllSettings['default_language']) && ! empty($AllSettings['default_language']) )
                            $sql .= "default_language = '".$AllSettings['default_language']."',";
                        else
                            $sql .= "default_language = 'fr-fr',";
```

Je vous joins mon fichier si vous voulez faire un diff dans le cas ou ce correctif vous intéresse.
[admin_user_modify.php.txt](https://github.com/JeromeDevome/GRR/files/14235480/admin_user_modify.php.txt)

**Comment by JeromeDevome** [comment]
Bonjour, c'est à sa première connexion qu'il hérite des paramètres par défaut.

**Comment by bambi1013** [comment]
Bonjour,
Désolé mais je n'ai pas le même comportement.
Après la 1er connexion, dans la table user, la valeur de default_list_type reste à 'item'
Le menu reste donc en mode bouton.

**Comment by JeromeDevome** [comment]
Bonjour,
J'ai corrigé cela 8f9239d7 , disponible prochainement en 4.3.7

**Comment by JeromeDevome** [comment]
Effectif dans la version 4.3.7 qui vient d'être publiée.
