### ISSUE TITLE
Impossible de choisir un site par défaut GRR 4.3.0

### ISSUE THREAD

**Issue by bambi1013** [JeromeDevome/GRR#334]
**Décrivez le bogue**
Le module site est activé. Plusieurs sites sont définis. Dans le panneau d'administration, il n'est pas possible de sélectionner un site par défaut le menu déroulant est vide.

**Infos GRR**
Version de GRR : 4.3.0
Version PHP : 8.1.27

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans configuration / Apparence
2. Cliquez sur le menu déroulant pour sélection un site par défaut

Il me semble qua dans ce Twig :  https://github.com/JeromeDevome/GRR/blob/master/admin/templates/admin_config6.twig#L68

Ligne 68:
il faut remplacer
`{{ trad.optionSite | raw }}`

par
`{{ d.optionSite | raw }}`

Cordialement
Eric

**Comment by JeromeDevome** [comment]
Merci pour votre aide 👍

**Comment by JeromeDevome** [comment]
Bonjour,
La version [4.3.2](https://github.com/JeromeDevome/GRR/releases/tag/v4.3.2) comporte le commit, je vous conseil donc de mettre à jour GRR. 
Je clos le sujet, si la mise à jour ne corrige pas le problème n'hésitez pas le rouvrir.

Bonne journée.
