### ISSUE TITLE
Logo impossible à afficher

### ISSUE THREAD

**Issue by FredHilbert** [JeromeDevome/GRR#34]
Bonjour,
j'ai un problème pour afficher le logo. lorsque je l'upload ça semble fonctionner mais quand je vais voir dans var/www/GRR/images mon logo ne s'y trouve pas. Suite à la lecture e la FAQ et du forum j'ai donc mis le logo manuellement dans ce dossier et donné les droits mais sans résultats. Enfin j'ai vu un autre suggestion qui propose de mettre le chemin du logo dans le table "grr_setting" a la ligne "logo" mais je n'ai pas cette ligne. 
Dernière question, est-il possible e donner les droits de "reservation au nom de" sans donner les droits admin?
encore merci pour votre travail.
Fred

**Comment by JeromeDevome** [comment]
Pour le logo, mettre le dossier image en droit 777

si logo n'existe pas tu peus le créer dans setting.

**Comment by anteldan** [comment]
Vérifie si l'extension php-gd est installée. Dans mon cas (V 3.4.1 avec php 7.3) elle est nécessaire.
Ton image sera transformée par la bibliothèque GD, son nom sera changé et elle sera stockée dans le dossier "images". 
Une ligne sera insérée dans la table `setting`  avec  la valeur "logo" dans la colonne "NAME" et le nom de l'image dans la colonne "VALUE".

Je pense que l'on peut fermer ce bug.
