### ISSUE TITLE
Impossible de supprimer des sites

### ISSUE THREAD

**Issue by olpak7** [JeromeDevome/GRR#340]
**Décrivez le bogue**
Impossible de supprimer des sites sur la page sur la page 
/admin/admin.php?p=admin_site

**Infos GRR**
Version de GRR : 4.3.1
Version PHP : 7.4.33
Problème suite à une installation ou mise à jour : 

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans l'interface d'administration : '.../admin/admin.php?p=admin_site'
2. Cliquez sur sur le bouton supprimer pour n'importe qu'elle site
3. une modal s'affiche. Cliquer sur "supprimer"
4. la page recharge mais aucun site de supprimé

Je ne suis pas expert en JS, mais a priori, le soucis est résolu en modifiant le fichier admin_site.twig:
l.76  :  var $target = $(e.target);   => var $target = $(e.currentTarget);

l. 78 : var modalSelector = $target.data('target');  => var modalSelector = $target.data('bs-target');

**Comment by JeromeDevome** [comment]
Bonjour merci pour l'info le commit 2ad69eb6 doit corriger votre problème.

Je n'ai pas testé votre solution, je me suis basé sur les autres modal, je pense que s'est du au changement de version de bootstrap entre temps dans le développement...

**Comment by JeromeDevome** [comment]
Bonjour,
La version [4.3.2](https://github.com/JeromeDevome/GRR/releases/tag/v4.3.2) comporte le commit, je vous conseil donc de mettre à jour GRR. 
Je clos le sujet, si la mise à jour ne corrige pas le problème n'hésitez pas le rouvrir.

Bonne journée.
