### ISSUE TITLE
Type par défaut d'un domaine non pris en compte (GRR4.3.1)

### ISSUE THREAD

**Issue by NHtoul** [JeromeDevome/GRR#342]
Bonjour,

**Décrivez le bogue**
Le type de réservation par défaut n'est pas pris en compte.

**Infos GRR**
Version de GRR : 4.3.1
Version PHP :8.2
Problème suite à une installation ou mise à jour :  rencontré après migration depuis la 3.

**Reproduire**
Étapes pour reproduire le comportement :
Dans le paramétrage des types ressources, on peut affecter un type par défaut.
Lors de la réservation d'une ressource, le type par défaut n'est pas affiché, 
Le bouton "Définir par défaut" lorsqu'on est administrateur,  pour définir ce type par défaut n'a également aucun effet.

J'ai testé de désactivé / réactivé sur un autre type, sans succès.
Problème rencontré quelque soit le navigateur utilisé.

**Comportement attendu**
Dans la liste déroulante, le typage par défaut et sensé être présélectionné.

Il n'y a aucun message d'erreur.

Cordialement,
NH

**Comment by JeromeDevome** [comment]
Je ne suis pas sur de comprendre, ou définissez vous exactement le type par défaut ?

On parle bien de Types de réservation ?

**Comment by NHtoul** [comment]
Bonjour, 
Je l'ai configure dans la gestion des domaines : 
![image](https://github.com/JeromeDevome/GRR/assets/161016066/44ef3ac1-1df4-4c43-aa93-347439fd1bb7)
![image](https://github.com/JeromeDevome/GRR/assets/161016066/efa53374-56ac-4915-aaf1-fa90dd977f63)


Et quand on réserve une ressource :
![image](https://github.com/JeromeDevome/GRR/assets/161016066/86ee4fe2-30bb-46e9-a84b-1d56f93a271c)

**Comment by JeromeDevome** [comment]
Bonjour, le commit 9cd84b08 devrait résoudre ce problème.

**Comment by NHtoul** [comment]
Merci, c'est résolu.
