### ISSUE TITLE
Aucune ressource n'est définie pour ce domaine.

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#343]
Version de GRR : 4.3.1
Version PHP : 7.4.33
Problème suite à une installation ou mise à jour : mise à jour

Bonjour,

Quand un utilisateur fait une réservation puis la supprime, cela me retourne : 

"Aucune ressource n'est définie pour ce domaine."

Cela à quand même supprimé la réservation, mais le fais de retourner au planning défini cela et un peu chiant pour les utilisateurs.

Avez-vous une idée ?

**Comment by JeromeDevome** [comment]
Bonjour, le commit 294971f2 doit résoudre le problème.

**Comment by JeromeDevome** [comment]
Bonjour,
La version [4.3.2](https://github.com/JeromeDevome/GRR/releases/tag/v4.3.2) comporte le commit, je vous conseil donc de mettre à jour GRR. 
Je clos le sujet, si la mise à jour ne corrige pas le problème n'hésitez pas le rouvrir.

Bonne journée.

**Comment by SteBoun** [comment]
Bonjour,

J'ai fait la mise à jour 4.3.2 et le problème est toujours là. 
J'ai remarqué que quand on supprime une réservation, GRR ajoute une apostrophe sur le champ URL à la fin.
Quand je supprime l'apostrophe, cela revient à la normale.

Y a-t-il pas un lien ?

**Comment by ynaessens** [comment]
Bonjour,
il y avait bien une apostrophe en trop, mais cela ne me provoquait pas d'erreur...
j'ai quand même corrigé le code https://github.com/JeromeDevome/GRR/commit/692699355fa69ef9e1bb4332b820baa60e06c6dc
Cordialement,
YN
