### ISSUE TITLE
Aucune ressources n'est pas définie pour ce domaine après avoir supprimé une réservation

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#347]
Bonjour,
#343
J'ai fait la mise à jour 4.3.2 et le problème est toujours là. (issue #343)
J'ai remarqué que quand on supprime une réservation, GRR ajoute une apostrophe sur le champ URL à la fin.
Quand je supprime l'apostrophe, cela revient à la normale.

Y a-t-il pas un lien ?

**Comment by JeromeDevome** [comment]
Pouvez vous me copier le lien ? Sans le domaine au début de l'adresse.

**Comment by SteBoun** [comment]
day.php?day=15&month=03&year=2024&area=5&room=all'

**Comment by JeromeDevome** [comment]
https://github.com/JeromeDevome/GRR/issues/343#issuecomment-2001925917

**Comment by SteBoun** [comment]
Du coup avec la modif cela fonctionne

Merci beaucoup
