### ISSUE TITLE
Mail automatique de modération n'envoit pas sur le bon lien

### ISSUE THREAD

**Issue by amomm** [JeromeDevome/GRR#349]
Bonjour, 
Le mail automatique envoyé aux gestionnaires d'une ressource modérée envoit sur le lien 
/validation.php?id=xxxxx

ne devrait il pas renvoyer plutot sur 
/app.php?p=vuereservation&id=xxxxx

Ceci permettrait aux modérateurs directement d'éditer la réservation sans repasser par le calendrier.

Merci

**Infos GRR**
Version de GRR : 3.4.1
Version PHP : 8.3

**Comment by JeromeDevome** [comment]
Bonjour,
C'est le fonctionnement historique, je ne sais pas pourquoi cela a été fait comme cela à une époque. Lorsque j'ai refait la page vue réservation, je me suis posé la même question.
Je pense que dans l'une des prochaines versions il n'y aura plus que page vue réservation. C'est un doublon inutile de mon point de vue. Mais il faut que je regarde plus attentivement qu'il n'y a pas de particularité.

**Comment by ynaessens** [comment]
Bonjour,
effectivement, cette page est "historique" et reprend largement le code de la page view_entry.
En pratique, pour ce qui est du message automatique, le lien complet est calculé au moyen de l'adresse réelle de GRR, définie dans la page de configuration générale. Si vous la laissez vide, GRR et le serveur sont en général capables de rediriger vers la page cible. Hors contexte, cela pose problème, d'où l'utilité de ce paramètre.
Dans la branche de développement devel3, j'ai proposé une modification de la page validation.php qui consiste à s'assurer que la connexion est bien établie avec les droits suffisants avant de rediriger vers la page view_entry où il y a tout ce qu'il faut pour valider une demande de réservation.
Cordialement,
YN

**Comment by JeromeDevome** [comment]
Bonjour,
J'ai modifié pour la prochaine version 9b1f25cf .
J'ai volontairement laissé la page validation.php (qui ne sert plus) mais pour pas que tout les liens soit HS. Je prévois dans la 4.4 de faire une redirection transparente.

**Comment by JeromeDevome** [comment]
Version 4.3.3 disponible, veuillez mettre à jour et me tenir informé si le problème persiste ou non.

Bonne journée.

**Comment by amomm** [comment]
Bonjour, 
c'est tout bon. Merci beaucoup ! 

Cordialement, 

-- 
Axel Momm 
Responsable du pôle développements - DSI 
Mines Saint-Étienne, une école de l'Institut Mines-Télécom 
Direction des systèmes d'information 
04 77 42 00 31 



De: "JeromeB" ***@***.***> 
À: "JeromeDevome/GRR" ***@***.***> 
Cc: "Axel MOMM" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 1 Avril 2024 13:49:57 
Objet: Re: [JeromeDevome/GRR] Mail automatique de modération n'envoit pas sur le bon lien (Issue #349) 





Version 4.3.3 disponible, veuillez mettre à jour et me tenir informé si le problème persiste ou non. 

Bonne journée.
