### ISSUE TITLE
V4.3.2 - Permettre aux administrateurs de marquer une ressource comme empruntée quand ils créent une réservation

### ISSUE THREAD

**Issue by CVZ-es** [JeromeDevome/GRR#352]
Bonjour, 

Dans un premier lieu, un grand merci pour toutes les avancées sur le logiciel !

Je me permets de vous écrire, car j'ai procédé ce jour à la montée de version de  4.2.4 à 4.3.2, et malheureseument, une fonctionalité bien pratique pour nous a disparu, la fonction qui permet aux administrateurs de marquer une ressource comme empruntée quand ils créent une réservation
Vous l'aviez résolé il y a quelques mois dans ce thread :
https://github.com/JeromeDevome/GRR/issues/275

Un grand merci par avance si vous pouvez l'implémenter dans la branche 4.3.X

Bon dimanche
Damien

**Comment by JeromeDevome** [comment]
Version 4.3.3 disponible, veuillez mettre à jour et me tenir informé si le problème persiste ou non.

Bonne journée.

**Comment by CVZ-es** [comment]
Merci beaucoup !
Je vous confirme que c'est résolu avec la version 4.3.3 :-)
Bien à vous
Damien
