### ISSUE TITLE
XSS possible dans la page de login

### ISSUE THREAD

**Issue by michaelpiche** [JeromeDevome/GRR#356]
**Décrivez le bogue**
Nous avons été informé d'une vulnérabilité  XSS sur la page de login avec le paramètre url.

**Infos GRR**
Version de GRR : 3.5.1
Version PHP : 8.2
Problème suite à une installation ou mise à jour : Non

**Reproduire**
Voici une adresse qui permet de reproduire : 
`login.php?param=&url=/reservation/month_all.php?%22%3E%3Cscript%3Ealert(%22Frankooo%22)%3C/script%3E`

**Contexte supplémentaire**
Pour le moment, j'ai modifié le code de login.php à la ligne 200, ce qui semble corriger le problème : 

Avant : 
`echo "<input type=\"hidden\" name=\"url\" value=\"".$_GET['url']."\" />\n";`

Après : 
 `echo "<input type=\"hidden\" name=\"url\" value=\"".clean_input($_GET['url'])."\" />\n";`

**Comment by ynaessens** [comment]
Merci beaucoup pour le signalement. Cela a échappé aux filtrages mis en place...

**Comment by JeromeDevome** [comment]
Corrigé dans la  3.5.1d
