### ISSUE TITLE
Toute les réservations en vue journée

### ISSUE THREAD

**Issue by Cyrilb42** [JeromeDevome/GRR#358]
Bonjour,

En vue journée, les réservations n'apparaissent pas et toutes les ressources apparaissent comme disponible (ce qui est faux).
Alors qu'en vue semaine, les réservations apparaissent bien avec un code couleur établie.

Ce bug est présent et visible sur d'autres domaines/ressources testés.

Merci

Infos GRR
Version de GRR : 4.3.2
Version PHP : 8.3

**Comment by JeromeDevome** [comment]
Bonjour,
Le commit [c2e31bb](https://github.com/JeromeDevome/GRR/commit/c2e31bb324a029616c7a89c63c11b7c891061de5) corrige le problème, je devrais générer une nouvelle version ce week-end.

**Comment by JeromeDevome** [comment]
Version 4.3.3 disponible, veuillez mettre à jour et me tenir informé si le problème persiste ou non.

Bonne journée.

**Comment by Cyrilb42** [comment]
Bonjour,
Parfait, le problème est corrigé.
Merci pour la réactivité
