### ISSUE TITLE
Warnings et deprecated s'affichent lorsqu'on sélectionne une ressource

### ISSUE THREAD

**Issue by Philippe34** [JeromeDevome/GRR#359]
**Décrivez le bogue**
Lorsqu'on choisit d'afficher une ressource (ici, une salle de réunion), les réservations apparaissent avec un warning et un message deprecated

**Infos GRR**
Version de GRR : 3.5.1d
Version PHP : 8.1.27

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans 'Ressources' et choisissez une ressource
2. Des messages d'avertissement sont affichés dans les réservations

![image](https://github.com/JeromeDevome/GRR/assets/12435553/26708e7e-2257-4bcc-b1a6-8e45c2248dc9)

```
Warning: Undefined array key "who" in /var/www/html/grr/week.php on line 827
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/grr/week.php on line 827
```

Cela correspond au code ligne 827 dans week.php

`echo "<a title=\"".htmlspecialchars($d[$weekday][$slot - $decale_slot * $nb_case]["who"])."\"  data-width=\"675\" onclick=\"request($id,$wday,$wmonth,$wyear,$room,'$currentPage',readData);\" data-rel=\"popup_name\" class=\"poplight lienCellule\">" ;`

J'ai trouvé une solution provisoire en retirant de ce code la partie correspondant à title

`echo "<a data-width=\"675\" onclick=\"request($id,$wday,$wmonth,$wyear,$room,'$currentPage',readData);\" data-rel=\"popup_name\" class=\"poplight lienCellule\">" ;`

![image](https://github.com/JeromeDevome/GRR/assets/12435553/01855d40-bbb6-41c9-b1c9-5b221e0af6b6)

**Contexte supplémentaire**

Si dans Ressources, on choisit 'Toutes les ressources', ce problème n'apparait pas.

Pourriez-vous SVP proposer un correctif à ce problème d'affichage ?

PS : Autre remarque pour M. Devome
Si on essaie de saisir le problème sur le forum: https://site.devome.com/fr/grr/forum-grr
On ne peut pas le faire, car on n'a pas la possibilité de saisir dans Message (tests avec Firefox et Chrome)

![image](https://github.com/JeromeDevome/GRR/assets/12435553/3300c570-afb2-483f-a15d-7d5abdb36b90)

**Comment by JeromeDevome** [comment]
Bonjour,
Pourquoi ne pas passer en version 4 ?

Merci pour le forum je vais y regarder.

**Comment by Philippe34** [comment]
Bonjour @JeromeDevome 
Nous avons un GRR 1.9.7e et nous le migrons vers un GRR 3.5.1
On a réussi à le faire fonctionner en récupérant la base de données et toutes les données (réservations, comptes) et j'ai vu que je ne pouvais migrer qu'au plus vers 3.5.1
J'ai aussi pas mal adapté le code pour le faire fonctionner avec notre environnement spécifique (multi authentification avec différents LDAP et attribution des droits multi-sites en fonction des adresses électroniques). En regardant le code de la version 4, c'était tout simplement impossible à réaliser.
Si nous avions mis en place GRR sans avoir à récupérer l'historique (création des ressources, conservation des réservations), je serai certainement parti sur la version 4.
Bien à vous.

**Comment by ynaessens** [comment]
Bonjour,
merci pour ce retour.
Je n'ai pas rencontré ce message warning car en principe le champ who ne devrait pas être NULL.
J'éluciderai la question dès que possible.
Cordialement,
YN

**Comment by Philippe34** [comment]
Merci @ynaessens pour votre investigation.
A part ce warning, je n'ai pas constaté d'autres bugs dans l'utilisation de la version 3.5.1
Cordialement

**Comment by Philippe34** [comment]
Le problème a été corrigé depuis la version 3.5.1e
