### ISSUE TITLE
Fichiers css manquant

### ISSUE THREAD

**Issue by Cyrilb42** [JeromeDevome/GRR#363]
Bonjour,

Depuis la mise à jour récente de GRR nous avons constaté une anomalie sur la liste déroulante (autocomplété) "Réservation au nom de".
Cette liste est visible lors de la création d'une réservation ou de la modification en mode gestionnaire.
Après avoir tapé quelques caractères, les résultats de la liste apparaissent en bas de page avec une vision liste à puces.
La sélection reste possible, mais peu confortable.

Après vérification, en console, des erreurs d'appels aux fichiers css sont présents visiblement supprimé dans le Commit b22b3c8.
Merci de votre aide

Infos GRR
Version de GRR : 4.3.2
Version PHP : 8.3

**Comment by JeromeDevome** [comment]
Attention, vous ne devez pas utiliser les fichiers les branches, elles viennent avec d'autres modifications... et ne sont pas forcément testées de bout en bout .

Pour télécharger une version, vous devez le faire sur la droite, dans release.
