### ISSUE TITLE
Problème recherche & stats

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#369]
**Décrivez le bogue**
Quand je veux faire des stats par rapport à un champ additionnel que j'ai créé (en résumé).
Cela me retourne un "-1" sans mettre toutes les données que j'ai mises dans mon champ additionnel alors que quand je fais avec les bénéficiaires ou avec les détails, cela me retourne bien le champ additionnel.  
**Infos GRR**
Version de GRR : 4.3.3
Version PHP : 8.1.23
Problème suite à une installation ou mise à jour : nope

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans Recherche & Stats
2. Dans "Résumé par (ne concerne que les résumés)", cliquez sur un champ additionnel que vous avez créé (liste).
3. Cliquer sur "envoyer"
4. Voir l'erreur

**Comportement attendu**

![2024-05-13 16_12_19-GRR - Vendee Grand Littoral _ Talmont Saint Hilaire](https://github.com/JeromeDevome/GRR/assets/50909713/d0039e9f-d64e-4ead-a4c0-2a5cf3c379b0)

**Captures d'écran**
Champ de sélection avant d'envoyer :
 
![2024-05-13 16_23_41-GRR - Vendee Grand Littoral _ Talmont Saint Hilaire](https://github.com/JeromeDevome/GRR/assets/50909713/1eb4ce16-dcf9-45d5-9d65-5099cabe7e6c)

Liste du champ additionnel :
Finance|Commande publique|DCSI|Coordination générale|Ressources Humaines|Ports|Développement économique|Environnement|Territoire et transitions écologiques|Urbanisme|Solidarité|Petite enfance|Enfance - jeunesse|Evènementiel|Culture et patrimoine|Sports|Service Techniques et ingénierie|Élus|Accueil|Secrétariat des élus|Communications|Services déchets

**Comment by JeromeDevome** [comment]
Bonjour,
Je pense que le bug est lié à
https://github.com/JeromeDevome/GRR/commit/043efb2a80a85595812d580b106eab606349a470

les réservations sont enregistrées sous un mauvais champ additionnel et cela empêche la recherche correctement.

**Comment by JeromeDevome** [comment]
Bonjour,
Pouvez-vous mettre à jour votre version en 4.3.6, et voir si vous avez encore le problème ou non ? (uniquement sur les réservations créé après la mise à jour)

**Comment by SteBoun** [comment]
non le problème est toujours présent
