### ISSUE TITLE
Détail réservation au survol de la souris

### ISSUE THREAD

**Issue by xillibit** [JeromeDevome/GRR#374]
Dans la 4.3.x au survol avec la souris d'une réservation, ça affiche ça. Est-ce que c'est possible d'afficher comme c'était dans la 4.2.x ?

![Capture d'écran 2024-06-14 103038](https://github.com/JeromeDevome/GRR/assets/876395/700fe26c-21f4-4220-8b7d-f1056a9333c0)

**Comment by JeromeDevome** [comment]
Bonjour,
Je pense que c'est cela qui vous convient :
https://devome.com/GRR/DOC/configuration-generale/apparence#affichage-des-informations-sur-les-r%C3%A9servations-dans-les-vues-jo

**Comment by xillibit** [comment]
Bonjour,

merci j'ai réussi à paramétrer l'info-bulle
