### ISSUE TITLE
Gestion des utilisateurs actifs / inactifs

### ISSUE THREAD

**Issue by babalou** [JeromeDevome/GRR#375]
Bonjour,

Il me semblait dans les version 3.x de GRR :
- Dans la liste des utilisateurs : il y avait un filtre pour afficher tous les utilisateurs, ou seulement les utilisateurs actifs ou seulement les utilisateurs inactifs.
- Dans la fiche d'un utilisateur : il était possible de définir un utilisateur actif ou inactif.

Dans la version 4.3.x de GRR, je ne retrouve plus ces deux fonctions.

**Infos GRR**
Version de GRR : 4.3.5 - Release-v4.3.5
Version PHP : 8.0.30
Problème suite à une installation ou mise à jour : peut-être lié au passage en version 4.3.x. ?

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans "Utilisateurs et accès" > "Utilisateurs". La liste des utilisateurs s'affiche.
**Comportement attendu**
Affichage d'un filtre pour afficher tous les utilisateurs, uniquement les utilisateurs actifs, uniquement les utilisateurs inactifs.
**Comportement constaté**
Absence de ce filtre.

**Reproduire**
Étapes pour reproduire le comportement :
1. Allez dans "Utilisateurs et accès" > "Utilisateurs".
2. Cliquer sur le bouton de modification d'un utilisateur (dans la colonne "Action"). La fiche de l'utilisateur s'affiche.
**Comportement attendu**
Affichage d'un champ pour définir un utilisateur comme actif ou inactif.
**Comportement constaté**
Absence de ce champ.

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows 10 Pro (64 bits)
  - Navigateur : Firefox
  - Version : 127.0.2

Bien cordialement,

**Comment by JeromeDevome** [comment]
Bonjour,
Pour la liste c'est un choix que j'ai fais, car nous pouvons trier entre inactif et actif et filtrer par inactif via le champ recherche.
Cela est-il suffisant ?

Concernant la modification de l'utilisateur, ceci est corrigé : bc8d8b35

**Comment by babalou** [comment]
Bonjour,

Merci beaucoup pour la correction apportée.

Concernant le tri entre actif/inactif sur la liste des utilisateurs, vous avez raison, il est possible de :
- saisir "inactif", pour afficher les comptes utilisateurs inactifs.
- saisir "actif" + faire un tri sur la colonne "Actif", pour afficher les comptes utilisateurs actifs en premier.
C'est suffisant pour notre gestion courante.

Bien cordialement,

**Comment by JeromeDevome** [comment]
Bonjour,
Disponible dans la version 4.3.6
