### ISSUE TITLE
SSO - CAS : Récupérer le displayName en plus du nom et du prénom

### ISSUE THREAD

**Issue by Gael-Mifsud** [JeromeDevome/GRR#381]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Pour le moment, dans personnalisation/config_CAS.inc.php on peut récupérer - entres autres - le nom et le prénom d'un utilisateur authentifié par SSO.

Problème, dans notre structure, le SSO renvoie également un attribut **displayName** que l'utilisateur peut configurer sur son ENT et qui est souvent préféré (pour cause de mariage/divorce/changement de sexe, etc).
Certaines personnes qui changent de prénom sont assez sensibles sur le sujet.

**Décrivez la solution que vous souhaitez**
Il serait idéal que GRR puisse :
- récupérer cet attribut dans une variable (ex : $user_affichenom) et,
- lorsqu'elle est récupérée, GRR l'utilise au lieu d'afficher Prénom Nom,
- mais GRR continue à utiliser Prénom et Nom pour les comptes locaux et ceux qui n'ont pas cet attribut dans leur SSO

**Décrivez les alternatives que vous avez envisagées**
J'ai bien pensé à récupérer l'attribut displayName et à ajouter une fonction dans config_CAS.inc.php qui tenterait d'en extraire le nom et le prénom, mais entre les prénoms composés, les noms à particule, et les personnes étrangères, cela me paraît impossible.

Maintenant, si GRR affichait toujours "Prénom Nom" et jamais prénom tout seul ou nom tout seul, alors je pourrais couper au premier espace sans me faire de soucis, et mettre la première partie dans Prénom et le reste dans Nom.
Mais en l'état ce n'est pas possible car, côté Admin, GRR affiche souvent "Nom Prénom", alors que du côté utilisateur, il affiche "Prénom Nom".

Merci.

**Comment by ynaessens** [comment]
Bonjour,
la situation que vous exposez ne paraît effectivement pas simple.
Le seul attribut qui soit intangible est le login, il est possible d'autoriser les utilisateurs à changer leur nom et prénom. Ce n'est pas idéal, mais permet aux utilisateurs de faire afficher leur displayName dans les réservations...
Cordialement,
YN

**Comment by Gael-Mifsud** [comment]
Merci.
Nous allons nous contenter de Nom Prénom tant qu'aucun utilisateur ne fait remonter le problème.
