### ISSUE TITLE
Bug affichage reservation fin de mois

### ISSUE THREAD

**Issue by NHtoul** [JeromeDevome/GRR#382]
**Décrivez le bogue**
Lors d'une réservation qui implique le dernier jour d'un mois. En vue mensuel, l'évènement et affiché sur le lendemain (1er jour du mois suivant ) alors qu'il ne devrait  pas être affiché.

**Infos GRR**
Version de GRR : 4.3.6
Version PHP : 8.2
Problème suite à une installation ou mise à jour : non toujours eu depuis la 4.3.0. peut être même inférieure

**Reproduire**
Étapes pour reproduire le comportement :
1. Réserver une ressources sur un planning ouvert 7/7, la réservation comporte par exemple 2 jours sur les 2 derniers jours du mois de juillet.
2. Aller sur le mois d'Aout en vue mensuel
3. Vous constatez l'affichage de la réservation jusqu'au 1 aout.

**Comportement attendu**
La réservation ne doit pas s'afficher le 1er du mois suivant a lors qu'elle se termine le dernier jour du mois précédent.
Bug présent sur n'importe quel navigateur / terminal.

**Captures d'écran**

![2024-08-07 13_52_22-débordement juin 3](https://github.com/user-attachments/assets/ef32078c-c9ca-48ac-82fd-db9755264f57)

![2024-08-07 13_54_54- - Mozilla Thunderbird](https://github.com/user-attachments/assets/1c7479d7-9ee0-44c5-8cca-c5bd1a5a897b)

**Comment by ynaessens** [comment]
Bonjour,
le bug existe en effet depuis longtemps.
Il ne se produit que lorsqu'on utilise la durée en jours, que ce soit avec des créneaux comme dans votre exemple ou avec des réservations basées sur le temps.
Tout dépend de ce qu'on attend d'une réservation de deux jours commençant le 30 juillet au matin : doit-elle s'arrêter le 31 au soir ou le 1er août avant le matin ? Pour les créneaux cela paraît assez clair, pour le temps cela mérite réflexion.
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
je propose ces correctifs selon la version de GRR :
pour la v 3.5.1, https://github.com/JeromeDevome/GRR/commit/8dcd51491fe4e58b8ad616ab956cb7003efa297e
pour la v 4.3.6, https://github.com/JeromeDevome/GRR/commit/e6a5c723a82888bfe1b5d044b8916c55c673feda
en espérant que cela ne crée pas d'effet indésirable.
Cordialement,
YN

**Comment by NHtoul** [comment]
Bonjour,
Je vous confirme le bon fonctionnement du patch, sans avoir noté d'effet indésirable.
Merci  pour votre suivi.
Cdt, NH
