### ISSUE TITLE
Boutton pour effacer une réservation ne demande plus de confirmation

### ISSUE THREAD

**Issue by jfsenechal** [JeromeDevome/GRR#385]
**Décrivez le bogue**
Lorsqu'on clique pour effacer une réservation il n'y a pas de demande de confirmation

**Infos GRR**
Version de GRR : 4.3.2
Version PHP : 8.2
Problème suite à une installation ou mise à jour : Non

**Reproduire**
Étapes pour reproduire le comportement :

Cliquez sur le bouton ^-^

**Solution**

```html
<a class="btn btn-danger" type="button" href="del_entry.php?id=207064&amp;series=0&amp;page=week_all&amp;room_back=all'" onclick="return confirm('Etes-vous sûr de vouloir effectuer l'action suivante ?\nEffacer cette réservation');">Effacer cette réservation</a>
```
A cause de l'apostrophe ... l'action...
Ajouter un slash avant

```
 l\'action
```

Merci

**Comment by JeromeDevome** [comment]
Bonjour,
Merci pour votre expertise, j'ai apporté une correction : 9c2d836

**Comment by JeromeDevome** [comment]
Effectif dans la version 4.3.7 qui vient d'être publiée.
