### ISSUE TITLE
Grosse lenteur de GRR. 

### ISSUE THREAD

**Issue by SteBoun** [JeromeDevome/GRR#400]
Bonjour

Depuis que l'on a activé le module ICS, nous avons de grosses lenteurs quand on se connecte à GRR.

Nous remarquons de grosses perfs au niveau de processeurs de notre serveur GRR.

Cela arrive quand on dépasse les 15 utilisateurs qui utilisent GRR de manière simultané.

Nous avons dû désactiver ce module pour continuer à utiliser GRR.

**Comment by JeromeDevome** [comment]
Bonjour,
Je vous invite à contacter commercial@devome.com pour trouver une solution.
