### ISSUE TITLE
Échanger les salles de deux réservations

### ISSUE THREAD

**Issue by ysalmon** [JeromeDevome/GRR#42]
Bonjour,
actuellement il est difficile d'échanger les salles de deux réservations ayant lieu en même temps. Il faut déplacer l'une d'elle dans une salle ou un horaire libre (à supposer qu'il en existe), déplacer l'autre dans la salle ainsi libérée puis déplacer de nouveau la première réservation dans la deuxième salle.

C'est assez lourd surtout pour des réservations récurrentes.

Il serait pratique de pouvoir, de façon atomique, échanger les salles de deux réservations ayant lieu en même temps.

À moins que ça soit déjà possible et que je n'aie pas trouvé ?

**Comment by ynaessens** [comment]
J'ai intégré cette fonctionnalité dans la future 3.4.1, actuellement en développement sur la branche devel3.
