### ISSUE TITLE
Problème CKEditor 

### ISSUE THREAD

**Issue by n-goncalves** [JeromeDevome/GRR#50]
Bonjour, 

Dans l'onglet Administration > Configuration Générale, (et surement dans les autres écrans où cet éditeur est utilisé) dans la version 3.3.1b de GRR, l’éditeur wysiwyg ckeditor ne s'affiche pas et cause des erreurs dans la console car des skins et des plugins ne sont pas présent (ou pas utiles ?) .

Contenu de la console : 
```
**ckeditor.js:89 GET http://localhost:8080/grr-original/js/ckeditor/skins/moono-lisa/editor.css?t=HBDG net::ERR_ABORTED
ckeditor.js:89 GET http://localhost:8080/grr-original/js/ckeditor/plugins/colorbutton/plugin.js?t=HBDG net::ERR_ABORTED
ckeditor.js:241 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "colorbutton" was not found at "http://localhost:8080/grr-original/js/ckeditor/plugins/colorbutton/plugin.js?t=HBDG".
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js:241)
    at f (ckeditor.js:236)
    at Array.n (ckeditor.js:236)
    at p (ckeditor.js:237)
    at HTMLScriptElement.CKEDITOR.env.ie.f.$.onerror (ckeditor.js:237)**
```

**Comment by ynaessens** [comment]
Bonjour, 
l’apparence de l’éditeur est-elle différente entre les versions 3.3.1b et celle de la branche master ?

**Comment by n-goncalves** [comment]
Ce problème n'intervient pas sur la branche master.

**Comment by ynaessens** [comment]
Bonjour,
merci pour votre signalement. Effectivement la mise à jour par git avait omis quelque 2000 fichiers du package ckEditor. Je viens de tester une fresh install, cela semble correct.

**Comment by n-goncalves** [comment]
Problème corrigé effectivement, je ferme l'issue.
Merci de votre résolution rapide et désolé pour mon silence.
