### ISSUE TITLE
retour page d'appel après acceptation

### ISSUE THREAD

**Issue by elbertondu62** [JeromeDevome/GRR#51]
Bonjour j'ai installé la version 3.3.1.
Quand un utilisateur accepte une modération, cela lui renvoi une page dans le lien .php
Ce qui du coup indique une erreur.
Que puis-je faire pour corriger cette erreur ?

A priori j'ai vu une modification de fait sur une page view-entry.php récemment.
Puis-je la mettre à jour dans ce cas depuis git-hub ?

**Comment by ynaessens** [comment]
Bonjour,
j'ai commité une modification du script view_entry.php afin de corriger cette erreur. Je vous encourage à télécharger cette nouvelle version et nous dire si les modifications apportées sont efficaces.
Merci.
YN
