### ISSUE TITLE
Documentation Module Externe

### ISSUE THREAD

**Issue by n-goncalves** [JeromeDevome/GRR#54]
Bonjour,

Je me suis installé la pre-release 4.0a sur ma machine pour faire quelques tests, et j'ai vu qu'il y avait maintenant la possibilité d'ajouter des modules externes ce qui est super intéressant, cela permettra au final de me passer d'un fork de GRR pour n'avoir qu'un seul module spécifique à mon besoin. 

Cependant, je n'ai pas vu de documentation accessible à ce sujet ici et sur votre site. Est-ce que celle-ci sera disponible au moment de la release ou dans un futur plus ou moins proche ?

**Comment by ynaessens** [comment]
Bonjour,
le système de pages et de modules existe déjà en version 3.4.0.
Par contre, Jérôme n'a pas encore détaillé le mode d'emploi.
Cordialement,
YN

**Comment by Bruyant** [comment]
Bonjour,
Je suis aussi très intéressé par la doc,
Pour suivis,
Merci

**Comment by JeromeDevome** [comment]
https://github.com/JeromeDevome/GRR-Modules
