### ISSUE TITLE
Pouvoir modifier le créneau de réservation

### ISSUE THREAD

**Issue by xillibit** [JeromeDevome/GRR#55]
Comme vous pouvez le voir sur l'image ci-dessous, je voudrais modifier le créneau de réservation qui est entouré en rouge. Je voudrais que cela commence à partir de 7h00
![periode_reservation](https://user-images.githubusercontent.com/876395/45492213-07340200-b76c-11e8-9644-5fa7872730a4.png)

Est-ce une modification à faire pour que ça soit modifiable ou c'est modifiable dans la configuration ?

**Comment by ynaessens** [comment]
Bonjour,
si c'est juste pour modifier les heures d'ouverture des ressources, cela se règle en page d'administration des domaines, avec un compte administrateur.

**Comment by xillibit** [comment]
Bonjour, j'ai beau chercher dans administration des domaines, je ne vois que la possibilité d'affecter des utilisateurs pour qu'il puissent gérer la ressource.

P.S. : je suis bien connecté avec le compte administrateur

**Comment by ynaessens** [comment]
Bonjour,
je crois qu'on s'est mal compris. L'URL à laquelle je pensais est grr/admin/edit_room.php?id_area="le numéro du domaine à éditer". Vous y personnalisez les paramètres du domaine.

**Comment by xillibit** [comment]
Merci, j'ai trouvé maintenant
