### ISSUE TITLE
Affichage par heure

### ISSUE THREAD

**Issue by nicodmf** [JeromeDevome/GRR#6]
Bonjour,

Est t'il possible dans l'admin de configurer l'affichage en ayant un affichage à l'heure plutot qu'au quart d'heure ?

Bien Cordialement,

Nicolas de Marqué

**Comment by JeromeDevome** [comment]
Bonjour,

Oui dans administration, et dans la configuration du domaine.

 

Cordialement,

Jérôme

 

Administrateur Team Devome

Chef de projet GRR

 

 <http://devome.com/> http://devome.com

 <http://forum.devome.com/> http://forum.devome.com Discussion & Entraide

 

De : Nicolas de Marqué Fromentin [mailto:notifications@github.com] 
Envoyé : jeudi 17 septembre 2015 16:41
À : JeromeDevome/GRR <GRR@noreply.github.com>
Objet : [GRR] Affichage par heure (#6)

 

Bonjour,

Est t'il possible dans l'admin de configurer l'affichage en ayant un affichage à l'heure plutot qu'au quart d'heure ?

Bien Cordialement,

Nicolas de Marqué
