### ISSUE TITLE
Revoir le code de zéro et intégrer les outils symfony

### ISSUE THREAD

**Issue by jfsenechal** [JeromeDevome/GRR#60]
Hello la communauté

Je lance un débat quand à la refont de l'outil GRR.
Comme vous le savez, il a hérité du vieux php et son code est on peut le dire quelque peut... pourris

Continuer a mettre en place de nouvelles fonctionnalités avec cet héritage ne mènera pas loin (risque de développer des bugs, aucun test possible, perte de temps...)

Donc prenons notre courage, et réécrivons tout ! 

Class, url friendly, abstracteur de db, gestion des injections des dépendances, batteries de test, template,...
Bref de la programmation "moderne" ;-)

J'ai l'habitude de travailler avec symfony, avec son système de modularité on est pas obligé de prendre tout le framework

J'ai commencé à l'installer #59 

Avec ses quelques lignes de code on a déjà un système d'url, controlleur, template, gestion des dépendances entre classes
et pas mal d'autres petites choses comme accéder autre que des $_GET $_POST

Pour avancer il faudrait par commencer par créer des classes par table, rassembler tous les query...

Mais avant que j'essaie d'aller plus loin, qu'en pensez vous ?

Avez vous songer à réécrire le code ?

Connaissez vous symfony ?

**Comment by remyd1** [comment]
Bonjour,

Juste pour dire que je suis plutôt pour, tant que je peux toujours surcharger facilement certaines fonctions (c'est ce que je fais actuellement pour alimenter un agenda caldav). Donc au pire, j'aimerai avoir un système de plugin ou pouvoir continuer à surcharger les fonctilns en questions.

Merci.

**Comment by Drallibor** [comment]
Bonjour,

c'est intéressant comme démarche. Il y a exactement un an, j'avais posé la question sur le forum GRR ([c'est par là]( https://site.devome.com/fr/kunena/proposer-une-correction/24-roadmap)) : savoir s'il y avait une roadmap, un framework en vue, une API ou encore un moteur de templates. A ce moment-là, je trouvais qu'un framework permettait d'impliquer potentiellement d'autres contributeurs.
La réponse de JeromeB avait été plutôt non.  

Symfony est un framework très connu en France, avec plein de tutoriels et de la documentation. Il demande une phase d'apprentissage non négligeable, et je le trouve adapté plutôt aux gros projets. D'un autre côté, on peut l'utiliser en version light avec "Silex", et puis l'étendre en fonction des besoins grâce à sa modularité.

**Comment by jfsenechal** [comment]
Silex est "mort"

https://symfony.com/blog/the-end-of-silex

Disons qu'il est maintenant intégré à symfony vu que celui-ci a décomposé son framework en "Components"

https://symfony.com/doc/current/components/index.html

Chaque composant peut être utilisé sans devoir installer tout le framework

C'est vrai qu'il demande un apprentissage, mais il n'est pas si difficile a utiliser que ça et quand on a commencé à developper avec croyez moi qu'on ne sait plus s'en passer ;-)

Pour le système de plugin, c'est claire qu'il en faut absolument un, je ne sais pas encore techniquement comment implémenter ça

Je propose qu'une branche 4.0 soit crée, et qu'on continue a discuter de comment et quoi mettre en place

**Comment by Drallibor** [comment]
Je n'avais pas vu l'intégration de Silex à Symfony : c'est une assez bonne évolution dans la mesure où ce dernier est divisé en composants.
Entre temps j'étais passé à MKFramework, sur d'autres petits projets. Hyper simple à apprendre, convenant aux applications de taille réduite, sécurisé, mais plus confidentiel que Symfony.

**Comment by jfsenechal** [comment]
Oui intégré est un mauvais terme, je devrais dire "remplacer" ;-)

**Comment by JeromeDevome** [comment]
Bonjour,

La version Master sera la version 4.0 en cours de developpement, à l’intérieur il y a un nouveau template admin, mais surtout le passage sous TWIG.

 

 

De : Jf <notifications@github.com> 
Envoyé : mercredi 14 novembre 2018 12:07
À : JeromeDevome/GRR <GRR@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [JeromeDevome/GRR] Revoir le code de zéro et intégrer les outils symfony (#60)

 

Oui intégré est un mauvais terme, je devrais dire "remplacer" ;-)

**Comment by ynaessens** [comment]
Bonjour à tous,
Jérôme a été plus rapide que moi pour répondre, d'autant que je n'étais pas sur mon ordinateur ces dernières heures ;-)
Si vous aviez consulté la page https://github.com/JeromeDevome/GRR/releases vous auriez vu l'évolution en cours de GRR :
- je maintiens la branche 3 sur les outils classiques : HTML + PHP + CSS + JS et un peu de Bootstrap pour la mise en page essentiellement. Conformément aux règles de nommages historiques, les modifications sur la base de données déclenchent un nouveau numéro de version. Vous avez donc la release stable 3.4.0a en cours et sous peu sortira une 3.4.0b. Vous avez une release en cours de préparation 3.4.1 RC1 dans laquelle j'ai repris le calcul des pages planning et admin, en allégeant le style.
- Jérôme développe une branche 4, basée sur Twig, de quoi satisfaire les amateurs de frameworks (?).
Comme jfsenechal le suggère dans le titre de cette issue, cela passe par une reprise assez large du code...
À remyd1 : si vous développez des fonctions intéressantes, ce serait sympa de les partager avec la communauté.
À Drallibor : je suis d'accord que notre travail manque de clarté, mais en général les idées ou améliorations viennent sur les pages "issues" de Github ou du forum https://site.devome.com/fr/grr/forum-grr
À tous, si vous voulez contribuer, vous êtes les bienvenus ! Postez vos idées sur ces pages et proposez vos pull requests !
Cordialement,
Yan

**Comment by Drallibor** [comment]
Hé bien que de chemin pour GRR en un an !
Une proposition de framework, un moteur de templates... Au passage Twig, c'est comme Symfony développé au départ par Fabien Potencier / Sensio Labs
Si je trouve du temps, je donnerais bien un coup de main sur l'interopérabilité. Je suis toujours convaincu par l'intérêt des API ou autres outils d'interface type caldav par exemple ;)

**Comment by jfsenechal** [comment]
> à l’intérieur il y a un nouveau template admin, mais surtout le passage sous TWIG.

Oui je l'avais vu et dans mon controlleur je les avais utilisé
L'admin est beaucoup plus beau ainsi :-)

**Comment by remyd1** [comment]
@ynaessens 

J'ai fait un Gist (diff du fichier include/mrbs_sql.inc.php) ici: https://gist.github.com/remyd1/3405f830c8575fb14e2764a86039634e

Cependant, je ne pense pas que ça soit réellement utile car je fais appel à du bash ensuite; je viens de faire le dépôt pour l'occasion: https://github.com/remyd1/bash_caldav
Dans l'absolu, il faudrait mettre à jour ça et le recoder en PHP7.

Le cadre d'utilisation de GRR est par ailleurs détourné car on s'en sert pour réserver des machines de calcul.

Rémy.

**Comment by ynaessens** [comment]
> Le cadre d'utilisation de GRR est par ailleurs détourné car on s'en sert pour réserver des machines de calcul.

Parce que vous ne considérez pas des machines de calcul comme des ressources ? Je ne vois pas où est le détournement.
Merci pour le partage de votre code. À temps perdu je regarderai comment en faire une fonctionnalité intégrée à GRR.
Yan

**Comment by JeromeDevome** [comment]
Bonjour, j’ai mis en place un serveur discord https://discord.gg/XGfuZyU , peut-être mieux pour discuter ?

 

De : ynaessens <notifications@github.com> 
Envoyé : jeudi 15 novembre 2018 18:07
À : JeromeDevome/GRR <GRR@noreply.github.com>
Cc : JeromeDevome <team.devome@gmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [JeromeDevome/GRR] Revoir le code de zéro et intégrer les outils symfony (#60)

 

Le cadre d'utilisation de GRR est par ailleurs détourné car on s'en sert pour réserver des machines de calcul.

Parce que vous ne considérez pas des machines de calcul comme des ressources ? Je ne vois pas où est le détournement.
Merci pour le partage de votre code. À temps perdu je regarderai comment en faire une fonctionnalité intégrée à GRR.
Yan

**Comment by lhadjadj** [comment]
Bonjour, vous en êtes ou de la migration vers Symfony ?

**Comment by Guizmos** [comment]
Bonjour,

Des avancées dans la refonte de la GRR ?
Je trouve l'outil hyper pratique mais l'interface reste perfectible et surtout "modernisable" ;-)
En tout cas merci à tous pour votre travail

**Comment by jfsenechal** [comment]
Hello

Mon dieu déjà 4 ans que j'avais écrit mon post :hushed:	

Le sujet n'a pas vraiment avancé, probablement à cause du covid :sweat_smile:

Je suis motivé à travailler sur cette refonte du code, j'espère que d'autres aussi

En attendant, j'ai fait un début d'intégration avec symfony

Je pense que dans un premier temps on peut travailler avec des class php et doctrine pour travailler sur la db
qui reste le coeur de l'appli

Je vous laisse lire et découvrir

[](https://github.com/jfsenechal/labo-grr/wiki)

**Comment by JeromeDevome** [comment]
Bonjour,
Le covid est belle excuse :)  Je ne l’utiliserai pas .
J'ai commencé sur la branche master avec l'utilisation de composer et twig. L'ensemble des pages admins sont sur twig et un début de l'interface user.

J'ai développé avec mes connaissances appris sur le tas, je pense que l'on peut faire mieux avec plus de temps.

**Comment by ynaessens** [comment]
Bonjour,
@jfsenechal , à propos des modifications sur la base de données, je pense qu'il y a des modifications inutiles :
- ALTER TABLE `grr_calendar`
    ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
- ALTER TABLE `grr_calendrier_feries`
    ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
- ALTER TABLE `grr_calendrier_vacances`
    ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
l'ajout d'un id est inutile : si vous avez besoin d'un index, c'est DAY qui doit être unique (vérifié en pratique par le script, mais c'est vrai que c'est plus propre en le définissant explicitement)

Par contre
- ALTER TABLE `grr_j_type_area`
    ADD PRIMARY KEY (`id_type`, `id_area`);
- ALTER TABLE `grr_log` CHANGE `AUTOCLOSE` `AUTOCLOSE` BOOLEAN NOT NULL DEFAULT FALSE;
sont des modifications qui pourront être reprises dans les prochaines versions.

Cordialement,
YN

**Comment by jfsenechal** [comment]
@JeromeDevome Merci pour ton retour, je prends bonne note ;-)

@ynaessens Oui en effet vous avez raison pour les modifications sql, la modif sur grr_log c'est parque doctrine n'acceptait pas le type ENUM

Mais vu qu'on veut pas de mon symfony ce n'est pas nécessaire :-P ;-)
