### ISSUE TITLE
Problème d'affichage "Administration des domaines"

### ISSUE THREAD

**Issue by jonkief** [JeromeDevome/GRR#61]
Bonjour,

Depuis la partie "Administration des domaines " il n'est plus possible de supprimer les comptes (cf doc).

![image](https://user-images.githubusercontent.com/45974262/50165627-90b41c80-02e5-11e9-8ab9-48ff359e40bd.png)

Merci à vous.

---

Numéro de version GRR fichier :  : 4.0.0a GitHub
Numéro de version GRR BDD :  : 4.0.0a
Version PHP : 7.2.7
Base de donnée :  : mysql => 5.5.56-MariaDB

**Comment by JeromeDevome** [comment]
Bonjour,
Merci pour le signalement je viens de corriger dans le commit 668e6d8

Il est déconseillé d'utiliser la version 4.0.0alpha en production.
