### ISSUE TITLE
Pb Champs_Add & Edit_entry

### ISSUE THREAD

**Issue by NaldDev** [JeromeDevome/GRR#63]
Bonjour,

Travaillant sur la version 3.4.0 de GRR, lorsque j'ajoute un champ additionnel et que je le rend obligatoire sur un domaine, je ne peux plus selectioner une valeur dans le champ additionnel ainsi que choisir un type, cela est très genant.

Suis-je le seul avec ce problème ?

Merci d'avance.

**Comment by ynaessens** [comment]
Bonjour,
c’est une erreur de mise en page dans edit_entry, j’y ai travaillé récemment. Avez-vous la dernière version sur la branche 3.4.0 ?
Par ailleurs, si vous souhaitez contribuer, il vaudrait mieux le faire sur la branche devel3 ou la branche master. 
Cordialement,
YN

**Comment by NaldDev** [comment]
Oui, nous avons la dernière version stable 3.4.0c

**Comment by NaldDev** [comment]
Bonjour,
Je viens de tester avec la branche devel3 et notre configuration mais cela ne change rien, l'affichage ne se fait toujours pas.

**Comment by ynaessens** [comment]
Mauvaise nouvelle : tout n’est pas réglé :-(
Pouvez-vous détailler la configuration du domaine qui crée le problème ?

**Comment by NaldDev** [comment]
Voici la config du domaine :
![domaine](https://user-images.githubusercontent.com/43473126/53095657-b2b46000-351d-11e9-922b-090278e01593.jpg)

**Comment by ynaessens** [comment]
Merci, et pour ce qui est des champs additionnels associés à ce domaine ?

**Comment by NaldDev** [comment]
Sur ce domaine nous n'avons qu'un seul champ additionnel =>
![champsadd](https://user-images.githubusercontent.com/43473126/53151986-b646f600-35b4-11e9-97fc-abb216d4e8a8.jpg)

**Comment by ynaessens** [comment]
C'est le caractère obligatoire du champ additionnel qui crée l'erreur : analyse à approfondir...

**Comment by NaldDev** [comment]
Bonjour,
Effectivement cela corrige bien le problème.
Merci à vous.
