### ISSUE TITLE
Impossible d'installer la base

### ISSUE THREAD

**Issue by T0MuX** [JeromeDevome/GRR#74]
Bonjour, j'ai un serveur Caddy sous Windows Serveur 2012 R2, PHP 7.3.7, et MySQL 8.

Je n'arrive pas à mettre en place GRR. J'accède bien à la page de configuration de GRR (choix entre mise à jour ou installation de la BDD) mais quand je fais l'installation, ça fini toujours par cette erreur : 

> ERROR : 'INSERT INTO grr_type_area VALUES (2, 'R�union', 2, 2, '#C03000', '#000000', 'B', 2);'
> ERROR : 'INSERT INTO grr_setting VALUES ('title_home_page', 'Gestion et R�servation de Ressources');'
> ERROR : 'INSERT INTO grr_setting VALUES ('message_home_page', 'En raison du caract�re personnel du contenu, ce site est soumis � des restrictions utilisateurs. Pour acc�der aux outils de r�servation, identifiez-vous :');' 

Je ne comprends pas d'où ça vient. J'ai essayé deux façons différentes : soit en créant à l'avance la base 'grr' et l'user 'grr' puis de le renseigner lors de l'installation de GRR, soit en indiquant directement les identifiants 'root' de la bdd pour qu'il se débrouille de créer lui même la bdd et ses tables... même erreur.

**Comment by ynaessens** [comment]
Bonjour,
un problème avec les accents ?
Pouvez-vous essayer en modifiant le fichier tables.sql en modifiant les lettres accentuées ?
Cordialement,
YN

**Comment by T0MuX** [comment]
Bonjour, au vu de nos besoins, j'ai carrément créer un serveur (vm archlinux) de base de données. Avec un Postgresql et un MariaDB. Je rencontre à nouveau exactement le même problème, ce qui confirme pour moi la présence d'une erreur dans la web app.

Etapes de création de la BDD :
```mysql
CREATE USER 'grr20'@'%' IDENTIFIED BY 'PASS';
CREATE DATABASE grr20;
USE grr20;
GRANT ALL PRIVILEGES ON grr20 TO 'grr20'@'%';
```

Au moment d'installer GRR, je me connecte à la DB avec l'user grr20, puis choisis la DB grr20... puis bug identique : 

> ERROR : 'INSERT INTO grr_type_area VALUES (2, 'R�union', 2, 2, '#C03000', '#000000', 'B', 2);'
> ERROR : 'INSERT INTO grr_setting VALUES ('title_home_page', 'Gestion et R�servation de Ressources');'
> ERROR : 'INSERT INTO grr_setting VALUES ('message_home_page', 'En raison du caract�re personnel du contenu, ce site est soumis � des restrictions utilisateurs. Pour acc�der aux outils de r�servation, identifiez-vous :');' 

Où est situé ce fichier tables.sql ?

T0MuX

**Comment by ynaessens** [comment]
Désolé, c'était de mémoire : le fichier dont la modification est à tester est tables.my.sql, dans le dossier /installation.
Notez bien que GRR ne gère que les bases de données compatibles MySQL, donc MariaDB OK, mais pas Postgresql.
YN

**Comment by T0MuX** [comment]
Ok je viens de tester et, en effet, l'installation aboutie correctement en retirant les accents des lignes concernées. Oui j'utilise MariaDB pour sa compatibilité à 100% avec MySQL, et postgresql pour d'autres projets.

T0MuX

**Comment by FanchTheSystem** [comment]
> Où est situé ce fichier tables.sql ?
https://raw.githubusercontent.com/JeromeDevome/GRR/master/installation/tables.my.sql

Peut-être:
```
file -i tables.my.sql 
iconv -f iso-8859-1 -t utf-8 tables.my.sql -o tables.my.sql.utf8 
```

Surtout si : 
https://github.com/JeromeDevome/GRR/blob/6f8213b33dca40a81b95900223d1bb40451de4d5/include/config.inc.php#L93

**Comment by ynaessens** [comment]
Ceci dépend de l'encodage dans la BDD. 
Si les caractères sont en utf-8, alors il vaut mieux que tables.my.sql soit codé en utf-8, mais si la BDD est encodée en latin-1, alors il est mieux de laisser tables.my.sql en ANSI.
@T0MuX : quel est l'encodage de votre BDD ?

**Comment by T0MuX** [comment]
@ynaessens la commande suivante
`mysqladmin -u root -p var | grep -E 'character|collation' | tr -s ' '`
me donne ceci : 
```
| character_set_client | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_database | utf8mb4 |
| character_set_filesystem | binary |
| character_set_results | utf8mb4 |
| character_set_server | utf8mb4 |
| character_set_system | utf8 |
| character_sets_dir | /usr/share/mysql/charsets/ |
| collation_connection | utf8mb4_unicode_ci |
| collation_database | utf8mb4_unicode_ci |
| collation_server | utf8mb4_unicode_ci |
| session_track_system_variables | autocommit,character_set_client,character_set_connection,character_set_results,time_zone |
```

**Comment by ynaessens** [comment]
Merci pour votre retour.
La base étant créée en utf-8, il faut que tables.my.sql soit également encodé en utf-8 pour que les insertions passent avec les accents.
Il faudrait mettre cela au point afin que ce soit transparent pour l'utilisateur.
