### ISSUE TITLE
Reservation Creation

### ISSUE THREAD

**Issue by guebli** [JeromeDevome/GRR#75]
Notice: Undefined variable: adm in /usr/local/www/GRR-v.3.4.1/include/functions.inc.php on line 5342

Après installation de la version 3.4.1 impossible de créer une réservation. Message d'erreur ci-dessus.
Configuration.
Freebsd 12.0 Apache 2.34 Php 7.2

**Comment by ynaessens** [comment]
Bonjour,
merci pour ce signalement.
Cette erreur est liée à l'activation de la génération des xml. 
Je cherche un correctif.
Cordialement,
YN

**Comment by guebli** [comment]
Bonjour,
Merci pour votre réponse.

Après avoir désactiver le module d'export XML et XML+, le message d'erreur disparait lors de la création d'une nouvelle réservation. Cependant on obtient une page blanche.
Cordialement 

TG
![2019-07-30 17_45_17-GRR-3 4 1](https://user-images.githubusercontent.com/16266577/62144428-17a48b00-b2f2-11e9-9a91-559f2d98eba6.png)

**Comment by ynaessens** [comment]
Pas d'erreur apache ni php ?
Cela se produit avec tous les navigateurs ?

**Comment by ynaessens** [comment]
Correctif proposé sur les branches 3.4.1 et devel3

**Comment by guebli** [comment]
Bonjour, ce bug semble résolu.
Le symptôme de la page blanche était du à l'absence du module php-json.

Merci pour le coorectif

**Comment by guebli** [comment]
merci pour le correctif.

TG
