### ISSUE TITLE
Probleme d'affichage des dates 

### ISSUE THREAD

**Issue by guebli** [JeromeDevome/GRR#76]
Date ( nom jour de semaine et des mois affiché en anglais et non en français )

**Comment by guebli** [comment]
Bonjour je rencontre actuellement des problèmes d'affichage des calendriers en français.

Dans le menu gauche le nom des jours de semaine  est en anglais .

La date des réservations est en anglais alors que la date du jour en haut à droite est bien en français.

J'ai éliminé un problème de configuration de serveur par l'installation d'une instance MRBS sur le même serveur, dont le comportement est correct.

Configuration

Freebsd 12.0
Mariadb 10.3.16
php 7.2.21

locale fr_FR.ISO8859-1

ci-joint capture d'écrans des différentes
![2019-08-19 14_39_54-Menu gauche](https://user-images.githubusercontent.com/16266577/63266832-16cb9d00-c291-11e9-9c5b-97df1f267601.png)
![2019-08-19 14_41_14-Menu Central](https://user-images.githubusercontent.com/16266577/63266839-192df700-c291-11e9-9efe-1891d0a7550f.png)
![2019-08-19 14_44_51-Menu Droit](https://user-images.githubusercontent.com/16266577/63266846-1c28e780-c291-11e9-9728-96ad3df7d7ce.png)


 zones

**Comment by guebli** [comment]
Petit oubli la version de grr est la 3.41

TG

**Comment by ynaessens** [comment]
Bonjour, 
merci pour votre message. C'est un problème de serveur, mais puisque MRBS fonctionne correctement, il faudrait que GRR fasse aussi bien !
À approfondir !
Cordialement, 
YN

**Comment by ynaessens** [comment]
À propos, tous les calendriers sont-ils fautifs, ou seulement ceux des pages plannings ?

**Comment by guebli** [comment]
Bonjour,
l'ensemble des calendriers sont concernée par cette anomalie. Tant pour le nom des jours de semaine que pour le nom des mois qui sont toujours affichés en anglais. !!

**Comment by Pafzedog** [comment]
bonjour,

même souci ici sur une Debian Stretch :
résolu en générant la locale FR `dpkg-reconfigure locale`
puis en faisant les corrections sur le fichier `/etc/default/local`
