### ISSUE TITLE
Empêcher qu’une réservation soit retirée ou modifiée par le demandeur  une fois qu’elle ait été accepté par le modérateur

### ISSUE THREAD

**Issue by lrhubert** [JeromeDevome/GRR#77]
Bonjour,
Nous désirons voir implanter les fonctionnalités suivantes: Empêcher qu’une réservation soit retirée ou modifiée par le demandeur une fois qu’elle ait été accepté par le modérateur ET permettre d’utiliser une ancienne réservation pour en créer une nouvelle dans le but d’en faire sa rédaction plus facilement et plus rapidement.  Du financement peut-être négocier.

Laurent

**Comment by ynaessens** [comment]
Bonjour,
sur le premier point, cela revient à créer une notion de réservation non modifiable, notion nouvelle ; cela demande du développement.
Pour le second point, vous avez déjà la fonction "copier cette réservation" : cela ne répond pas à votre souhait ?
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
en reprenant votre question, je vois en page GRR/admin/admin_config2.php la possibilité d'interdire aux utilisateurs le droit de modifier une réservation en cours. Vous voudriez un droit encore plus restreint en empêchant la modification de réservations modérées, ai-je bien compris ?
Cordialement,
YN

**Comment by lrhubert** [comment]
Bonjour,
C'est exact, une fois que la réservation a été accordée par le modérateur on ne veut plus de changement sur celle-ci, surtout  pas un retrait. À moins qu'elle soit à nouveau modérée ou du  moins que le modérateur soit averti du changement.
Merci!

Laurent

--
Laurent Hubert, PhD, LFCS
Professionnel de recherche
Administration de systèmes Linux, déploiement de solutions Open Source
Centre d'imagerie moléculaire de Sherbrooke
Centre de recherche du Centre hospitalier universitaire de Sherbrooke
819 346 1110 x 11836
pagette: 6475
http://www.cims.med.usherbrooke.ca<http://www.cims.med.usherbrooke.ca/>
________________________________

**Comment by ynaessens** [comment]
Bonjour,
il existe déjà un paramètre (page d'édition des ressources) qui interdit aux utilisateurs la modification ou la suppression de leurs propres réservations.
Si l'utilisateur peut modifier ses réservations, il y a une nouvelle demande de modération.
Il n'y aurait donc que la procédure de suppression à modifier...
J'ai donc pour plan : si modification ou suppression sont autorisées, un mail est envoyé pour modération de cette décision, par ordre et par défaut, au gestionnaire de la ressource, du domaine, du site, à l'administrateur général.
Qu'en pensez-vous ?
Cordialement,
YN

**Comment by ynaessens** [comment]
Bonjour,
voici une première modification, sur la branche 3.4.1 : https://github.com/JeromeDevome/GRR/commit/9e78cca3d6c115d01d08cdb59681a940c2859e07
Lorsqu'un utilisateur supprime une réservation qu'il avait faite et qui a été modérée, le modérateur reçoit un mail pour le prévenir. La suppression reste effective.
Cordialement,
YN
