### ISSUE TITLE
L'assistant d'installation révèle le mot de passe administrateur

### ISSUE THREAD

**Issue by Gilrain** [JeromeDevome/GRR#79]
Lors de la création de la base de données, il est demandé à l'étape 3 de renseigner les emails du support et du webmestre.
Ne pas remplir ces champs a pour conséquence de les voir peuplés par le mdp admin en clair dans la base de données et, donc, de l'afficher tel quel sur le site dans leurs champs respectifs dans la section Configuration générale (voir plus, mais dans mon empressement, je n'ai pas cherché au-delà).

**Comment by ynaessens** [comment]
On est bien sur la branche master ?
Cela ne semble pas top, il faudrait mettre une valeur bidon par défaut. 
Ce sera corrigé dès que possible. 
Cordialement 
YN

**Comment by Gilrain** [comment]
> On est bien sur la branche master ?
Oui, à jour avec le dernier commit fb8751af32a8a86a28e48325bc36f5706fd02da0
