### ISSUE TITLE
Problème pour générer une impression des "recherches et stats" version 3.4.1

### ISSUE THREAD

**Issue by gbwin** [JeromeDevome/GRR#80]
Bonjour,
je viens d'avoir un problème pour générer des rapports, en cliquant sur l'icone d'imprimante, alors que celui si fonctionne sur les autres pages.
En regardant le lien "à la volée" affiché en bas du navigateur FF 67.0 il apparraît un espace entre le report.php et le "?"
Puis j'ai regardé dans le fichier report.php et l'aide d'un dev et il s'avère que la ligne 600 comporte une erreur avec un espace en trop.
voici là ligne en question :
`                                                         <a href="./report.php '. '?' . htmlspecialchars($_SERVER['QUERY_STRING']) . '&amp;pview=1" ';`
au lieu de :
`                                                         <a href="./report.php'. '?' . htmlspecialchars($_SERVER['QUERY_STRING']) . '&amp;pview=1" ';`

J'ai testé cela sur notre serveur et la modif fonctionne.
Si vous pouvez faire la modification dans le github.
Bonne journée à tous.
GBwin

**Comment by ynaessens** [comment]
Merci pour le signalement. Ce sera corrigé dès que possible. 
Cordialement 
YN
