### ISSUE TITLE
Problème avec les titre de messages qui sont pas en UTF-8

### ISSUE THREAD

**Issue by gbwin** [JeromeDevome/GRR#81]
Bonjour,
nous utilisons la version 3.4.1 de GRR et le "bug" des accents dans les titres de mails  est toujours présent.
J'ai vu qu'une solution a été apporté il y a env. 2 mois, mais sur le forum du site, pas su le Github.
cf : https://site.devome.com/fr/kunena/proposer-une-correction/409-sujets-mail-mal-encodes#1996
Pourriez-vous corriger cela pour les prochaines versions.
En vous remerciant d'avance.
Cdlt.
GBwin

**Comment by ynaessens** [comment]
Bonjour,
je n'ai pas repris la solution de podz proposée sur le forum, parce qu'elle déclenche une erreur lorsque je la teste (cf. forum).
J'en propose une autre, que je viens de déposer sur la branche devel3. Si vous pouviez la tester et confirmer la résolution du problème, je pourrais la publier sur la branche stable.
Cordialement,
YN

**Comment by gbwin** [comment]
Bonjour,
je n'ai pas eu le temps de faire le test mais dès que je peux, je vous ferais un retour ici.
Je vous oublie pas.
Cdlt.
GBwin

**Comment by remyd1** [comment]
Bonjour,

Simplement pour confirmer que le commit de @ynaessens corrige bien le bug d'accents dans les mails pour GRR en version `3.4.1_rc3`.

Merci,
Cordialement,

**Comment by lhadjadj** [comment]
Bonsoir, j'ai également intégré la modification sur la version 3.4.1 et cela fonctionne sans problème. Les caractères accentués sont bien repris dans l'objet du mail.
Nous utilisons Exchange comme serveur de messagerie. Par contre le corps du message est en texte brute et donc pas formaté..

**Comment by ynaessens** [comment]
Bonjour,
lors de l'affichage, les balises html apparaissent-elles ?
Sinon, rien de surprenant, le code html n'intègre pas de mise en page particulière.
Cordialement,
YN

**Comment by gbwin** [comment]
Bonjour,
veuillez m'excuser pour la non réponse,
j'avais complètement oublié cet issue après que les admin du boulot aient fait une monté de version directement.
Désolé je clôture donc.
gbwin

**Comment by gbwin** [comment]
Bonjour,
veuillez m'excuser pour la non réponse,
j'avais complètement oublié cet issue après que les admin du boulot aient fait une monté de versiondirectement.
Désolé je clôture donc.
gbwin
