### ISSUE TITLE
Blank page after ldap login, and unable validate reservation

### ISSUE THREAD

**Issue by yb45** [JeromeDevome/GRR#82]
Good morning and thank you for this tools. After installing version GRR 3.4.0b (upgrade of 1.9), I encountered 2 problems. The first was with the ldap login. The solution was to comment the line nettoieLogConnexion() in the login.php file for the moment.

The second problem avoid valid form with save button on valid_entry.php. It generate a lot of warnin and error in javascript. The solution was to replace the last lang.fr on this website because the zip file GRR340b.zip contains a bad file with quote an no scape characters \. Thank you in advance,

**Comment by ynaessens** [comment]
Hello !
Thank you for using our software and reporting these issues.
Can you access GRR after LDAP login with your correction ? No side effect ?
For the second issue, you should use later releases either 3.4.0d or 3.4.1, and tell us if it's all right.
Thank you.

**Comment by yb45** [comment]
Hi and thank you very much for your answer! It seems working fine now with the version 3.4.1. 
With the previous version, I confirm it was possible to access GRR commenting this line. Best regards,
