### ISSUE TITLE
PHP Fatal error start_page_w_header

### ISSUE THREAD

**Issue by sparkodutos** [JeromeDevome/GRR#83]
Bonjour,

Lors de la modification horaire d'une réservation, page blanche après la validation.

Dans les logs apache : 
PHP Fatal error:  Uncaught Error: Call to undefined function start_page_w_header() in /var/www/html/edit_entry_handler.php:778

Aucune trace de cette fonction dans le code source de l'appli.

Cordialement

edit : politesse

**Comment by ynaessens** [comment]
Bonjour,
vous avez installé les scripts de quelle branche ?
Cordialement,
YN

**Comment by sparkodutos** [comment]
Bonjour,

Version Git à jour origin/master

Cordialement

**Comment by ynaessens** [comment]
Bonjour,
j'ai commité un ajout. Merci de nous dire si le problème est résolu.
Cordialement,
YN

**Comment by sparkodutos** [comment]
Après un fetch/pull la modification d'une réservation semble fonctionnelle !

Merci
