### ISSUE TITLE
Impossible de régler les privilèges grr [3.4.1 RC3]

### ISSUE THREAD

**Issue by houdini69** [JeromeDevome/GRR#86]
Bonjour,
Nous utilisons depuis plusieurs mois grr [3.4.1 RC3] avec une dizaine d'utilisateurs et il fonctionne très correctement. J'ai noté cependant l'impossibilité de régler les privilèges. La documentation générale indique : "Il est possible de modifier le statut d'un utilisateur en cliquant sur le lien à gauche des nom et prénom de l'utilisateur". Or, il n'y a pas de colonne à gauche des nom et prénom dans notre cas (voir copie d'écran).
Laurent

![Snapshot](https://user-images.githubusercontent.com/24533104/67202911-11faa500-f40a-11e9-8533-b83f167c407b.png)

**Comment by ynaessens** [comment]
Bonjour,
à gauche de la colonne Nom Prénom, je vois une colonne Login. En cliquant sur le login, vous n’arrivez pas à la fiche utilisateur ?
Cordialement,
YN

**Comment by houdini69** [comment]
Bonjour,
Il y a bien une colonne "Nom de login" mais pas de liens associés à ces noms. Si je clique sur un des noms dans la colonne "Nom et prénom" (lien actif dans ce cas) je me retrouve sur la page "Modification d'un utilisateur existant" sans possibilités de changer les privilèges.
Cordialement,
Laurent

**Comment by ynaessens** [comment]
Bonjour,
autant pour moi (je n'étais pas devant GRR lorsque je vous ai répondu).
Le lien actif est bien sur la colonne Nom et Prénom, et envoie sur la fiche utilisateur, dans laquelle il est possible de modifier le statut de l'utilisateur (visiteur, usager, gestionnaire des utilisateurs, administrateur).
Si vous voulez accéder aux statuts intermédiaires (gestionnaire de domaine ou de ressource, accès aux domaines restreints), il faut passer par les domaines ou ressources concernés.
Je corrige néanmoins la documentation sur l'emplacement du lien à suivre pour modifier le statut. Merci pour votre question.
Cordialement,
YN

**Comment by houdini69** [comment]
Bonsoir,
Merci pour les éclaircissements. Une suggestion : rajouter en aide-mémoire sur la page qui liste les utilisateurs la signification des lettres concernant les privilèges.
Cordialement,
Laurent
