### ISSUE TITLE
Administrateur d'un domaine : pas de lien vers réservation à modérer

### ISSUE THREAD

**Issue by anteldan** [JeromeDevome/GRR#91]
En version 3.4.1b
J'ai créé un domaine restreint. 
Dans ce domaine restreint, un utilisateur créé une réservation sur une ressource "modérée". 
Un administrateur du domaine restreint quand il consulte le planning voit dans le bandeau qu'il y a une réservation à modérer. 
Il clique sur cette information, il arrive sur la page d'accueil de l'administration, mais il n'a pas le lien pour accéder à la réservation à modérer.
L'administrateur général du site, lui, a le lien pour ouvrir directement la réservation à modérer.

**Comment by ynaessens** [comment]
Dans la page d'accueil, il a la liste des réservations à modérer, mais sans lien ?

**Comment by anteldan** [comment]
Je pense qu'il faut jeter un oeil dans la fonction resaToModerate($user). Dans le cas où le user est admin d'un domaine et non pas admin général. Je pourrai m'en occuper un peu plus tard, mais si @ynaessens a le temps maintenant, c'est encore mieux.

Sur n'importe quelle page du planning, il y a le bandeau sur fond rouge :
![Capture du 2020-02-11 16-41-42](https://user-images.githubusercontent.com/34574269/74252337-d43dc700-4ced-11ea-8669-308c2507346f.png)

Mais quand je clique sur le bandeau j'arrive sur la page d'accueil de l'administration :
![Capture du 2020-02-11 16-42-38](https://user-images.githubusercontent.com/34574269/74252401-f1729580-4ced-11ea-9037-2e99940a4da1.png)

L'administrateur général, lui a :
![Capture du 2020-02-11 16-42-11](https://user-images.githubusercontent.com/34574269/74252478-0cdda080-4cee-11ea-870e-805c8cfe1aca.png)

puis :
![Capture du 2020-02-11 16-43-09](https://user-images.githubusercontent.com/34574269/74252514-17983580-4cee-11ea-9798-635e31a9ddcb.png)

**Comment by anteldan** [comment]
Trouvé : le lien sur fond rouge avec les réservations à modérer envoie vers l'accueil de l'administration mais sans les paramètres `site` et `area`.
J'ai testé en les ajoutant manuellement dans l'URL de la page d'accueil d'administration et j'ai bien les liens vers les résa à modérer

**Comment by anteldan** [comment]
Je me pose une question quand même sur ce qui est établi. L'administrateur d'un domaine n'a l'avertissement que lorsqu'il visualise le domaine concerné. S'il visualise un autre domaine auquel il a accès en tant que simple usager l'avertissement ne lui apparaît pas.
Un administrateur général aura toujours quant à lui le message d'avertissement même sil visualise un domaine dans lequel il n'y pas de modération à faire.

Est-ce voulu ?

Ce n'est pas hyper génant comme comportement, car on peut supposer qu'un administrateur d'un domaine ira visualiser régulièrement son domaine et aura donc l'avertissement à ce moment là.

**Comment by ynaessens** [comment]
Ce n'est pas voulu et ce serait mieux si la liste des réservations à modérer s'affichait quelle que soit l'origine de l'accès à la page accueil de l'administration. Je vois cela dès que possible.
