### ISSUE TITLE
Impossible de se connecter avec le compte de base

### ISSUE THREAD

**Issue by SibreuR** [JeromeDevome/GRR#94]
Bonjour, 
J'ai installé GRR sur une machine CentOS 7 en suivant la procédure et en installant moi même la base de données.
Cependant j'ai accès bien accès au site mais en renseignant les Login et Mdp de base le site me renvoie l'erreur : "Echec de connexion à GRR. Identifiant ou mot de passe incorrect".
J'ai moi même essayer de modifier les identifiants manuellement dans la base de données mais sans succès.
Merci

**Comment by ynaessens** [comment]
Bonjour,
quelle version de GRR avez-vous installée ?
Cordialement,
YN

**Comment by SibreuR** [comment]
GRR version 3.4.0
PHP version 5.4.16
MySQL version 5.5.64

**Comment by ynaessens** [comment]
Et ainsi administrateur/azerty ne fonctionne pas ?

**Comment by SibreuR** [comment]
Nan administrateur/azerty ne fonctionne pas, en allant inspecter la base de données j'ai remarqué que la valeur pour password était "VariableInstal05" j'ai donc essayé avec cette valeur comme mot de passe et même erreur, j'ai donc modifier la valeur dans le script "/installation/tables.my.sql" pour avoir azerty, azerty est bien renseigné comme mot de passe dans la bdd mais l'erreur persiste.

**Comment by ynaessens** [comment]
Ce que vous me dites laisse à croire que vous avez mélangé des versions de GRR. VariableInstal05 n'apparaît que dans la version 4.0 en cours de développement. Avec une version stable, la 3.4.1b de préférence, administrateur/azerty devrait fonctionner.
Si vous voulez modifier le mot de passe en base, il faut encoder azerty par la procédure MD5, ce qui donne ab4f63f9ac65152575886860dde480a1.

**Comment by SibreuR** [comment]
Merci problème résolu, j'ai modifier le script de la base de données avec azerty encodé en MD5 et cela fonctionne, par contre le script de base me mettais bien "VariableInstal05" alors que j'ai vérifier et j'ai bien récupéré le git de la version 3.4.0

**Comment by ynaessens** [comment]
Bien.
Cependant, il n'y a pas de VariableInstal dans le script de la 3.4.0 et je vous recommande vivement d'utiliser la version 3.4.1b qui corrige pas mal de bugs.
Cordialement,
YN
