### ISSUE TITLE
[Mineur] Remplissage de la rubrique "brève description" dans le formulaire réservation

### ISSUE THREAD

**Issue by anteldan** [JeromeDevome/GRR#97]
GRR 3.4.1b
admin/admin_config1.php

Il manque l'astérisque dans le formulaire dans le cas où le nom de l'usager est mis par défaut.

Quand le 3ème et dernier cas est sélectionné : 'La rubrique "brève description" contient, par défaut, le nom de l'usager'
Il s'agit du cas précédent 'Le remplissage de la rubrique "brève description" est obligatoire' avec pré-remplissage par défaut.
Par contre, dans le formulaire de réservation il n'y a pas d'astérisque sur l'étiquette "Brève description", donc si l'utilisateur vide le champ "Brève description" car il n'a pas l'indication habituelle du caractère obligatoire du champ il aura un message d'erreur lors de l'enregistrement.

**Comment by ynaessens** [comment]
Bonjour,
les modifications du commit [https://github.com/JeromeDevome/GRR/commit/ae6d20880ec1093083ab418379961205d2d40fbd](url) devraient résoudre le problème.
Merci pour le signalement.
Cordialement,
YN

**Comment by anteldan** [comment]
Merci pour les corrections, avec l'astérisque sur le Type également.
