### ISSUE TITLE
Erreur droits usagers

### ISSUE THREAD

**Issue by SibreuR** [JeromeDevome/GRR#98]
Bonjour, mon GRR est totalement fonctionnel.
Seul problème, selon la documentation les usagers ont la possibilité de modifier leur compte.
Pour moi ce n'est pas le cas, quand un usager clique sur "Gérer mon compte" il tombe sur une page lui indiquant qu'il n'a pas les doits pour effectuer cette action, le grade le plus bas pouvant le faire sont les "gestionnaire des utilisateurs" cependant je ne veux pas que tous mes utilisateurs aient ce grade pour modifier leur compte car ils auront accès à la partie Administration, et même s'ils ne pourront pas s'amuser avec les autres usagers qui ont le même grade qu'eux je ne veux pas qu'ils aient accès à cette partie.
Merci
Cordialement.

**Comment by ynaessens** [comment]
Bonjour,
dans la page de gestion des utilisateurs (Administration > Utilisateurs et accès > Utilisateurs ), avez-vous vérifié que ces droits sont bien ouverts ?
Quelle version de GRR avez-vous installée ?
Cordialement,
YN

**Comment by SibreuR** [comment]
GRR version 3.4.0
PHP version 5.4.16
MySQL version 5.5.64
Voici mes versions
Et qu'entendez vous par "ces droits sont bien ouverts" quand je vais sur la page gestion des utilisateurs je ne peux que en rajouter, voir ceux avec des mots de passe faible, et gerer chaque utilisateurs un par un.
Cordialement.

**Comment by anteldan** [comment]
Bonjour,

Dans la version 3.4.1 il y a une section "Droits généraux des utilisateurs" qui permet de gérer ces droits.
![Capture du 2020-03-04 11-37-42](https://user-images.githubusercontent.com/34574269/75871343-b525e700-5e0c-11ea-84e7-40db23f5fcac.png)

**Comment by ynaessens** [comment]
Oui, et cela existe déjà en 3.4.0d
Mais le mieux est de profiter des dernières améliorations en utilisant la 3.4.1b :-)

**Comment by SibreuR** [comment]
J'ai bien accès à ces paramètres dans les configurations générale et elles sont bien configurer pour "Tous".

**Comment by anteldan** [comment]
Voici même une capture d'écran de la 3.4.0b (celle qui est en production chez nous), et je suis d'accord avec Monsieur Yan, il vaut mieux passer en 3.4.1b :-)
![Capture du 2020-03-04 11-41-53](https://user-images.githubusercontent.com/34574269/75871779-63ca2780-5e0d-11ea-81f8-81b1eb5e0299.png)

**Comment by anteldan** [comment]
Ce sont des comptes locaux ou extérieurs ?

**Comment by SibreuR** [comment]
Ce sont des comptes locaux, créer manuellement via l'interface de GRR.

**Comment by ynaessens** [comment]
De mon côté en utilisateur sans privilèges, j'ai bien accès à la page Mon Compte, avec une erreur php : 
Warning:  session_name(): Cannot change session name when session is active in C:\xampp\htdocs\GRR340\include\session.inc.php on line 831
erreur résolue en 3.4.1b ;-)

**Comment by SibreuR** [comment]
Je ne tombe pas sur une erreur mais juste un message "Accès Refusé" et un lien pour retourner en arrière.
Y a t'il une méthode pour mettre à jour sa version sans devoir faire une nouvelle installation et perdre tous mes usagers ?

**Comment by ynaessens** [comment]
Oui, bien sûr !
Faire une sauvegarde de la base depuis GRR,
mettre de côté les fichiers de configuration et les personnalisations s'il y en a,
téléverser les nouveaux scripts,
restaurer la sauvegarde,
se connecter en administrateur (avec login et MDP de la base),
GRR va alors se plaindre que la base n'est pas à jour : mettre à jour.

Tiens, je vois que ce n'est pas documenté... soit j'ai mal lu, soit vous confirlez que tout s'est bien passé et je mettrai les documentations à jour.
